// vue/src/lib/slider/examples/step.vue
<template>
  <div>
    <h5>Low: {{slider1.low}} High: {{slider1.high}}</h5>
    <md-slider
      canCross
      :min="0"
      :max="500"
      :tick="100"
      :value="slider1"
      :step="20"
      @change="val => slider1 = val"
    />
  </div>
</template>

<script>
export default {
  name: 'ExampleSliderStep',

  data() {
    return {
      slider1: { low: 100, high: 200 },
    };
  },
};
</script>

// react/src/lib/Slider/examples/Step.js
import React from 'react';
import { Slider } from '@momentum-ui/react';
export default class SliderStep extends React.Component {
  state = {
    slider1: { low: 100, high: 200 },
    slider2: { low: 100, high: 200 },
  }
  render() {
    return (
      <span>
        <div className="row" key='child-0'>
          <div>Low: {this.state.slider1.low} High: {this.state.slider1.high}</div>
          <Slider
            min={0}
            max={500}
            tick={100}
            value={this.state.slider1}
            step={20}
            canCross
            onChange={value => this.setState({ slider1: value })}
          />
        </div>
        <br key='child-1' />
        <div className="row" key='child-2'>
          <div>Low: {this.state.slider2.low} High: {this.state.slider2.high}</div>
          <Slider
            min={0}
            max={500}
            tick={100}
            value={this.state.slider2}
            step={50}
            canCross
            onChange={value => this.setState({ slider2: value })}
          />
        </div>
      </span>
    );
  }
}
