// react/src/lib/Popover/index.js
import React from 'react';
import PropTypes from 'prop-types';
import { EventOverlay } from '@collab-ui/react';
import { omit } from 'lodash';

/**
 * @category communication
 * @component popover
 * @variations collab-ui-react
 */

class Popover extends React.Component {
  static displayName = 'Popover';

  state = {
    isOpen: false
  };

  componentWillUnmount() {
    this.hideTimerId && clearTimeout(this.hideTimerId);
    this.showTimerId && clearTimeout(this.showTimerId);
  }

  delayedHide = e => {
    const { delay, hideDelay, onClose } = this.props;

    if (this.showTimerId) {
      clearTimeout(this.showTimerId);
      this.showTimerId = null;
    }

    const popoverHideTime = hideDelay
      ? hideDelay
      : delay;

    this.hideTimerId = setTimeout(() => {
      this.hideTimerId = null;
      this.setState(
        { isOpen: false },
        onClose && onClose(e)
      );
    }, popoverHideTime);

    e.stopPropagation();
  };

  delayedShow = e => {
    const { delay, showDelay } = this.props;

    if (this.hideTimerId) {
      clearTimeout(this.hideTimerId);
      this.hideTimerId = null;
    }

    const popoverShowTime = showDelay
      ? showDelay
      : delay;

    this.showTimerId = setTimeout(() => {
      this.showTimerId = null;
      this.setState({ isOpen: true });
    }, popoverShowTime);

    e.stopPropagation();
  };

  handleClose = e => {
    const { onClose } = this.props;

    this.setState(
      { isOpen: false },
      onClose && onClose(e)
    );
  };

  handleMouseEnter = e => {
    const { children } = this.props;

    children.props.onMouseEnter && children.props.onMouseEnter(e);
    return !this.showTimerId && !this.state.isOpen && this.delayedShow(e);
  };

  handleMouseLeave = e => {
    const { children } = this.props;
    if (this.hasFocus) {
      return false;
    }

    children.props.onMouseLeave && children.props.onMouseLeave(e);
    return !this.hideTimerId && this.state.isOpen && this.delayedHide(e);
  };

  handleBlur = e => {
    const { children } = this.props;
    this.hasFocus = false;

    children.props.onBlur && children.props.onBlur(e);
    this.handleMouseLeave(e);
  };

  handleClick = e => {
    const { children, doesAnchorToggle } = this.props;
    const { isOpen } = this.state;

    this.hasFocus = true;

    children.props.onClick && children.props.onClick(e);

    if(!this.showTimerId) {
      return !isOpen
        ? this.delayedShow(e)
        : doesAnchorToggle && this.handleBlur(e);
    }
  }

  handleFocus = e => {
    const { children } = this.props;
    const { isOpen } = this.state;

    this.hasFocus = true;
    
    children.props.onFocus && children.props.onFocus(e);
    
    if(!this.showTimerId) {
      return !isOpen
        ? this.delayedShow(e)
        : this.handleBlur(e);
    }
  };

  render() {
    const { isOpen } = this.state;
    const {
      children,
      className,
      content,
      popoverTrigger,
      showArrow,
      ...props
    } = this.props;

    const otherProps = omit({...props}, [
      'onClose'
    ]);

    const getTriggers = () => {
      const triggerProps = {};
      triggerProps.ref = ele => (this.anchorRef = ele);
      triggerProps.key = 'child-1';

      switch (popoverTrigger) {
        case 'MouseEnter':
          triggerProps.onMouseEnter = this.handleMouseEnter;
          triggerProps.onMouseLeave = this.handleMouseLeave;

          triggerProps.onFocus = this.handleFocus;
          triggerProps.onBlur = this.handleBlur;
          break;

        case 'Click':
          triggerProps.onClick = this.handleClick;
          
          triggerProps.onBlur = null;
          triggerProps.onFocus = null;
          triggerProps.onMouseEnter = null;
          triggerProps.onMouseLeave = null;

          break;

        case 'Focus':
          triggerProps.onFocus = this.handleFocus;
          triggerProps.onBlur = this.handleBlur;
          triggerProps.onMouseEnter = null;
          triggerProps.onMouseLeave = null;

          break;
      }

      return triggerProps;
    };

    const anchorWithTriggers =
      children && React.cloneElement(children, getTriggers());

    return (
      <span>
        {anchorWithTriggers}
        <EventOverlay
          anchorNode={this.anchorRef}
          className={className}
          close={this.handleClose}
          isOpen={isOpen}
          ref={ref => this.overlay = ref}
          showArrow={showArrow}
          {...otherProps}
        >
          {content}
        </EventOverlay>
      </span>
    );
  }
}

Popover.defaultProps = {
  className: '',
  delay: 0,
  doesAnchorToggle: true,
  hideDelay: 0,
  onClose: null,
  popoverTrigger: 'MouseEnter',
  showArrow: true,
  showDelay: 0,
};

Popover.propTypes = {
  /**
   * this should be the popover trigger(this should be a stateful component)
   */
  children: PropTypes.element.isRequired,
  /**
   * css class names which goes over popover container
   */
  className: PropTypes.string,
  /**
   * the content that goes into the popover
   */
  content: PropTypes.oneOfType([PropTypes.element, PropTypes.node]).isRequired,
  /**
   * the delay for popover on hover, click, focus (hide/show)
   */
  delay: PropTypes.number,
  /**
   * Boolean for whether the Anchor Toggles the Popover
   */
  doesAnchorToggle: PropTypes.bool,
  /**
   * the hide delay for popover on hover, click, focus
   */
  hideDelay: PropTypes.number,
  /**
   * optional function that will execute on close
   */
  onClose: PropTypes.func,
  /**
   * Event that will trigger popover appearance
   */
  popoverTrigger: PropTypes.oneOf(['MouseEnter', 'Click', 'Focus']),
   /**
   * Boolean for whether the Arrow should show
   */
  showArrow: PropTypes.bool,
  /**
   * the show delay for popover on hover, click, focus
   */
  showDelay: PropTypes.number,
};

export default Popover;

/**
* @name Popover Default
*
* @category communication
* @component popover
* @section default
*
* @js

 import {
  Button
} from '@collab-ui/react';

 export default function Default() {

  const content = (
    <span key="1" style={{ padding: '10px'}}>Popover Top</span>
  );

  return (
    <div className='row'>
      <div className="docs-example docs-example--spacing">

        <h3>
          Props
          <p><code className="small">direction=(top-center)</code></p>
          <p><code className="small">{'targetOffset=({vertical: 10})'}</code></p>
        </h3>
        <Popover content={content} direction={'top-center'} targetOffset={{vertical: 10}}>
          <Button children='Hover' ariaLabel='Hover' />
        </Popover>

      </div>
      <div className="docs-example docs-example--spacing">

        <h3>
          Props
          <p><code className="small">delay=(500)</code></p>
          <p><code className="small">direction=(top-center)</code></p>
        </h3>
        <Popover content={content} delay={500} direction={'top-center'}>
          <Button children='Hover with Delay' ariaLabel='Hover with Delay' />
        </Popover>

      </div>
    </div>
  );
}
**/

/**
* @name Popover on Click
*
* @category communication
* @component popover
* @section onclick
*
* @js

 import {
  Button
} from '@collab-ui/react';

 export default function PopOverClick() {

    const content = (
      <span key="1" style={{ padding: '10px'}}>Popover Bottom</span>
    );

    return (
      <div className='row'>
        <div className="docs-example docs-example--spacing">

          <h3>
            Props
            <p><code className="small">direction=(bottom-center)</code></p>
            <p><code className="small">popoverTrigger=(Click)</code></p>
          </h3>
          <Popover
            content={content}
            direction={'bottom-center'}
            popoverTrigger={'Click'}
          >
            <Button
              children='Click'
              ariaLabel='Click'
            />
          </Popover>

        </div>
        <div className="docs-example docs-example--spacing">

          <h3>
            Props
            <p><code className="small">direction=(bottom-center)</code></p>
            <p><code className="small">popoverTrigger=(Click)</code></p>
            <p><code className="small">doesAnchorToggle(false)</code></p>
          </h3>
          <Popover
            content={content}
            direction={'bottom-center'}
            doesAnchorToggle={false}
            popoverTrigger={'Click'}
          >
            <Button
              children='Click No Toggle'
              ariaLabel='Click'
            />
          </Popover>

        </div>
      </div>
    );
}
**/

/**
* @name Popover on Focus
*
* @category communication
* @component popover
* @section onfocus
*
* @js

 import {
  Button
} from '@collab-ui/react';

 export default function PopOverFocus() {
   
  const contentLeft = (
    <span key="1" style={{ padding: '10px'}}>Popover Left</span>
  );

  const contentRight = (
    <span key="1" style={{ padding: '10px'}}>Popover Right</span>
  );

  return (
    <div className='row'>
      <div className="docs-example docs-example--spacing">

        <h3>
          Props
          <p><code className="small">direction=(right-center)</code></p>
          <p><code className="small">popoverTrigger=(Focus)</code></p>
        </h3>
        <Popover
          content={contentRight}
          direction={'right-center'}
          popoverTrigger={'Focus'}
        >
          <Button
            children='Focus Right'
            ariaLabel='Focus Right'
          />
        </Popover>

      </div>
      <div className="docs-example docs-example--spacing">

        <h3>
          Props
          <p><code className="small">direction=(left-center)</code></p>
          <p><code className="small">popoverTrigger=(Focus)</code></p>
        </h3>
        <Popover
          content={contentLeft}
          direction={'left-center'}
          popoverTrigger={'Focus'}
        >
          <Button
            children='Focus Left'
            ariaLabel='Focus Left'
          />
        </Popover>

      </div>
    </div>
  );
}
**/

// vue/src/lib/popover/index.vue
<script>
import cloneElement from '../utils/cloneElement';
import assign from 'lodash/assign';
import omit from 'lodash/omit';
import { Fragment } from 'vue-fragment'

export default {
  name: 'md-popover',

  components: { Fragment },

  data() {
    return {
      isOpen: false,
      isHovering: false,
      nativeOn: null,
    }
  },

  render(h) {
    const isOpen = this.isOpen;
    const {
      className,
      overflowType,
      popoverTrigger,
      showArrow,
      ...props
    } = this.$props;

    const otherProps = omit({...props}, [
      'delay',
      'doesAnchorToggle',
      'hideDelay',
      'hoverDelay',
      'showDelay',
      'startOpen',
    ]);

    const getTriggers = () => {
      const triggerProps = {
        attrs: {
          ref: 'anchorRef',
          key: 'child-1',
        },
        nativeOn: {},
      };

      switch (popoverTrigger) {
        case 'MouseEnter':
          triggerProps.nativeOn.mouseenter = this.handleMouseEnter;
          triggerProps.nativeOn.mouseleave = this.handleMouseLeave;

          triggerProps.nativeOn.focus = this.handleFocus;
          triggerProps.nativeOn.blur = this.handleBlur;
          break;

        case 'Click':
          triggerProps.nativeOn.click = this.handleClick;
          break;

        case 'Focus':
          triggerProps.nativeOn.focus = this.handleFocus;
          triggerProps.nativeOn.blur = this.handleBlur;
          break;
      }

      return triggerProps;
    };

    const node = this.$slots.default && this.$slots.default[0];

    if (!this.nativeOn) {
      this.nativeOn = {};
      node.data && node.data.nativeOn && assign(this.nativeOn, node.data.nativeOn);
    }

    const data = getTriggers();
    if (node && node.data) {
      node.data.on = {};
      node.data.nativeOn = {};
      assign(node.data.attrs, data.attrs);
      assign(node.data.on, data.nativeOn);
      assign(node.data.nativeOn, data.nativeOn);
    }

    const getComponentData = () => ({
      class: className,
      attrs: {
        ref: 'overlay',
        ...this.$attrs,
      },
      props: {
        anchorNode: node.elm,
        isOpen: isOpen,
        showArrow: showArrow,
        contentStyle: { overflow: overflowType },
        ...popoverTrigger === 'Focus' && { allowClickAway: false },
        ...otherProps,
        ...this.$attrs,
      },
      on: {
        close: this.handleClose,
      },
      nativeOn: {
        ...popoverTrigger === 'MouseEnter' && {
          mouseenter: e => {
              this.isHovering = true;
              this.isOpen = true;
            },
          mouseleave: e => {
              this.isHovering = false;
              this.delayedHide(e);
            },
        },
      },
    });

    return (
      h(this.fragment ? 'fragment' : 'span',
        {},
        [node, isOpen &&
          h('md-event-overlay', getComponentData(), this.$slots.content)]
      )
    );
  },

  props: {
    /** @prop Optional CSS class names which goes over popover container | '' */
    className: String,
    /** @prop The delay for popover on hover, click, focus (hide/show) | 0 */
    delay: {
      type: [Number, String],
      default: 0
    },
    /** @prop Boolean for whether the Anchor Toggles the Popover | true */
    doesAnchorToggle: {
      type: Boolean,
      default: true
    },
    /** @prop Use fragment tag | true */
    fragment: {
      type: Boolean,
      default: true
    },
    /** @prop The hide delay for popover on hover, click, focus | 0 */
    hideDelay: {
      type: [Number, String],
      default: 0
    },
    /** @prop The hover delay for checking whether we are still hovering before closing | 500 */
    hoverDelay: {
      type: [Number, String],
      default: 500
    },
    /** @prop Optional prop that controls overflow css style of EventOverlay | 'auto' */
    overflowType: {
      type: String,
      default: 'auto'
    },
    /** @prop Event that will trigger popover appearance | 'MouseEnter' */
    popoverTrigger: {
      type: String,
      default: 'MouseEnter',
      validator: (value) => ['MouseEnter', 'Click', 'Focus', 'None'].indexOf(value) !== -1
    },
    /** @prop Boolean for whether the Arrow should show | true */
    showArrow: {
      type: Boolean,
      default: true
    },
    /** @prop The show delay for popover on hover, click, focus | 0 */
    showDelay: {
      type: [Number, String],
      default: 0
    },
    /** @prop Should Popover start open | false */
    startOpen: Boolean,
  },

  methods: {
    delayedHide(e) {
      const { delay, hideDelay } = this.$props;
      if ( this.isHovering ) return;

      if (this.showTimerId) {
        clearTimeout(this.showTimerId);
        this.showTimerId = null;
      }

      const popoverHideTime = hideDelay
        ? hideDelay
        : delay;

      this.hideTimerId = setTimeout(() => {
        this.hideTimerId = null;
        this.isOpen = false;
        this.isHovering = false;
        this.$emit('close', e);
      }, popoverHideTime);

      e && e.stopPropagation();
    },

    delayedShow(e) {
      const { delay, showDelay } = this.$props;

      if (this.hideTimerId) {
        clearTimeout(this.hideTimerId);
        this.hideTimerId = null;
      }

      const popoverShowTime = showDelay
        ? showDelay
        : delay;

      this.showTimerId = setTimeout(() => {
        this.showTimerId = null;
        this.isOpen = true;
        this.isHovering = true;
      }, popoverShowTime);

      e && e.stopPropagation();
    },

    handleClose(e) {
      this.isOpen = false;
      this.$emit('close', e);
    },

    handleMouseEnter(e) {
      this.nativeOn && this.nativeOn.mouseenter && this.nativeOn.mouseenter(e);
      return !this.showTimerId && !this.isOpen && this.delayedShow(e);
    },

    delayCheckHover(e) {
      const { hoverDelay } = this.$props;
      this.isHovering = false;
      setTimeout(() => this.delayedHide(e), hoverDelay);
    },

    handleMouseLeave(e) {
      if (this.hasFocus) {
        return false;
      }

      if (this.showTimerId) {
        clearTimeout(this.showTimerId);
        this.showTimerId = null;
      }

      this.nativeOn && this.nativeOn.mouseleave && this.nativeOn.mouseleave(e);
      return !this.hideTimerId && this.isOpen && this.delayCheckHover(e);
    },

    handleBlur(e) {
      this.hasFocus = false;

      this.nativeOn && this.nativeOn.blur && this.nativeOn.blur(e);
      this.handleMouseLeave(e);
    },

    handleClick(e) {
      const { doesAnchorToggle } = this.$props;

      this.hasFocus = true;

      this.nativeOn && this.nativeOn.click && this.nativeOn.click(e);
      if(!this.showTimerId) {
        return !this.isOpen
          ? this.delayedShow(e)
          : doesAnchorToggle && this.handleBlur(e);
      }
    },

    handleFocus(e) {
      this.hasFocus = true;

      this.nativeOn && this.nativeOn.focus && this.nativeOn.focus(e);
      if(!this.showTimerId) {
        return !this.isOpen
          ? this.delayedShow(e)
          : this.handleBlur(e);
      }
    },
  },

  mounted() {
    this.startOpen &&
    this.delayedShow();
  },

  beforeDestroy() {
    this.hideTimerId && clearTimeout(this.hideTimerId);
    this.showTimerId && clearTimeout(this.showTimerId);
  },
};
</script>
