// react/package/src/lib/Alert/examples/Success.js
import React from 'react';
import {
  Alert,
  AlertContainer,
  Button
} from '@momentum-ui/react';
export default class AlertDefault extends React.PureComponent {
  state = {
    show: false
  }
  render() {
    return (
      <section>
        <div>
          <div className='row'>
            <Button
              ariaLabel='Click to Open'
              onClick={() => this.setState({ show: true })}
              children='Success'
              color='primary'
            />
          </div>
        </div>
        <br />
        <AlertContainer>
          <Alert
            closable
            title='Alert'
            message={'Who\'s awesome?  You are!'}
            dismissBtnProps={{ 
              onClick: () => this.setState({ show: false }),
              ariaLabel: 'Close Alert'
            }}
            show={this.state.show}
            type='success'
          />
        </AlertContainer>
      </section>
    );
  }
}

// vue/src/lib/alert/examples/success.vue
<template>
  <section>
    <div>
      <div class="row">
        <md-button
          ariaLabel="Click to Open"
          @click="() => show = true"
          color="primary"
        >Success</md-button>
      </div>
    </div>
    <br />
    <md-alert-container>
      <md-alert
        closable
        title="Success"
        message="Who's awesome?  You are!"
        :dismissBtnEvents="{
          click: () => show = false
        }"
        :dismissBtnProps="{
          ariaLabel: 'Close Alert'
        }"
        :show="show"
        type="success"
      />
    </md-alert-container>
  </section>
</template>

<script>
export default {
  name: 'ExampleAlertSuccess',

  data() {
    return {
      show: false
    }
  },
};
</script>
