// vue/src/lib/topbar/examples/light.vue
<template>
  <md-topbar
    color="light"
    title="Momentum UI"
  >
    <md-topbar-nav>
      <md-list-item>Develop</md-list-item>
      <md-list-item>Styles</md-list-item>
      <md-list-item>Layout</md-list-item>
      <md-list-item>Navigation</md-list-item>
    </md-topbar-nav>
    <md-topbar-right>
      <div class="md-top-bar__user" />
      <div class="md-top-bar__logged-out">
        <a href="javascript:void(0)">Log In</a>
        <md-button color="blue" ariaLabel="myAriaLabel">
          Button
        </md-button>
      </div>
    </md-topbar-right>
    <md-topbar-mobile :shouldCloseOnClick="false">      
      <md-list-item>Develop</md-list-item>
      <md-list-item>Styles</md-list-item>
      <md-list-item>Layout</md-list-item>
      <md-list-item>Navigation</md-list-item>
    </md-topbar-mobile>
    
    <template v-slot:brand>
      <a
        href="javascript:void(0)"
        title="Momentum UI"
      >
        <md-icon name="cisco-logo" :size="32" />
      </a>
    </template>
  </md-topbar>
</template>

<script>
export default {
  name: 'ExampleTopbarLight',
};
</script>

// react/package/src/lib/Topbar/examples/Light.js
/* eslint-disable jsx-a11y/anchor-is-valid */
import React from 'react';
import {
  Button,
  Icon,
  ListItem,
  Topbar,
  TopbarMobile,
  TopbarNav,
  TopbarRight,
} from '@momentum-ui/react';

export default class TopbarLight extends React.Component {
  render() {
    return (
      <Topbar
        color='light'
        brandAnchorElement={
          <a
            href='javascript:void(0)'
            title='Momentum UI'
          >
            <Icon name='cisco-logo' />
          </a>
        }
      >
        <TopbarNav>
          <ListItem>Develop</ListItem>
          <ListItem>Styles</ListItem>
          <ListItem>Layout</ListItem>
          <ListItem>Navigation</ListItem>
        </TopbarNav>
        <TopbarRight>
          <div className='md-top-bar__user' />
          <div className='md-top-bar__logged-out'>
            <a href='javascript:void(0)'>Log In</a>
            <Button color='blue' ariaLabel='myAriaLabel'>
              Button
            </Button>
          </div>
        </TopbarRight>
        <TopbarMobile shouldCloseOnClick={false}>
          <a
            href='javascript:void(0)'
            title='Momentum UI'
          >
            <Icon name='cisco-logo' />
          </a>
          <ListItem>Develop</ListItem>
          <ListItem>Styles</ListItem>
          <ListItem>Layout</ListItem>
          <ListItem>Navigation</ListItem>
        </TopbarMobile>
      </Topbar>
    );
  }
}
/* eslint-enable jsx-a11y/anchor-is-valid */
