// vue/src/lib/label/index.vue
<script>
export default {
  name: 'md-label',

  render: function (h) {
    const {
      htmlFor,
      label,
      theme,
      ...props
    } = this.$props;

    return (
      <label
        class={`${theme ? ` md-label--${theme}` : ''}`}
        for={htmlFor}
        {...props}
      >
        {
          label
          ? <span>{label}</span>
          : this.$slots.default
        }
      </label>
    )
  },

  props: {
    /** @prop HTML ID for associated Input | null */
    htmlFor: {
      type: String,
      required: true
    },
    /** @prop Required Label text | null */
    label: String,
    /** @prop Set Label's color theme | '' */
    theme: {
      type: String,
      default: ''
    },
  }
};
</script>

// angular/src/lib/label/label.component.ts
import {
  Component,
  Input,
} from '@angular/core';

@Component({
  selector: 'md-label',
  template: `
    <label
      [attr.for]="htmlFor"
      [ngClass]="[
        'md-label',
        (theme && 'md-label--' + theme) || '',
        (className && className) || ''
      ]"
    >
      <span *ngIf="label">{{label}}</span>
      <ng-content></ng-content>
    </label>
  `,
  styles: []
})

export class LabelComponent {
  /** @prop HTML class name for associated Input | '' */
  @Input() public className: string;
  /** @prop Set Label's color theme | '' */
  @Input() public theme: string;
  /** @prop Optional Label text | null */
  @Input() public label: string;
  /** @prop HTML ID for associated control | null */
  @Input() public htmlFor: string;
}


<label
  [ngClass]="labelClasses"
>
  <span>{{label}}</span>
</label>


<!-- htmlFor="{{htmlId}}" -->
