// vue/src/lib/modal/examples/large.vue
<template>
  <div class="row">
    <div class="docs-example docs-example--spacing">
      <md-button
        @click="() => showModal = true"
        ariaLabel="Open Modal"
        color="primary"
      >Large Modal</md-button>
      <md-button
        @click="() => showModal2 = true"
        ariaLabel="Open Modal 2"
        color="primary"
      >Large Modal with Message</md-button>
      <md-modal
        applicationId="app"
        @hide="showModal = false"
        :show="showModal"
        ref="modal1"
        htmlId="modal1"
        size="large"
      >
        <md-modal-header
          headerLabel="Large Modal"
          showCloseButton
        />
        <md-modal-body>
          <form ref="form1" />
        </md-modal-body>
        <md-modal-footer>
          <md-button
            @click="() => $refs.modal1.closeModal()"
            ariaLabel="Close Modal"
            color="default"
          >Cancel</md-button>
          <md-button
            type="submit"
            @click="() => $refs.modal1.closeModal()"
            ariaLabel="Submit Form"
            color="blue"
          >OK</md-button>
        </md-modal-footer>
      </md-modal>
      <md-modal
        applicationId="app"
        @hide="showModal2 = false"
        :show="showModal2"
        ref="modal2"
        htmlId="modal2"
        size="large"
      >
        <md-modal-header
          headerLabel="Large Modal"
          message="To create a meeting invite manually, copy and paste the meeting information and people into your email calendar invite."
          showCloseButton
        />
        <md-modal-body>
          <form ref="form1" />
        </md-modal-body>
        <md-modal-footer>
          <md-button
            @click="() => $refs.modal2.closeModal()"
            ariaLabel="Close Modal"
            color="default"
          >Cancel</md-button>
          <md-button
            type="submit"
            @click="() => $refs.modal2.closeModal()"
            ariaLabel="Submit Form"
            color="blue"
          >OK</md-button>
        </md-modal-footer>
      </md-modal>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ExampleModalLarge',

  data() {
    return {
      showModal: false,
      showModal2: false,
    }
  },
};
</script>

// react/src/lib/Modal/examples/Large.js
import React from 'react';
import {
  Button,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader
} from '@momentum-ui/react';
export default class ModalLarge extends React.PureComponent {
  state = {
    showModal5: false,
    showModal6: false,
  }
  render() {
    return (
      <div className='row'>
        <div className="docs-example docs-example--spacing">
          <Button
            children='Large Modal'
            onClick={() => this.setState({showModal5: true})}
            ariaLabel='Open Modal'
            color='primary'
            id='large-1'
          />
          <Button
            children='Large Modal with Message'
            onClick={() => this.setState({showModal6: true})}
            ariaLabel='Open Modal'
            color='primary'
            id='large-2'
          />
          <Modal
            applicationId='app'
            onHide={() => this.setState({showModal5: false})}
            show={this.state.showModal5}
            ref={modal5 => this.modal5 = modal5}
            htmlId='modal5'
            size='large'
          >
            <ModalHeader
              headerLabel='Large Modal'
              showCloseButton
            />
            <ModalBody>
              <form ref={form1 => this.form1 = form1} />
            </ModalBody>
            <ModalFooter>
              <Button
                children='Cancel'
                onClick={() => this.modal5.closeModal()}
                ariaLabel='Close Modal'
                color='default'
              />
              <Button
                children='OK'
                type='submit'
                onClick={(e) => {
                  e.preventDefault();
                  this.modal5.closeModal();
                }}
                ariaLabel='Submit Form'
                color='blue'
              />
            </ModalFooter>
          </Modal>
          <Modal
            applicationId='app'
            onHide={() => this.setState({showModal6: false})}
            show={this.state.showModal6}
            ref={modal6 => this.modal6 = modal6}
            htmlId='modal6'
            size='large'
          >
            <ModalHeader
              headerLabel='Large Modal'
              showCloseButton
              message='To create a meeting invite manually, copy and paste the meeting information and people into your email calendar invite. To create a meeting invite manually, copy and paste the meeting information and people into your email calendar invite.'
            />
            <ModalBody>
              <form ref={form1 => this.form1 = form1} />
            </ModalBody>
            <ModalFooter>
              <Button
                children='Cancel'
                onClick={() => this.modal6.closeModal()}
                ariaLabel='Close Modal'
                color='default'
              />
              <Button
                children='OK'
                type='submit'
                onClick={(e) => {
                  e.preventDefault();
                  this.modal6.closeModal();
                }}
                ariaLabel='Submit Form'
                color='blue'
              />
            </ModalFooter>
          </Modal>
        </div>
      </div>
    );
  }
}
