// react/src/lib/Tooltip/examples/Direction.js
import React from 'react';
import { Button, Tooltip } from '@collab-ui/react';

export default function TooltipDirection() {
  return (
    <div className="docs-example docs-example--spacing">
      <Tooltip
        tooltip="Hello!"
        tooltipTrigger="Click"
        popoverProps={{ direction: 'right-center' }}
      >
        <Button children="Direction" ariaLabel="Direction" />
      </Tooltip>
    </div>
  );
}

// vue/src/lib/tooltip/examples/direction.vue
<template>
  <div class="docs-example docs-example--spacing">
    <md-tooltip
      tooltip="Hello!"
      tooltipTrigger="MouseEnter"
      :popoverProps="{
        direction: 'right-center'
      }">
      <md-button ariaLabel="Direction">Direction</md-button>
    </md-tooltip>
  </div>
</template>

<script>
export default {
  name: 'ExampleTooltipDirection',
};
</script>
