// react/package/src/lib/AlertMeeting/examples/Multiple.js
/** @component alert-meeting */

import React from 'react';
import {
  Button,
  AlertMeeting,
  AlertContainer
} from '@momentum-ui/react';

export default class Default extends React.PureComponent {
  state = {
    show: false
  }

  handleOnHide = () => {
    this.setState({show: false});
  }
  
  handleOnSnooze = () => {
    this.setState({show: false});
  }

  render() {
    return (
      <section>
        <div>
          <div className='row'>
            <Button
              ariaLabel='Click to Open'
              onClick={() => this.setState({show: true})}
              children='Multiple Attendees'
              color='primary'
            />
          </div>
          <br />
          <AlertContainer>
            <AlertMeeting
              title='Important Meeting'
              status='In 5 mins.'
              message='This is important'
              onHide={this.handleOnHide}
              onSnooze={this.handleOnSnooze}
              attendees={[{title: 'J $'}, {title: 'Jefe Guadelupe'}]}
              show={this.state.show}
            />
          </AlertContainer>
        </div>
      </section>
    );
  }
}

// angular/src/lib/alert-meeting/examples/multiple.component.ts
import { Component } from '@angular/core';
import { AlertMeetingService } from '@momentum-ui/angular';

@Component({
  selector: 'example-alert-meeting-multiple',
  template: `
    <button md-button (click)="onClick()" aria-label="Click to Open">Multiple</button>
  `,
})
export class ExampleAlertMeetingMultipleComponent {
  constructor(private alertMeetingService: AlertMeetingService) {}

  onClick() {
    this.alertMeetingService.show({
      title: 'Important Meeting',
      message: 'This is important',
      status: 'In 5 mins.',
      attendees: [{title: 'J $'}, {title: 'Jefe Guadelupe'}],
      onClick: () => {},
      onHide: () => {},
      onSnooze: () => {},
    });
  }
}
