// react/src/app/containers/Playground/index.js
import React from 'react';
import SampleComponent from './insertExampleHere';

const Playground = () => {
  return (
    <div data-docs-overview="docs-overview">
      <article className="row copy-spacing">
        <h1>Playground</h1>
        <div className="docs-container">
          <SampleComponent />
        </div>
      </article>
    </div>
  );
};

export default Playground;

// angular/src/docs/app/playground/playground.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'docs-playground',
  template: `
    <div data-docs-overview="docs-overview">
      <article class="row copy-spacing">
        <h1>Playground</h1>
        <div class="docs-container">
          <!-- Insert Example Here -->
        </div>
      </article>
    </div>
  `,
})
export class PlaygroundComponent { }
