// vue/src/lib/button/examples/size.vue
<template>
  <div class="example-spacing">
    <md-button :ariaLabel="'For the Win'">no size</md-button>
    <md-button :ariaLabel="'For the Win'" :size="28">size 28</md-button>
    <md-button :ariaLabel="'For the Win'">size 36</md-button>
    <md-button :ariaLabel="'For the Win'" :size="40">size 40</md-button>
    <md-button :ariaLabel="'For the Win'" :size="52">size 52</md-button>
  </div>
</template>

<script>
export default {
  name: 'ExampleButtonSize',
};
</script>

// react/src/lib/Button/examples/Size.js
import React from 'react';
import { Button } from '@momentum-ui/react';
export default function ButtonSize() {
  return(
    <div className="example-spacing">
      <div>
        <Button
          ariaLabel='For the Win'
          size='none'
        >
          no size
        </Button>
      </div>
      <br />
      <div>
        <Button
          ariaLabel='For the Win'
          size={28}
        >
          size 28
        </Button>
      </div>
      <br />
      <div>
        <Button
          ariaLabel='For the Win'
        >
          size 36
        </Button>
      </div>
      <br />
      <div>
        <Button
          ariaLabel='For the Win'
          size={40}
        >
          size 40
        </Button>
      </div>
      <br />
      <div>
        <Button
          ariaLabel='For the Win'
          size={52}
        >
          size 52
        </Button>
      </div>
      <br />
    </div>
  );
}
