// angular/src/lib/form/form-section.component.ts
/** @component form */

import { Component, Input } from '@angular/core';

@Component({
  selector: 'md-form-section',
  template: `
    <md-form-info [title]="title" [description]="description"></md-form-info>
    <md-form-content><ng-content></ng-content></md-form-content>
  `,
  host: {
    'class': 'md-form__section',
  }
})

export class FormSectionComponent {
  /** @prop Optional FormSection description | '' */
  @Input() description: string = '';
  /** @prop Optional FormSection title | null */
  @Input() title: string;
}

// react/package/es/FormSection/index.js
/** @component form */
import React from 'react';
import PropTypes from 'prop-types';
import { FormInfo, FormContent } from "./..";

var FormSection = function FormSection(props) {
  var title = props.title,
      description = props.description,
      children = props.children;
  return React.createElement("div", {
    className: "md-form__section"
  }, React.createElement(FormInfo, {
    title: title,
    description: description
  }), React.createElement(FormContent, null, children));
};

FormSection.propTypes = {
  /** @prop Children node to render inside FormSection | null */
  children: PropTypes.node,

  /** @prop Optional FormSection description | '' */
  description: PropTypes.string,

  /** @prop Optional FormSection title | null */
  title: PropTypes.string.isRequired
};
FormSection.defaultProps = {
  children: null,
  description: '',
  title: null
};
FormSection.displayName = 'FormSection';
export default FormSection;
