// react/package/src/lib/FormContent/index.js
/** @component form */

import React from 'react';
import PropTypes from 'prop-types';

/**
 * FormContent helps organize the content within a form section and provides a S wrapper;
 **/

const FormContent = props => {
  const { children } = props;

  return <div className="section__content">{children}</div>;
};

FormContent.propTypes = {
  /** @prop Children node to render inside FormContent | null */
  children: PropTypes.node,
};

FormContent.deafultProps = {
  children: null,
};

FormContent.displayName = 'FormContent';

export default FormContent;

// angular/src/lib/form/form-content.component.ts
/** @component form */

import { Component, Input } from '@angular/core';

/**
 * FormContent helps organize the content within a form section and provides a S wrapper;
 **/

@Component({
  selector: 'md-form-content',
  template: `
    <ng-content></ng-content>
  `,
  host: {
    'class': 'section__content',
  }
})

export class FormContentComponent {}
