// vue/src/lib/slider/examples/cross.vue
<template>
  <div>
    <h5>Low: {{slider1.low}} High: {{slider1.high}}</h5>
    <md-slider
      canCross
      :min="0"
      :max="500"
      :tick="100"
      :value="slider1"
      :step="1"
      @change="val => slider1 = val"
    />
  </div>
</template>

<script>
export default {
  name: 'ExampleSliderCross',

  data() {
    return {
      slider1: { low: 100, high: 200 },
    };
  },
};
</script>

// angular/src/lib/slider/examples/cross.component.ts
import { Component } from '@angular/core';
import { SliderChange } from '@momentum-ui/angular/slider';

@Component({
  selector: 'example-slider-cross',
  template: `
    <div>
      {{ label }}
    </div>
    <md-slider
      [(ngModel)]="value"
      max="500"
      tick="100"
      [canCross]="true"
      (change)="change($event)"
    ></md-slider>
  `,
})
export class ExampleSliderCrossComponent {
  value: SliderChange = { high: 300, low: 100 };
  get label(): string {
    return `Low: ${this.value.low} High: ${this.value.high}`;
  }

  change(event: SliderChange) {
    console.info(event);
  }
}
