// vue/src/lib/date-picker/date-picker-day/index.vue
<template>
  <md-button
    circle
    :size="28"
    :disabled="disabled"
    class="md-datepicker__day"
    :class="{
      'md-datepicker__day--selected': isSelected,
      'md-datepicker__day--focus': hasFocus,
      'md-datepicker__day--today': isToday,
      'md-datepicker__day--outside-month': isOutsideMonth
    }"
    @click="handleClick"
    :ariaLabel="`${day.format('dddd, MMMM Do YYYY')}`"
    :aria-selected="isSelected"
    tabindex="-1"
  >
    <div :aria-label="day.format('dddd, MMMM Do YYYY')">
      {{ getDate(day) }}
    </div>
  </md-button>
</template>

<script>
import {
  getDate,
  getMonth,
  isDayDisabled,
  isSameDay,
  now,
} from '../../utils/dateUtils.js';
import moment from 'moment';

export default {
  name: 'md-date-picker-day',

  inject: {
    getFocus: {
      default: null
    },
    getSelected: {
      default: null
    },
    handleDayClick: {
      default: null
    },
  },

  props: {
    /** Required day that the DatePickerDay displays */
    day: {
      type: Object,
      required: true
    },
    /** @prop Function to filter Dates | null */
    filterDate: Function,
    /** Required month that the DatePickerDay displays */
    month: {
      type: Number,
      required: true
    },
  },

  computed: {
    isOutsideMonth() {
      return this.month !== getMonth(this.day);
    },
    isSelected() {
      return this.getSelected ? isSameDay(this.day, this.getSelected()) : false;
    },
    isToday() {
      return isSameDay(this.day, now());
    },
    disabled() {
      return isDayDisabled(this.day, this.$props);
    },
    hasFocus() {
      return this.getFocus ? isSameDay(this.day, this.getFocus()) : false;
    },
  },

  methods: {
    handleClick(e) {
      return (
        this.handleDayClick
        && this.handleDayClick(e, this.day)
      );
    },

    getDate(day) {
      return getDate(day);
    }
  },
};
</script>

// react/src/lib/DatePicker/DatePickerDay/index.js
import React from 'react';
import PropTypes from 'prop-types';
import { Button } from '@momentum-ui/react';
import DatePickerContext from '@momentum-ui/react/DatePickerContext';
import {
  getDate,
  getMonth,
  isDayDisabled,
  isSameDay,
  now,
} from '@momentum-ui/react/utils/dateUtils';
import mapContextToProps from 'react-context-toolbox/mapContextToProps';
import moment from 'moment';

class DatePickerDay extends React.Component {
  static displayName = 'DatePickerDay';

  handleClick = e => {
    const { handleDayClick, day } = this.props;
    return (
      handleDayClick
      && handleDayClick(e, day)
    );
  };

  render() {
    const { selected, focus, day, month } = this.props;

    const isOutsideMonth = month !== getMonth(day);
    const isSelected = isSameDay(day, selected);
    const isToday = isSameDay(day, now());
    const disabled = isDayDisabled(day, this.props);
    const hasFocus = isSameDay(day, focus);

    return (
      <Button
        circle
        size={28}
        disabled={disabled}
        className={
          'md-datepicker__day' +
          `${(isSelected && ` md-datepicker__day--selected`) || ''}` +
          `${(hasFocus && ` md-datepicker__day--focus`) || ''}` +
          `${(isToday && ` md-datepicker__day--today`) || ''}` +
          `${(isOutsideMonth && ` md-datepicker__day--outside-month`) || ''}`
        }
        onClick={this.handleClick}
        ariaLabel={`${day.format("dddd, MMMM Do YYYY")}`}
        aria-selected={isSelected}
        tabIndex={-1}
      >
        <div aria-label={day.format("dddd, MMMM Do YYYY")}>
          {getDate(day)}
        </div>
      </Button>
    );
  }
}

DatePickerDay.propTypes = {
  /** Required day that the DatePickerDay displays */
  day: PropTypes.instanceOf(moment).isRequired,
  // Internal Context Use Only
  focus: PropTypes.instanceOf(moment),
  // Internal Context Use Only
  handleDayClick: PropTypes.func,
  /** Required month that the DatePickerDay displays */
  month: PropTypes.number.isRequired,
  // Internal Context Use Only
  selected: PropTypes.instanceOf(moment),
};

export default mapContextToProps(
  DatePickerContext,
  context => context,
  DatePickerDay
);
