// angular/src/lib/alert-banner/examples/error.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-alert-banner-error',
  template: `
    <md-alert-banner
      *ngIf="show"
      type="error"
      (hide)="show = false"
      [closable]="true"
    >
      Error Alert Banner
    </md-alert-banner>
    <button md-button (click)="onClick()" aria-label="Error Alert Banner">
      Toggle Error Alert Banner
    </button>
  `,
})
export class ExampleAlertBannerErrorComponent {
  show: boolean = false;

  constructor() {}

  onClick() {
    this.show = !this.show;
  }
}

// vue/src/lib/alert-banner/examples/error.vue
<template>
  <div>
    <div>
      <md-alert-banner
        :show="showAlert1"
        closable
        @hide="() => showAlert1 = false"
        type="error"
      >
        Error Alert Banner
      </md-alert-banner>
    </div>
    <div>
      <div class='row'>
        <br />
        <md-button
          @click="() => showAlert1 = !showAlert1"
          ariaLabel="Error Alert Banner"
          class="btn--primary btn--large"
        >Toggle Error Alert Banner</md-button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ExampleAlertBannerError',

  data() {
    return {
      showAlert1: true,
    }
  },
};
</script>
