// react/src/lib/AlertBanner/examples/Warning.js
import React from 'react';
import { AlertBanner, Button } from '@momentum-ui/react';
export default class AlertBannerWarning extends React.PureComponent {
  state = {
    showAlert1: true
  }
  render() {
    return (
     <div>
       <div>
         <AlertBanner
           show={this.state.showAlert1}
           closable
           onHide={() => this.setState({showAlert1: false})}
           type='warning'
         >
           Warning Alert Banner
         </AlertBanner>
       </div>
       <div>
         <div className='row'>
           <br />
           <Button
             children='Toggle Warning Alert Banner'
             onClick={() => this.setState({showAlert1: !this.state.showAlert1})}
             ariaLabel='Warning Alert Banner'
             className='btn--primary btn--large'
           />
         </div>
       </div>
     </div>
    );
  }
}

// vue/src/lib/alert-banner/examples/warning.vue
<template>
  <div>
    <div>
      <md-alert-banner
        :show="showAlert1"
        closable
        @hide="() => showAlert1 = false"
        type="warning"
      >
        Warning Alert Banner
      </md-alert-banner>
    </div>
    <div>
      <div class='row'>
        <br />
        <md-button
          @click="() => showAlert1 = !showAlert1"
          ariaLabel="Warning Alert Banner"
          class="btn--primary btn--large"
        >Toggle Warning Alert Banner</md-button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ExampleAlertBannerWarning',

  data() {
    return {
      showAlert1: true,
    }
  },
};
</script>
