// react/src/lib/Loading/index.js
/** @component loading-spinner */

import React from 'react';
import PropTypes from 'prop-types';

const Loading = props => {
  const {
    small,
  } = props;

  return (
    <div className={`cui-loading ${small ? 'cui-loading--small' : ''}`}>
      <span className='cui-loading__icon'/>
      <span className='cui-loading__icon'/>
      <span className='cui-loading__icon'/>
    </div>
  );
};

Loading.propTypes = {
  /** @prop Prop to make the Loading animation small | false */
  small: PropTypes.bool,
};

Loading.defaultProps = {
  small: false,
};

Loading.displayName = 'Loading';

export default Loading;

/**
* @name Default Loading
* @description Loadings are useful.
*
* @category communication
* @component loader-spinner
* @section default
*
* @js
import { Loading } from '@collab-ui/react';

export default function LoaderSpinnerDefault() {
  return (
    <div className="row">
      <div className="docs-example docs-example--spacing" style={{fontSize: '1rem', display: 'flex'}}>
        <Loading />
      </div>
      <div className="docs-example docs-example--spacing" style={{fontSize: '2rem', display: 'flex'}}>
        <Loading />
      </div>
      <div className="docs-example docs-example--spacing" style={{fontSize: '3rem', display: 'flex'}}>
        <Loading />
      </div>
    </div>
  );
}

**/

// angular/src/lib/loading/loading.component.ts
import {
  Component,
  HostBinding,
  Input,
  ViewEncapsulation
} from '@angular/core';

@Component({
  selector: 'cui-loading, CSLoading',
  template: `
    <span class="cui-loading__icon"></span>
    <span class="cui-loading__icon"></span>
    <span class="cui-loading__icon"></span>
  `,
  styles: [],
  encapsulation: ViewEncapsulation.None,
})
export class LoadingComponent {
  /** @prop Prop to make the Loading animation small | false */
  @Input() private small: boolean = false;

  @HostBinding('class') get className(): string {
    return `cui-loading ${this.small ? 'cui-loading--small' : ''}`;
  }

  constructor() {}
}

 /**
 * @component loading
 * @section default
 * @angular
 *
<div className="row">
  <div className="docs-example docs-example--spacing" [style]="{fontSize: '1rem', display: 'flex'}">
    <cui-loading></cui-loading>
  </div>
  <div className="docs-example docs-example--spacing" [style]="{fontSize: '2rem', display: 'flex'}">
    <cui-loading></cui-loading>
  </div>
  <div className="docs-example docs-example--spacing" [style]="{fontSize: '3rem', display: 'flex'}">
    <cui-loading></cui-loading>
  </div>
</div>
 */
