// angular/src/docs/app/playground/playground.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'docs-playground',
  template: `
    <div data-docs-overview="docs-overview">
      <article class="row copy-spacing">
        <h1>Playground</h1>
        <div class="docs-container">
          <!-- Insert Example Here -->
        </div>
      </article>
    </div>
  `,
})
export class PlaygroundComponent { }

// angularjs/src/app/playground/playground.component.ts
class PlaygroundController {}

export class Playground implements angular.IComponentOptions {
  static selector = 'playground';
  static controller = PlaygroundController;
  static template = `
  <article className="row copy-spacing">
    <h1>AngularJS Playground</h1>
    <div className="docs-container">
      <!-- insert code here -->
    </div>
  </article>
  `;
}
