// angular/src/lib/input/examples/success.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-input-success',
  template: `
    <md-input
      [(ngModel)]="dataModel"
      inputSize="small-5"
      label="Success Label"
      [errorArr]="[{
        error: 'This is where the success message would be.',
        type: 'success'
      }]"
    >
    </md-input>
  `,
})
export class ExampleInputSuccessComponent {
  dataModel: string = 'success';
}

// react/src/lib/Input/examples/Success.js
import React from 'react';
import { Input } from '@collab-ui/react';
export default function InputSuccess() {
  return (
    <Input
      name='inputSuccess'
      label='Error (Success) Input'
      htmlId='inputSuccess'
      inputSize='small-5'
      errorArr={ [{error: 'This is where the success message would be.', type: 'success'}] }
    />
  );
}
