// angular/src/lib/input/examples/warning.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-input-warning',
  template: `
    <md-input
      [(ngModel)]="dataModel"
      inputSize="small-5"
      label="Warning Label"
      [errorArr]="[
        {
          error: 'This is where the success message would be.',
          type: 'warning'
        }
      ]"
    >
    </md-input>
  `,
})
export class ExampleInputWarningComponent {
  dataModel: string = 'Warning';
}

// react/src/lib/Input/examples/Warning.js
import React from 'react';
import { Input } from '@collab-ui/react';
export default function InputWarning() {
  return (
    <Input
      name='inputWarning'
      label='Error (Warning) Input'
      htmlId='inputWarning'
      inputSize='small-5'
      errorArr={ [{error: 'This is where the warning message would be.', type: 'warning'}] }
    />
  );
}
