// vue/src/lib/input/examples/warning.vue
<template>
  <md-input
    name="inputWarning"
    label="Error (Warning) Input"
    htmlId="inputWarning"
    inputSize="small-5"
    :errorArr="[
      {
        error: 'This is where the warning message would be.',
        type: 'warning',
      },
    ]"
  />
</template>

<script>
export default {
  name: 'ExampleInputWarning',
};
</script>

// react/src/lib/Input/examples/Warning.js
import React from 'react';
import { Input } from '@collab-ui/react';
export default function InputWarning() {
  return (
    <Input
      name='inputWarning'
      label='Error (Warning) Input'
      htmlId='inputWarning'
      inputSize='small-5'
      errorArr={ [{error: 'This is where the warning message would be.', type: 'warning'}] }
    />
  );
}
