// vue/src/lib/tooltip/index.vue
<template>
  <md-popover
    :className="`md-tooltip ${$attrs.class}`"
    :popoverTrigger="tooltipTrigger"
    v-bind="popoverProps"
    showArrow
  >
    <span
      slot="content"
      class="md-tooltip__text"
      :style="{ width: `${width}px` }"
      v-html="tooltip"
    ></span>
    <slot></slot>
  </md-popover>
</template>

<script>
export default {
  name: 'md-tooltip',

  props: {
    /** @prop Optional object for Popover Component props | {} */
    popoverProps: {
      type: Object,
      default: _ => { return {} }
    },
    /** @prop Tooltip text | '' */
    tooltip: {
      type: String,
      default: ''
    },
    /** @prop Set the action which triggers the Tooltip | 'MouseEnter' */
    tooltipTrigger: {
      type: String,
      default: 'MouseEnter',
      validator: value => ['MouseEnter', 'Click', 'Focus'].indexOf(value) !== -1
    },
    /** @prop Set the Tooltip width | null */
    width: Number
  }
};
</script>

// react/src/lib/Tooltip/index.js
/** @component tooltip */

import React from 'react';
import PropTypes from 'prop-types';
import { Popover } from '@collab-ui/react';

class Tooltip extends React.Component {

  render () {
    const {
      children,
      className,
      popoverProps,
      tooltip,
      tooltipTrigger,
      width,
      ...otherProps
    } = this.props;

    const content = (
      <span
        className='md-tooltip__text'
        {
          ...width
           && { style: { width: `${width}px` }}
        }
      >
        {tooltip}
      </span>
    );

    const clonedChildren = () => (
      React.cloneElement(children, {
        ...otherProps
      })
    );

    return (
      <Popover
        className={
          'md-tooltip' +
          `${(className && ` ${className}`) || ''}`
        }
        content={content}
        popoverTrigger={tooltipTrigger}
        showArrow
        {...popoverProps}
      >
        {clonedChildren()}
      </Popover>
    );
  }
}

Tooltip.propTypes = {
  /** @prop Children element to wrap Tooltip component around | null */
  children: PropTypes.element,
  /** @prop Optional CSS class string | '' */
  className: PropTypes.string,
   /** @prop Optional object for Popover Component props | {} */
  popoverProps: PropTypes.object,
  /** @prop Tooltip text | '' */
  tooltip: PropTypes.string,
  /** @prop Set the action which triggers the Tooltip | 'MouseEnter' */
  tooltipTrigger: PropTypes.oneOf(['MouseEnter', 'Click', 'Focus']),
  /** @prop Set the Tooltip width | null */
  width: PropTypes.number
};

Tooltip.defaultProps = {
  children: null,
  className: '',
  popoverProps: {},
  tooltip: '',
  tooltipTrigger: 'MouseEnter',
  width: null
};

Tooltip.displayName = 'Tooltip';

export default Tooltip;
