// vue/src/lib/input-search/index.vue
<template>
  <md-input class="md-search-input" v-bind="$attrs">
    <md-spinner v-if="isLoading" :size="20" slot="inputBefore" />
    <md-icon
      v-if="!isLoading"
      class="md-search-input__icon"
      name="search_20"
      slot="inputBefore"
    />
  </md-input>
</template>

<script>
export default {
  name: 'md-input-search',

  props: {
    /** @prop Determines if spinner is present | false */
    isLoading: Boolean
  }
};
</script>

// react/package/src/lib/InputSearch/index.js
/** @component input-search */

import React from 'react';
import PropTypes from 'prop-types';
import {
  Icon,
  Input,
  Spinner
} from '@momentum-ui/react';

const SearchInput = props => {
  const {
    isLoading,
    ...otherProps
  } = props;

  return (
    <Input
      inputBefore={
        isLoading
          ? <Spinner size={20} />
          : <Icon name='search_20'/>
      }
      {...otherProps}
    />
  );
};

SearchInput.propTypes = {
  /** @prop Determines if spinner is present | false */
  isLoading: PropTypes.bool
};

SearchInput.defaultProps = {
  isLoading: false
};

SearchInput.displayName = 'SearchInput';

export default SearchInput;
