// vue/src/lib/input/examples/clear.vue
<template>
  <md-input
    name="clearInput"
    label="Input with clear"
    htmlId="clearInput"
    inputSize="small-5"
    placeholder="Placeholder Text"
    :value="value"
    @change="handleChange"
    :clear="true"
  />
</template>

<script>
export default {
  name: 'ExampleInputClear',

  data() {
    return {
      value: 'Press or click the clear icon to clear this input'
    }
  },

  methods: {
    handleChange(e){
      this.value = e.target.value;
    },
  },
};
</script>

// react/examples/Input/clear.js
import React from 'react';
import { Input } from '@collab-ui/react';
export default class Clear extends React.PureComponent {
  state = {
    value: 'Press or click the clear icon to clear this input'
  };
  handleChange = (event) => {
    this.setState({value: event.target.value});
  }
  render() {
    return (
      <div className='row'>
      <Input
        name='clearInput'
        label='Input with clear'
        htmlId='clearInput'
        inputSize='small-5'
        placeholder='Placeholder Text'
        value={this.state.value}
        onChange={this.handleChange}
        clear
      />
    </div>
    );
  }
}
