// angular/src/lib/input/examples/disabled.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-input-disabled',
  template: `
    <md-input-group
      label="Disabled Input"
      inputSize="small-5"
    >
      <input
        mdInput
        disabled
        value='Disabled'
      />
    </md-input-group>
  `,
})

export class ExampleInputDisabledComponent {}

// react/examples/Input/disabled.js
import React from 'react';
import { Input } from '@collab-ui/react';
export default function InputDisabled() {
  return (
    <div className='row'>
      <Input
        name='inputDisabled'
        label='Disabled Input'
        htmlId='inputDisabled'
        inputSize='small-5'
        value='Disabled Text'
        disabled
      />
    </div>
  );
}
