// vue/src/lib/input/examples/help-text.vue
<template>
  <md-input
    name="inputHelpText"
    label="Help Text Input"
    htmlId="inputHelpText"
    containerSize="medium-6"
    helpText="This is help text for the input."
    placeholder="With Placeholder"
  />
</template>

<script>
export default {
  name: 'ExampleInputHelpText',
};
</script>

// react/examples/Input/helptext.js
import React from 'react';
import { Input } from '@collab-ui/react';
export default function InputHelp() {
  return (
    <div className='row'>
      <Input
        name='inputHelpText'
        label='Help Text Input'
        htmlId='inputHelpText'
        inputSize='small-5'
        inputHelpText='Help Text'
      />
    </div>
  );
}
