// angular/src/lib/input/examples/readonly-component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-input-readonly',
  template: `
    <md-input-container
      inputSize="small-5"
      label="Read Only Input"
    >
      <input
        mdInput
        readonly
        value='Read Only Text'
      />
    </md-input-container>
  `,
})

export class ExampleInputReadOnlyComponent {}

// react/examples/Input/readonly.js
import React from 'react';
import { Input } from '@collab-ui/react';
export default function InputReadonly() {
  return (
    <div className='row'>
      <Input
        name='inputReadonly'
        label='Read Only Input'
        htmlId='inputReadonly'
        inputSize='small-5'
        value='Read Only Text'
        readOnly
      />
    </div>
  );
}
