// angular/src/lib/tabs/tab-header.component.ts
/** @component tab */

import { Component, Input } from '@angular/core';

@Component({
  selector: 'md-tab-header',
  template: `
    {{ heading }}
    <div *ngIf="subHeading">{{ subHeading }}</div>
  `,
  styles: [],
})
export class TabHeaderComponent {
  /** @prop TabHeader text */
  @Input() public heading: string;
  /** @prop Subheader text | '' */
  @Input() public subHeading: string = '';
}

// react/package/es/TabHeader/index.js
/** @component tabs */
import React from 'react';
import PropTypes from 'prop-types';

var TabHeader = function TabHeader(props) {
  var heading = props.heading,
      subHeading = props.subHeading;
  return (//Element type required by Momentum UI Style
    React.createElement("md-tab-heading", null, heading, subHeading && React.createElement("div", null, subHeading))
  );
};

TabHeader.propTypes = {
  /** @prop TabHeader text */
  heading: PropTypes.string.isRequired,

  /** @prop Subheader text | '' */
  subHeading: PropTypes.string
};
TabHeader.defaultProps = {
  subHeading: ''
};
TabHeader.displayName = 'TabHeader';
export default TabHeader;
