// vue/src/lib/list-separator/index.vue
<template>
  <div
    class="md-list-separator"
    :style="[
      lineColor && {color: lineColor},
      margin && {margin: margin}
    ]"
  >
    <span class="md-list-separator__container">
      <span v-if="$slots.default || text"
        class="md-list-separator__text"
        :style="[
          textColor && {color: textColor},
          textPadding && {padding: textPadding}
        ]"
      >
        <slot></slot>{{ content }}
      </span>
    </span>
  </div>
</template>

<script>
export default {
  name: 'md-list-separator',

  props: {
    /** @prop Color of the ListSeparator line | null */
    lineColor: String,
    /** @prop Margin of the ListSeparator | null */
    margin: String,
    /** @prop Text of the ListSeparator | null */
    text: String,
    /** @prop TextColor of the ListSeparator | null */
    textColor: String,
    /** @prop Padding around text of the ListSeparator | null */
    textPadding: String,
  },

  computed: {
    content() {
      return !this.$slots.default ? this.text : '';
    }
  },
};
</script>

// angular/src/lib/list-separator/list-separator.component.ts
import { Component, HostBinding, Input } from '@angular/core';

@Component({
  selector: 'cui-list-separator',
  template: `
    <span class="cui-list-separator__container">
      <ng-content *ngIf="!text; else textTemplate"></ng-content>
    </span>

    <ng-template #textTemplate>
      <span
        class="cui-list-separator__text"
        [ngStyle]="{color: textColor, padding: textPadding}"
      >{{text}}</span>
    </ng-template>
  `,
  host: {
    'class': 'cui-list-separator'
  },
})
export class ListSeparatorComponent {
  /** @prop Background Color of the ListSeparator | null */
  @Input() backgroundColor: string;
  /** @prop Color of the ListSeparator line | null */
  @Input() lineColor: string;
  /** @prop Margin of the ListSeparator | null */
  @Input() margin: string;
  /** @prop Text of the ListSeparator | null */
  @Input() text: string;
  /** @prop TextColor of the ListSeparator | null */
  @Input() textColor: string;
  /** @prop Padding around text of the ListSeparator | null */
  @Input() textPadding: string;

  @HostBinding('style.background-color') get _backgroundColor(): string {
    return this.backgroundColor;
  }
  @HostBinding('style.color') get _lineColor(): string {
    return this.lineColor;
  }
  @HostBinding('style.margin') get _margin(): string {
    return this.margin;
  }
}
