// react/package/src/lib/Checkbox/examples/Indeterminate.js
import React from 'react';
import { Checkbox } from '@momentum-ui/react';
export default function CheckboxIndeterminate() {
  return (
    <Checkbox
      value='indeterminate'
      label='Indeterminate Checkbox'
      htmlId='indeterminateCheckbox'
      onChange={()=>{}}
      indeterminate
    />
  );
}

// angular/src/lib/checkbox/examples/indeterminate.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-checkbox-indeterminate',
  template: `
    <md-checkbox
      name="TDG"
      value="val5"
      label="Indeterminate Checkbox"
      [(ngModel)]="checkedValues"
      [indeterminate]="true"
      htmlId="val5"
    >
    </md-checkbox>
  `,
})
export class ExampleCheckboxIndeterminateComponent {
  checkedValues: string[] = [];
}
