// vue/src/lib/label/index.vue
<script>
export default {
  name: 'md-label',

  render: function (h) {
    const {
      htmlFor,
      label,
      theme,
      ...props
    } = this.$props;

    return (
      <label
        class={`${theme ? ` md-label--${theme}` : ''}`}
        for={htmlFor}
        {...props}
      >
        {
          label
          ? <span>{label}</span>
          : this.$slots.default
        }
      </label>
    )
  },

  props: {
    /** @prop HTML ID for associated Input | null */
    htmlFor: {
      type: String,
      required: true
    },
    /** @prop Required Label text | null */
    label: String,
    /** @prop Set Label's color theme | '' */
    theme: {
      type: String,
      default: ''
    },
  }
};
</script>

// react/package/src/lib/Label/index.js
/** @component label */

import React from 'react';
import PropTypes from 'prop-types';

const Label = ({
  children,
  className,
  htmlFor,
  label,
  theme,
  ...props
}) => {
  return (
    <label
      className={
        'md-label' +
        `${className ? ` ${className}` : ''}` +
        `${theme ? ` md-label--${theme}` : ''}`
      }
      htmlFor={htmlFor}
      {...props}
    >
      {
        label 
        ? <span>{label}</span>
        : children
      }
    </label>
  );
};

Label.propTypes = {
  /** @prop Children nodes to render inside the Label | null */
  children: PropTypes.node,
  /** @prop HTML class name for associated Input | '' */
  className: PropTypes.string,
  /** @prop HTML ID for associated Input | null */
  htmlFor: PropTypes.string.isRequired,
  /** @prop Required Label text | null */
  label: PropTypes.string,
  /** @prop Set Label's color theme | '' */
  theme: PropTypes.string,
};

Label.defaultProps = {
  children: null,
  className: '',
  htmlFor: null,
  label: null,
  theme: '',
};

Label.displayName = 'Label';

export default Label;
