// vue/src/lib/tooltip/examples/delay.vue
<template>
  <div class="docs-example docs-example--spacing">
    <md-tooltip
      tooltip="Delayed!"
      tooltipTrigger="MouseEnter"
      :popoverProps="{
        delay: 500
      }">
      <md-button ariaLabel="Delay">Delay</md-button>
    </md-tooltip>
  </div>
</template>

<script>
export default {
  name: 'ExampleTooltipDelay',
};
</script>

// react/package/src/lib/Tooltip/examples/Delay.js
import React from 'react';
import { Button, Tooltip } from '@momentum-ui/react';

export default function TooltipDelay() {
  return (
    <div className="row">
      <div className="docs-example docs-example--spacing">
        <Tooltip
          tooltip="Delayed!"
          tooltipTrigger="Click"
          popoverProps={{ delay: 500 }}
        >
          <Button id='delay' children="Delay" ariaLabel="Delay" />
        </Tooltip>
      </div>
    </div>
  );
}
