// vue/src/lib/slider/examples/cross.vue
<template>
  <div>
    <h5>Low: {{slider1.low}} High: {{slider1.high}}</h5>
    <md-slider
      canCross
      :min="0"
      :max="500"
      :tick="100"
      :value="slider1"
      :step="1"
      @change="val => slider1 = val"
    />
  </div>
</template>

<script>
export default {
  name: 'ExampleSliderCross',

  data() {
    return {
      slider1: { low: 100, high: 200 },
    };
  },
};
</script>

// react/package/src/lib/Slider/examples/Cross.js
import React from 'react';
import { Slider } from '@momentum-ui/react';
export default class SliderCross extends React.Component {
  state = {
    slider1: {low: 100, high: 200},
  }
  render() {
    return (
      <div>
        <h5>
          Low: {this.state.slider1.low} High: {this.state.slider1.high}
        </h5>
        <Slider
          min={0}
          max={500}
          tick={100}
          value={this.state.slider1}
          step={1}
          canCross
          onChange={value => this.setState({ slider1: value })}
        />
      </div>
    );
  }
}
