// vue/src/lib/input-error/index.vue
<template>
  <div class="md-input__messages" role="alert">
    <div class="message">{{ error }}</div>
  </div>
</template>

<script>
export default {
  name: 'md-input-error',

  props: {
    /** @prop Error message for InputError component */
    error: {
      type: String,
      required: true
    }
  }
};
</script>

// angular/src/lib/input-error/input-error.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'md-input-error',
  template: `
    <div class="md-input__messages" role="alert">
      <div class="message">{{ error }}</div>
    </div>
  `,
  styles: [],
})
export class InputErrorComponent implements OnInit {
  @Input() public error: string;

  constructor() {}

  ngOnInit() {}
}
