// vue/src/lib/popover/index.vue
<script>
import cloneElement from '../utils/cloneElement';
import assign from 'lodash/assign';
import omit from 'lodash/omit';
import { Fragment } from 'vue-fragment'

export default {
  name: 'md-popover',

  components: { Fragment },

  data() {
    return {
      isOpen: false,
      isHovering: false,
      nativeOn: null,
    }
  },

  render(h) {
    const isOpen = this.isOpen;
    const {
      className,
      overflowType,
      popoverTrigger,
      showArrow,
      ...props
    } = this.$props;

    const otherProps = omit({...props}, [
      'delay',
      'doesAnchorToggle',
      'hideDelay',
      'hoverDelay',
      'showDelay',
      'startOpen',
    ]);

    const getTriggers = () => {
      const triggerProps = {
        attrs: {
          ref: 'anchorRef',
          key: 'child-1',
        },
        nativeOn: {},
      };

      switch (popoverTrigger) {
        case 'MouseEnter':
          triggerProps.nativeOn.mouseenter = this.handleMouseEnter;
          triggerProps.nativeOn.mouseleave = this.handleMouseLeave;

          triggerProps.nativeOn.focus = this.handleFocus;
          triggerProps.nativeOn.blur = this.handleBlur;
          break;

        case 'Click':
          triggerProps.nativeOn.click = this.handleClick;
          break;

        case 'Focus':
          triggerProps.nativeOn.focus = this.handleFocus;
          triggerProps.nativeOn.blur = this.handleBlur;
          break;
      }

      return triggerProps;
    };

    const node = this.$slots.default && this.$slots.default[0];

    if (!this.nativeOn) {
      this.nativeOn = {};
      node.data && node.data.nativeOn && assign(this.nativeOn, node.data.nativeOn);
    }

    const data = getTriggers();
    if (node && node.data) {
      node.data.on = {};
      node.data.nativeOn = {};
      assign(node.data.attrs, data.attrs);
      assign(node.data.on, data.nativeOn);
      assign(node.data.nativeOn, data.nativeOn);
    }

    const getComponentData = () => ({
      class: className,
      attrs: {
        ref: 'overlay',
        ...this.$attrs,
      },
      props: {
        anchorNode: node.elm,
        isOpen: isOpen,
        showArrow: showArrow,
        contentStyle: { overflow: overflowType },
        ...popoverTrigger === 'Focus' && { allowClickAway: false },
        ...otherProps,
        ...this.$attrs,
      },
      on: {
        close: this.handleClose,
      },
      nativeOn: {
        ...popoverTrigger === 'MouseEnter' && {
          mouseenter: e => {
              this.isHovering = true;
              this.isOpen = true;
            },
          mouseleave: e => {
              this.isHovering = false;
              this.delayedHide(e);
            },
        },
      },
    });

    return (
      h(this.fragment ? 'fragment' : 'span',
        {},
        [node, isOpen &&
          h('md-event-overlay', getComponentData(), this.$slots.content)]
      )
    );
  },

  props: {
    /** @prop Optional CSS class names which goes over popover container | '' */
    className: String,
    /** @prop The delay for popover on hover, click, focus (hide/show) | 0 */
    delay: {
      type: [Number, String],
      default: 0
    },
    /** @prop Boolean for whether the Anchor Toggles the Popover | true */
    doesAnchorToggle: {
      type: Boolean,
      default: true
    },
    /** @prop Use fragment tag | true */
    fragment: {
      type: Boolean,
      default: true
    },
    /** @prop The hide delay for popover on hover, click, focus | 0 */
    hideDelay: {
      type: [Number, String],
      default: 0
    },
    /** @prop The hover delay for checking whether we are still hovering before closing | 500 */
    hoverDelay: {
      type: [Number, String],
      default: 500
    },
    /** @prop Optional prop that controls overflow css style of EventOverlay | 'auto' */
    overflowType: {
      type: String,
      default: 'auto'
    },
    /** @prop Event that will trigger popover appearance | 'MouseEnter' */
    popoverTrigger: {
      type: String,
      default: 'MouseEnter',
      validator: (value) => ['MouseEnter', 'Click', 'Focus', 'None'].indexOf(value) !== -1
    },
    /** @prop Boolean for whether the Arrow should show | true */
    showArrow: {
      type: Boolean,
      default: true
    },
    /** @prop The show delay for popover on hover, click, focus | 0 */
    showDelay: {
      type: [Number, String],
      default: 0
    },
    /** @prop Should Popover start open | false */
    startOpen: Boolean,
  },

  methods: {
    delayedHide(e) {
      const { delay, hideDelay } = this.$props;
      if ( this.isHovering ) return;

      if (this.showTimerId) {
        clearTimeout(this.showTimerId);
        this.showTimerId = null;
      }

      const popoverHideTime = hideDelay
        ? hideDelay
        : delay;

      this.hideTimerId = setTimeout(() => {
        this.hideTimerId = null;
        this.isOpen = false;
        this.isHovering = false;
        this.$emit('close', e);
      }, popoverHideTime);

      e && e.stopPropagation();
    },

    delayedShow(e) {
      const { delay, showDelay } = this.$props;

      if (this.hideTimerId) {
        clearTimeout(this.hideTimerId);
        this.hideTimerId = null;
      }

      const popoverShowTime = showDelay
        ? showDelay
        : delay;

      this.showTimerId = setTimeout(() => {
        this.showTimerId = null;
        this.isOpen = true;
        this.isHovering = true;
      }, popoverShowTime);

      e && e.stopPropagation();
    },

    handleClose(e) {
      this.isOpen = false;
      this.$emit('close', e);
    },

    handleMouseEnter(e) {
      this.nativeOn && this.nativeOn.mouseenter && this.nativeOn.mouseenter(e);
      return !this.showTimerId && !this.isOpen && this.delayedShow(e);
    },

    delayCheckHover(e) {
      const { hoverDelay } = this.$props;
      this.isHovering = false;
      setTimeout(() => this.delayedHide(e), hoverDelay);
    },

    handleMouseLeave(e) {
      if (this.hasFocus) {
        return false;
      }

      if (this.showTimerId) {
        clearTimeout(this.showTimerId);
        this.showTimerId = null;
      }

      this.nativeOn && this.nativeOn.mouseleave && this.nativeOn.mouseleave(e);
      return !this.hideTimerId && this.isOpen && this.delayCheckHover(e);
    },

    handleBlur(e) {
      this.hasFocus = false;

      this.nativeOn && this.nativeOn.blur && this.nativeOn.blur(e);
      this.handleMouseLeave(e);
    },

    handleClick(e) {
      const { doesAnchorToggle } = this.$props;

      this.hasFocus = true;

      this.nativeOn && this.nativeOn.click && this.nativeOn.click(e);
      if(!this.showTimerId) {
        return !this.isOpen
          ? this.delayedShow(e)
          : doesAnchorToggle && this.handleBlur(e);
      }
    },

    handleFocus(e) {
      this.hasFocus = true;

      this.nativeOn && this.nativeOn.focus && this.nativeOn.focus(e);
      if(!this.showTimerId) {
        return !this.isOpen
          ? this.delayedShow(e)
          : this.handleBlur(e);
      }
    },
  },

  mounted() {
    this.startOpen &&
    this.delayedShow();
  },

  beforeDestroy() {
    this.hideTimerId && clearTimeout(this.hideTimerId);
    this.showTimerId && clearTimeout(this.showTimerId);
  },
};
</script>

// react/package/es/Popover/index.js
function _extends() { _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }

function _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; }

function _inheritsLoose(subClass, superClass) { subClass.prototype = Object.create(superClass.prototype); subClass.prototype.constructor = subClass; subClass.__proto__ = superClass; }

/** @component popover */
import React from 'react';
import PropTypes from 'prop-types';
import { EventOverlay } from "./..";
import omit from 'lodash/omit';

var Popover = /*#__PURE__*/function (_React$Component) {
  _inheritsLoose(Popover, _React$Component);

  function Popover() {
    var _this;

    for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    _this = _React$Component.call.apply(_React$Component, [this].concat(args)) || this;
    _this.state = {
      isOpen: _this.props.startOpen || false,
      isHovering: _this.props.startOpen || false
    };

    _this.delayedHide = function (e) {
      var _this$props = _this.props,
          delay = _this$props.delay,
          hideDelay = _this$props.hideDelay,
          onClose = _this$props.onClose;
      var isHovering = _this.state.isHovering;
      if (isHovering) return;

      if (_this.showTimerId) {
        clearTimeout(_this.showTimerId);
        _this.showTimerId = null;
      }

      var popoverHideTime = hideDelay ? hideDelay : delay;
      _this.hideTimerId = setTimeout(function () {
        _this.hideTimerId = null;

        _this.setState(function () {
          return {
            isOpen: false,
            isHovering: false
          };
        }, onClose && onClose(e));
      }, popoverHideTime);
      e && e.stopPropagation();
    };

    _this.delayedShow = function (e) {
      var _this$props2 = _this.props,
          delay = _this$props2.delay,
          showDelay = _this$props2.showDelay;

      if (_this.hideTimerId) {
        clearTimeout(_this.hideTimerId);
        _this.hideTimerId = null;
      }

      var popoverShowTime = showDelay ? showDelay : delay;
      _this.showTimerId = setTimeout(function () {
        _this.showTimerId = null;

        _this.setState(function () {
          return {
            isOpen: true,
            isHovering: true
          };
        });
      }, popoverShowTime);
      e && e.stopPropagation();
    };

    _this.handleClose = function (e) {
      var onClose = _this.props.onClose;

      _this.setState({
        isOpen: false
      }, onClose && onClose(e));
    };

    _this.handleMouseEnter = function (e) {
      var children = _this.props.children;
      children.props.onMouseEnter && children.props.onMouseEnter(e);
      return !_this.showTimerId && !_this.state.isOpen && _this.delayedShow(e);
    };

    _this.delayCheckHover = function (e) {
      var _this$props3 = _this.props,
          hoverDelay = _this$props3.hoverDelay,
          popoverTrigger = _this$props3.popoverTrigger;
      var delay = popoverTrigger === 'MouseEnter' ? hoverDelay : 0;
      e.persist();

      _this.setState({
        isHovering: false
      }, function () {
        return setTimeout(function () {
          return _this.delayedHide(e);
        }, delay);
      });
    };

    _this.handleMouseLeave = function (e) {
      var children = _this.props.children;

      if (_this.hasFocus) {
        return false;
      }

      if (_this.showTimerId) {
        clearTimeout(_this.showTimerId);
        _this.showTimerId = null;
      }

      children.props.onMouseLeave && children.props.onMouseLeave(e);
      return !_this.hideTimerId && _this.state.isOpen && _this.delayCheckHover(e);
    };

    _this.handleBlur = function (e) {
      var children = _this.props.children;
      _this.hasFocus = false;
      children.props.onBlur && children.props.onBlur(e);

      _this.handleMouseLeave(e);
    };

    _this.handleClick = function (e) {
      var _this$props4 = _this.props,
          children = _this$props4.children,
          doesAnchorToggle = _this$props4.doesAnchorToggle;
      var isOpen = _this.state.isOpen;
      _this.hasFocus = true;
      children.props.onClick && children.props.onClick(e);

      if (!_this.showTimerId) {
        return !isOpen ? _this.delayedShow(e) : doesAnchorToggle && _this.handleBlur(e);
      }
    };

    _this.handleFocus = function (e) {
      var children = _this.props.children;
      var isOpen = _this.state.isOpen;
      _this.hasFocus = true;
      children.props.onFocus && children.props.onFocus(e);

      if (!_this.showTimerId) {
        return !isOpen ? _this.delayedShow(e) : _this.handleBlur(e);
      }
    };

    return _this;
  }

  var _proto = Popover.prototype;

  _proto.componentDidMount = function componentDidMount() {
    this.props.startOpen && this.forceUpdate();
  };

  _proto.componentWillUnmount = function componentWillUnmount() {
    this.hideTimerId && clearTimeout(this.hideTimerId);
    this.showTimerId && clearTimeout(this.showTimerId);
  };

  _proto.render = function render() {
    var _this2 = this;

    var isOpen = this.state.isOpen;

    var _this$props5 = this.props,
        children = _this$props5.children,
        className = _this$props5.className,
        content = _this$props5.content,
        includeFocusOnHover = _this$props5.includeFocusOnHover,
        overflowType = _this$props5.overflowType,
        popoverTrigger = _this$props5.popoverTrigger,
        showArrow = _this$props5.showArrow,
        props = _objectWithoutPropertiesLoose(_this$props5, ["children", "className", "content", "includeFocusOnHover", "overflowType", "popoverTrigger", "showArrow"]);

    var otherProps = omit(_extends({}, props), ['delay', 'doesAnchorToggle', 'hideDelay', 'hoverDelay', 'onClose', 'showDelay', 'startOpen']);

    var getTriggers = function getTriggers() {
      var triggerProps = {};

      triggerProps.ref = function (ele) {
        return _this2.anchorRef = ele;
      };

      triggerProps.key = 'child-1';

      switch (popoverTrigger) {
        case 'MouseEnter':
          triggerProps.onMouseEnter = _this2.handleMouseEnter;
          triggerProps.onMouseLeave = _this2.handleMouseLeave;
          triggerProps.onFocus = includeFocusOnHover && _this2.handleFocus;
          triggerProps.onBlur = includeFocusOnHover && _this2.handleBlur;
          break;

        case 'Click':
          triggerProps.onClick = _this2.handleClick;
          triggerProps.onBlur = null;
          triggerProps.onFocus = null;
          triggerProps.onMouseEnter = null;
          triggerProps.onMouseLeave = null;
          break;

        case 'Focus':
          triggerProps.onFocus = _this2.handleFocus;
          triggerProps.onBlur = _this2.handleBlur;
          triggerProps.onMouseEnter = null;
          triggerProps.onMouseLeave = null;
          break;

        case 'None':
          triggerProps.onClick = null;
          triggerProps.onFocus = null;
          triggerProps.onBlur = null;
          triggerProps.onMouseEnter = null;
          triggerProps.onMouseLeave = null;
          break;
      }

      return triggerProps;
    };

    var anchorWithTriggers = function anchorWithTriggers() {
      return children && React.cloneElement(children, getTriggers());
    };

    return React.createElement(React.Fragment, null, anchorWithTriggers(), isOpen && React.createElement(EventOverlay, _extends({
      anchorNode: this.anchorRef,
      className: className,
      close: this.handleClose,
      isOpen: isOpen,
      ref: function ref(_ref) {
        return _this2.overlay = _ref;
      },
      showArrow: showArrow,
      style: {
        overflow: overflowType
      }
    }, popoverTrigger === 'MouseEnter' && {
      onMouseEnter: function onMouseEnter() {
        _this2.setState({
          isHovering: true,
          isOpen: true
        });
      },
      onMouseLeave: function onMouseLeave(e) {
        e.persist();

        _this2.setState({
          isHovering: false
        }, function () {
          return _this2.delayedHide(e);
        });
      }
    }, popoverTrigger === 'Focus' && {
      allowClickAway: false
    }, otherProps), content));
  };

  return Popover;
}(React.Component);

Popover.propTypes = {
  /** @prop Children node that should be the popover trigger(this should be a stateful component) */
  children: PropTypes.element.isRequired,

  /** @prop Optional CSS class names which goes over popover container | '' */
  className: PropTypes.string,

  /** @prop The content that goes into the popover */
  content: PropTypes.oneOfType([PropTypes.element, PropTypes.node]).isRequired,

  /** @prop The delay for popover on hover, click, focus (hide/show) | 0 */
  delay: PropTypes.number,

  /** @prop Boolean for whether the Anchor Toggles the Popover | true */
  doesAnchorToggle: PropTypes.bool,

  /** @prop The hide delay for popover on hover, click, focus | 0 */
  hideDelay: PropTypes.number,

  /** @prop The hover delay for checking whether we are still hovering before closing | 500 */
  hoverDelay: PropTypes.number,

  /** @prop Optional prop that determines whether Focus triggers apply to MouseEnter | true */
  includeFocusOnHover: PropTypes.bool,

  /** @prop Callback function that will execute on close | null */
  onClose: PropTypes.func,

  /** @prop Optional prop that controls overflow css style of EventOverlay | 'auto' */
  overflowType: PropTypes.string,

  /** @prop Event that will trigger popover appearance | 'MouseEnter' */
  popoverTrigger: PropTypes.oneOf(['MouseEnter', 'Click', 'Focus', 'None']),

  /** @prop Boolean for whether the Arrow should show | true */
  showArrow: PropTypes.bool,

  /** @prop The show delay for popover on hover, click, focus | 0 */
  showDelay: PropTypes.number,

  /** @prop Should Popover start open | false */
  startOpen: PropTypes.bool
};
Popover.defaultProps = {
  className: '',
  delay: 0,
  doesAnchorToggle: true,
  hideDelay: 0,
  hoverDelay: 500,
  includeFocusOnHover: true,
  onClose: null,
  overflowType: 'auto',
  popoverTrigger: 'MouseEnter',
  showArrow: true,
  showDelay: 0,
  startOpen: false
};
Popover.displayName = 'Popover';
export default Popover;
