// react/src/lib/SelectOption/index.js
/** @component select-option */

import React from 'react';
import ReactDOM from 'react-dom';
import PropTypes from 'prop-types';
import {
  Checkbox,
  Icon,
  ListItem,
  ListItemSection,
} from '@collab-ui/react';
import SelectContext from '../SelectContext';
import ListContext from '../ListContext';
import { UIDConsumer } from 'react-uid';

class SelectOption extends React.Component {
  render() {
    const {
      className,
      active,
      children,
      label,
      title,
      ...props
    } = this.props;

    const separateChildren = (isMulti, cxtActive, uniqueId) => {
      return (
        isMulti
      ? (
        <Checkbox
          htmlId={`${uniqueId}__checkbox`}
          label={label}
          checked={cxtActive || false}
          onChange={() => {}}
        />
      ) : (
        [
          <ListItemSection key='child-0' position='center'>
            {label || children}
          </ListItemSection>,
          <ListItemSection key='child-1' position='right'>
            {cxtActive && <Icon color='blue-50' name='check_20'/>}
          </ListItemSection>
        ]
       ) );
    };

    return (
      <UIDConsumer name={id => `md-select-option-${id}`}>
        {id => (
          <SelectContext.Consumer>
            {isMulti => (
              <ListContext.Consumer>
                {listContext => {
                  const cxtActive = active
                    || listContext
                    && listContext.active
                    && ReactDOM.findDOMNode(this)
                    && ReactDOM.findDOMNode(this).attributes['data-md-event-key']
                    && ReactDOM.findDOMNode(this).attributes['data-md-event-key'].value
                    && listContext.active.includes(
                      ReactDOM.findDOMNode(this)
                        .attributes['data-md-event-key']
                        .value
                    );

                  const uniqueId = this.props.id || id;

                  return (
                    <ListItem
                      className={`${(className && ` ${className}`) || ''}`}
                      id={uniqueId}
                      label={label}
                      title={title || label}
                      {...props}
                    >
                      {separateChildren(isMulti, cxtActive, uniqueId)}
                    </ListItem>
                  );
                }}
              </ListContext.Consumer>
            )}
          </SelectContext.Consumer>
        )}
      </UIDConsumer>
    );
  }
}

SelectOption.propTypes = {
  /** @prop SelectOption Boolean that describes active state | false */
  active: PropTypes.bool,
  /** @prop Children nodes to render inside SelectOption | null */
  children: PropTypes.node,
  /** @prop Optional HTML Class Name for ListItem | '' */
  className: PropTypes.string,
  /** @prop SelectOption ID | '' */
  id: PropTypes.string,
  /** @prop SelectOption label text | '' */
  label: PropTypes.string,
  /** @prop ListItem Title | '' */
  title: PropTypes.string,
  /** @prop SelectOption value | '' */
  value: PropTypes.string,
};

SelectOption.defaultProps = {
  active: false,
  children: null,
  className: '',
  id: '',
  label: '',
  title: '',
  value:'',
};

SelectOption.displayName = 'SelectOption';

export default SelectOption;

// vue/src/lib/select-option/index.vue
<template>
  <md-list-item
    :id="uniqueId"
    :label="label"
    :title="title || label"
    :value="value"
    @click="handleClick"
    v-bind="$attrs"
  >
    <md-checkbox
      v-if="isMulti && !$slots.customAnchor"
      :htmlId="`${uniqueId}__checkbox`"
      :label="label"
      :checked="cxtActive || false"
      ref="checkbox"
    />
    <md-list-item-section v-if="!isMulti && !$slots.customAnchor" key="child-0" position="center">
      {{ label }}<slot v-if="!label"></slot>
    </md-list-item-section>
    <md-list-item-section v-if="!isMulti && !$slots.customAnchor" key="child-1" position="right">
      <md-icon v-if="cxtActive" color="blue-50" name="check_20" />
    </md-list-item-section>
    <slot name="customAnchor"></slot>
  </md-list-item>
</template>

<script>
import uniqueId from 'lodash/uniqueId';

export default {
  name: 'md-select-option',

  data() {
    return {
      cxtActive: null,
      uniqueId: this.id || uniqueId('md-select-option-'),
    }
  },

  inject: {
    isMulti: {
      default: null
    },
    parentSelect: {
      default: null
    },
    getParentActive: {
      default: null
    },
  },

  props: {
    /** @prop SelectOption Boolean that describes active state | false */
    active: Boolean,
    /** @prop SelectOption ID | '' */
    id: {
      type: String,
      default: ''
    },
    /** @prop SelectOption label text | '' */
    label: {
      type: String,
      default: ''
    },
    /** @prop ListItem Title | '' */
    title: {
      type: String,
      default: ''
    },
    /** @prop SelectOption value | '' */
    value: {
      type: String,
      default: ''
    },
  },

  mounted() {
    this.cxtActive = this.getActive();
  },

  methods: {
    handleClick(e, opts) {
      if (this.parentSelect) {
        this.parentSelect(e, opts);
        this.cxtActive = this.getActive();
      }
      this.$emit('click', e);
    },

    getActive() {
      let parentActive;
      if (this.getParentActive) {
        parentActive = this.getParentActive();
      }
      return this.active
        || parentActive
        && this.$el
        && this.$el.attributes['data-md-event-key']
        && this.$el.attributes['data-md-event-key'].value
        && parentActive.includes(
          this.$el.attributes['data-md-event-key'].value
        );
    }
  },
};
</script>
