// vue/src/lib/checkbox-group/index.vue
<script>
import cloneElement from '../utils/cloneElement';

export default {
  name: 'md-checkbox-group',

  data() {
    return {
      activeValues: this.values
    }
  },

  render: function (h) {
    const { name } = this.$props;

    const addHandlersToChildren = () => {
      return this.$slots.default.map((child, idx) => {
        if (child.componentOptions) {
          const checked = this.activeValues.includes(child.componentOptions.propsData.value);
          return cloneElement(child, h, {
              name: name,
              checked: checked,
              attrs: {
                'aria-checked': checked,
              }
            });
        } else {
          return child;
        }
      });
    };

    return <div class="md-checkbox-group">{addHandlersToChildren()}</div>;
  },

  provide () {
    return {
      change: this.handleToggle,
    }
  },

  props: {
    /** @prop An HTML `<input>` name for each child button | '' */
    name: String,
    /** @prop An array of values, of the active (pressed) buttons | [] */
    values: {
      type: Array,
      default: () => []
    },
  },

  methods: {
    handleToggle(value) {
      let newValues;
      const isActive = this.activeValues.includes(value);

      if (isActive) {
        newValues = this.activeValues.filter(v => v !== value);
      } else {
        newValues = this.activeValues.concat(value);
      }
      this.activeValues = newValues;
      this.$emit('change', newValues);
    }
  },
};
</script>

// react/src/lib/CheckboxGroup/index.js
/** @component checkbox */

import React from 'react';
import PropTypes from 'prop-types';

class CheckboxGroup extends React.Component {
  static displayName = 'CheckboxGroup';

  state = {
    values: []
  }

  componentWillMount() {
    if (this.props.values) {
      this.setState({ values: this.props.values });
    }
  }

  handleToggle = value => {
    let newValues;
    const { onChange } = this.props;
    const { values } = this.state;
    const isActive = values.includes(value);

    if (isActive) {
      newValues = values.filter(v => v !== value);
      onChange(this.props.values.filter(n => n !== value));
    } else {
      newValues = values.concat(value);
      onChange([...this.props.values, value]);
    }

    this.setState({
      values: newValues,
    });
  }

  render() {
    const { children, name } = this.props;
    const { values } = this.state;

    const addHandlersToChildren = () => {
      return React.Children.map(children, child => {
        const { value } = child.props;
        return React.cloneElement(child, {
          name: name,
          checked: values.includes(value),
          'aria-checked': values.includes(value),
          onChange: () => this.handleToggle(value),
        });
      });
    };

    return <div className={`md-checkbox-group`}>{addHandlersToChildren()}</div>;
  }
}

CheckboxGroup.propTypes = {
  /** @prop Children nodes to render inside Accordion | null */
  children: PropTypes.node,
  /** @prop Callback fired with the value or array of active values when the user presses a button | null */
  onChange: PropTypes.func,
  /** @prop An array of values, of the active (pressed) buttons | () => {} */
  values: PropTypes.array,
  /** @prop An HTML `<input>` name for each child button | '' */
  name: PropTypes.string,
};

CheckboxGroup.defaultProps = {
  values: [],
  onChange: () => {},
  name: '',
};

export default CheckboxGroup;
