// vue/src/lib/date-picker/date-picker-week/index.vue
<script>
import { addDays, getStartOfWeek } from '../../utils/dateUtils.js';
import moment from 'moment';

export default {
  name: 'md-date-picker-week',

  render(h) {
    const { day, month, ...otherProps } = this.$props;

    const renderDays = () => {
      const startOfWeek = getStartOfWeek(day.clone());

      const days = [0, 1, 2, 3, 4, 5, 6].map(offset => {
        const day = addDays(startOfWeek.clone(), offset);
        return (
          <md-date-picker-day
            key={offset}
            day={day}
            month={month}
            {...{props: otherProps}}
            {...{attrs: this.$attrs}}
          />
        );
      });

      return days;
    };

    return (
      <div class="md-datepicker__week">
        {renderDays()}
      </div>
    );
  },

  props: {
    /** Required day for the DatePickerWeek */
    day: {
      type: Object,
      required: true
    },
    /** Required month that the DatePickerDay displays */
    month: {
      type: Number,
      required: true
    },
  },
};
</script>

// react/src/lib/DatePicker/DatePickerWeek/index.js
import React from 'react';
import PropTypes from 'prop-types';
import DatePickerDay from '@collab-ui/react/DatePicker/DatePickerDay';
import { addDays, getStartOfWeek } from '@collab-ui/react/utils/dateUtils';
import moment from 'moment';

class DatePickerWeek extends React.PureComponent {
  static displayName = 'DatePickerWeek';

  render() {
    const { day, ...otherProps } = this.props;

    const renderDays = () => {
      const startOfWeek = getStartOfWeek(day.clone());

      const days = [0, 1, 2, 3, 4, 5, 6].map(offset => {
        const day = addDays(startOfWeek.clone(), offset);
        return (
          <DatePickerDay
            key={offset}
            day={day}
            {...otherProps}
          />
        );
      });

      return days;
    };

    return (
      <div className="md-datepicker__week">
        {renderDays()}
      </div>
    );
  }
}

DatePickerWeek.propTypes = {
  /** Required day for the DatePickerWeek */
  day: PropTypes.instanceOf(moment).isRequired,
};

export default DatePickerWeek;
