// react/src/lib/AlertCall/DeviceListCall/index.js
import React from 'react';
import PropTypes from 'prop-types';
import { uniqueId } from 'lodash';
import {
  Icon,
  List,
  ListItem,
  ListItemHeader,
  ListItemSection
} from '@collab-ui/react';

class DeviceListCall extends React.PureComponent {
  static displayName = 'DeviceListCall'

  state = {
    selectedIndex: this.props.defaultSelected,
    id: uniqueId(this.props.id && `${this.props.id}-` || 'cui-device-list-call-'),
  };

  handleSelect = (e, value, index) => {
    const { onSelect, devices } = this.props;
    const currentIndex = devices.length < index - 1
      ? 0
      : index - 1;

    e.preventDefault();
    return this.setState({
      selectedIndex: currentIndex
    },
    () => (
      onSelect && onSelect(e, currentIndex, value)
    ));
  }

  render() {
    const { className, header, devices } = this.props;
    const { selectedIndex, id } = this.state;

    const getLeftSection = deviceType => {
      switch(deviceType) {
        case 'device': return <Icon name='spark-board_20' />;
        default: return <Icon name='laptop_20'/>;
      }
    };

    const getRightSection = (device, idx) => {
      if (idx === selectedIndex) {
        return <Icon name='check_20' color='blue'/>;
      }
    };

    return (
      <List
        className={className}
        onSelect={this.handleSelect}
        active={selectedIndex}
      >
        <ListItemHeader header={header} />
        {
          devices.map((ele, idx) => (
            <ListItem
              key={`device-${idx}`}
              id={id}
              value={ele}
              label={ele.name}
              title={ele.title || ele.name}
            >
              <ListItemSection position='left'>
                {getLeftSection(ele.type)}
              </ListItemSection>
              <ListItemSection position='center'>
                <div className='cui-list-item__header'>
                  {ele.name}
                </div>
              </ListItemSection>
              <ListItemSection position='right'>
                {getRightSection(ele, idx)}
              </ListItemSection>
            </ListItem>
          ))
        }
      </List>
    );
  }
}

DeviceListCall.defaultProps = {
  className: '',
  defaultSelected: 0,
  id: null,
  onSelect: null
};

DeviceListCall.propTypes = {
  /** Default Index Value selected */
  defaultSelected: PropTypes.number,
  /** required list of devices to show in list */
  devices: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string.isRequired,
      value: PropTypes.string,
      type: PropTypes.oneOf(['', 'device']),
      title: PropTypes.string
    })
  ).isRequired,
  /** HTML Class for associated input */
  className: PropTypes.string,
  /** ListItem header */
  header: PropTypes.string.isRequired,
  /** HTML ID for associated input */
  id: PropTypes.string,
  /** optional function called when list item is selected */
  onSelect: PropTypes.func
};

export default DeviceListCall;

// angular/src/lib/alert-call/device-list-call.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { ListItemComponent } from '@collab-ui/angular/list-item';
import uniqueId from 'lodash-es/uniqueId';

export type AlertCallDeviceType = '' | 'device';

export class AlertCallDevice {
  id?: string = uniqueId('cui-device-list-item-');
  name: string;
  value?: string;
  type?: AlertCallDeviceType;
  title?: string;
}

@Component({
  selector: 'cui-device-list-call',
  template: `
    <cui-list (select)="onSelect($event)">
      <cui-list-item-header cuiRemoveHost [header]="header"></cui-list-item-header>
      <div cui-list-item *ngFor="let device of devices; index as i"
        [value]="device.value"
        [title]="device.title || device.name"
      >
        <cui-list-item-section position="left">
          <ng-container [ngSwitch]="device.type">
            <cui-icon *ngSwitchCase="'device'" name="spark-board_20"></cui-icon>
            <cui-icon *ngSwitchDefault name="laptop_20"></cui-icon>
          </ng-container>
        </cui-list-item-section>
        <cui-list-item-section position="center">
          <div class="cui-list-item__header">
            {{ device.name }}
          </div>
        </cui-list-item-section>
        <cui-list-item-section position="right">
          <cui-icon *ngIf="i === selectedIndex || device.id === selectedIndex" name="check_20" color="blue"></cui-icon>
        </cui-list-item-section>
      </div>
    </cui-list>
  `,
})

export class DeviceListCallComponent {
  /** Default Index Value selected | null */
  @Input() defaultSelected: number | string;
  /** Required list of devices to show in list */
  @Input() devices: AlertCallDevice[];
  /** ListItem header */
  @Input() header: string;

  @Output() readonly select: EventEmitter<ListItemComponent> = new EventEmitter<ListItemComponent>();

  selectedIndex: number | string = this.defaultSelected;

  onSelect(listItem: ListItemComponent) {
    console.log(listItem);
    this.selectedIndex = listItem.id;
    this.select.emit(listItem);
  }
}
