// react/src/lib/Spinner/index.js
/** @component loader-spinner */

import React from 'react';
import PropTypes from 'prop-types';
import { isNumber, round } from 'lodash';

const Spinner = props => {
  const {
    className,
    color,
    showCheck,
    percentage,
    showPercentage,
    size,
    ...otherHTMLProps
  } = props;

  if(isNumber(percentage)) {
    if (size !== 36 && showPercentage) {
      /* eslint-disable no-console */
      console.warn('[@collab-ui/react] Spinner: Percentage will not be shown for sizes smaller than 36');
      /* eslint-enable no-console */
    }
    return (
      <div className={
        `cui-spinner-progress` +
        ` cui-spinner-progress__percentage-${round(percentage)}` +
        `${(size && ` cui-spinner-progress--${size}`) || ''}` +
        `${(color && ` cui-spinner-progress--${color}`) || ''}` +
        `${(className && ` ${className}`) || ''}`
        }
        {...otherHTMLProps}
      >
        <div className="cui-spinner-progress__circle">
          <div className="cui-spinner-progress__mask cui-spinner-progress__full">
            <div className="cui-spinner-progress__fill"/>
          </div>
          <div className="cui-spinner-progress__mask cui-spinner-progress__half">
            <div className="cui-spinner-progress__fill"/>
            <div className="cui-spinner-progress__fill cui-spinner-progress__fix"/>
          </div>
          <div className={
            `cui-spinner-progress__inset-circle` +
            `${showCheck && percentage === 100 && ' cui-spinner-progress__inset-circle--check' || ''}`
            }
          >
            {
              size === 36 && showPercentage && !showCheck
              && <div className="cui-spinner-progress__percentage">{round(percentage)}</div>
            }
          </div>
        </div>
      </div>
    );
  } else {
    return (
      <i className={
        `cui-spinner` +
        `${(size && ` cui-spinner--${size}`) || ''}` +
        `${(color && ` cui-spinner--${color}`) || ''}` +
        `${(className && ` ${className}`) || ''}`
        }
        {...otherHTMLProps}
      />
    );
  }
};

Spinner.propTypes = {
  /** @prop Optional CSS class names | '' */
  className: PropTypes.string,
  /** @prop Set Spinner color | '' */
  color: PropTypes.string,
  /** @prop Show percentage value for progress on Spinner | null */
  percentage: PropTypes.number,
  /** @prop Show the check mark if percentage 100 | false */
  showCheck: PropTypes.bool,
  /** @prop Show the number value for progress on Spinner | false */
  showPercentage: PropTypes.bool,
  /** @prop Spinner size | 36 */
  size: PropTypes.oneOf([16, 20, 28, 36]),
};

Spinner.defaultProps = {
  className: '',
  color: 'black',
  percentage: null,
  showCheck: false,
  showPercentage: false,
  size: 36,
};

Spinner.displayName = 'Spinner';

export default Spinner;

/**
* @component loader-spinner
* @section default
* @react
import { Spinner } from '@collab-ui/react';

export default function LoaderSpinnerDefault() {
  return (
    <Spinner />
  );
}

**/

/**
* @component loader-spinner
* @section determinate
* @react
import { Spinner } from '@collab-ui/react';

export default function LoaderSpinnerDeterminate() {
  return (
    <Spinner percentage={65}/>
  );
}

**/

/**
* @component loader-spinner
* @section percentage
* @react
import { Spinner } from '@collab-ui/react';

export default function LoaderSpinnerPercentage() {
  return (
    <Spinner
      percentage={65}
      showPercentage={true}
    />
  );
}

**/

/**
* @component loader-spinner
* @section check
* @react
import { Spinner } from '@collab-ui/react';

export default function LoaderSpinnerCheck() {
  return (
    <Spinner
      percentage={100}
      showCheck
    />
  );
}

**/

// angular/src/lib/spinner/spinner.component.ts
import { Component, Input, OnInit } from "@angular/core";

@Component({
  selector: 'cui-spinner',
  templateUrl: './spinner.component.html',
  styles: [],
})
export class SpinnerComponent implements OnInit {

  @Input() public className: string;
  @Input() public color: string = 'black';
  @Input() public size: number = 36;
  @Input() public percentage: number;
  @Input() public showCheck: boolean = false;
  @Input() public showPercentage: boolean = false;

  public isPercentage : boolean;

  constructor() { }

  ngOnInit() {
    this.checkPercentage(this.percentage);
  }

  get defaultClasses() {
    return {
      ['cui-spinner--' + this.size]: this.sizeCheck(this.size),
      ['cui-spinner--36']: Number(this.size) === 36,
      ['cui-spinner--' + this.color]: this.color,
      [this.className]: this.className,
    };
  }

  get percentageClasses() {
    return {
      ['cui-spinner-progress--' + this.size]: this.sizeCheck(this.size),
      ['cui-spinner-progress__percentage-' + this.percentage]: this.percentage,
      ['cui-spinner-progress--' + this.color]: this.color,
      [this.className]: this.className,
    };
  }

  get checkMarkClasses() {
    return {
      ['cui-spinner-progress__inset-circle--check']: this.sizeCheck(this.size) && this.showCheck,
      ['cui-spinner-progress__inset-circle--check' + this.percentage]: this.showCheck && Number(this.percentage) === 100,
    };
  }

  private checkPercentage = (percent) => {
    if(!isNaN(percent)){
      this.isPercentage = true;
      this.percentage = Math.round(percent);
    }
    if (Number(this.size) !== 36 && this.showPercentage) {
      console.warn('Spinner: Percentage will not be shown for sizes smaller than 36');
    }
  }

  private sizeCheck = (size) => {
    const sizes = [16, 20, 28, 36];
    if(sizes.includes(Number(size))){
      return true;
    }
    console.warn('Only sizes 16, 20, 28, 36 are acceptable for spinner')
    return false;
  }
}

/**
 * @component loader-spinner
 * @section default
 * @angular
 *
<div>
  <cui-spinner></cui-spinner>
</div>
 */

 /**
 * @component loader-spinner
 * @section determinate
 * @angular
 *
<div>
  <cui-spinner percentage=65></cui-spinner>
</div>
 */


 /**
 * @component loader-spinner
 * @section percentage
 * @angular
 *
<div>
  <cui-spinner percentage=65 showPercentage=true></cui-spinner>
</div>
 */


 /**
 * @component loader-spinner
 * @section check
 * @angular
 *
<div>
  <cui-spinner percentage=100 showCheck=true></cui-spinner>
</div>
 */

<div
  *ngIf="isPercentage; else normal"
  [ngClass]="percentageClasses"
  class="cui-spinner-progress"
>
  <div class="cui-spinner-progress__circle">
    <div class="cui-spinner-progress__mask cui-spinner-progress__full">
      <div class="cui-spinner-progress__fill"></div>
    </div>
    <div class="cui-spinner-progress__mask cui-spinner-progress__half">
      <div class="cui-spinner-progress__fill"></div>
      <div class="cui-spinner-progress__fill cui-spinner-progress__fix"></div>
    </div>
    <div
      [ngClass]="checkMarkClasses"
      class="cui-spinner-progress__inset-circle"
    >
      <div
        *ngIf="size === 36 && showPercentage && !showCheck"
        class="cui-spinner-progress__percentage"
      >
        {{ percentage | number: '1.0-0' }}
      </div>
    </div>
  </div>
</div>

<ng-template #normal>
  <i [ngClass]="defaultClasses" class="cui-spinner"></i>
</ng-template>
