// react/package/src/lib/Input/examples/Error.js
import React from 'react';
import { Input } from '@momentum-ui/react';

export default function InputError() {
  return (
    <Input
      name='inputError'
      label='Error Input'
      htmlId='inputError'
      containerSize='medium-6'
      messageArr={[
        { message: 'This is where the error message would be.', type: 'error' },
      ]}
      value='Error Text'
    />
  );
}

// vue/src/lib/input/examples/error.vue
<template>
  <md-input
    name="inputError"
    label="Error Input"
    htmlId="inputError"
    containerSize="medium-6"
    :messageArr="[
      { message: 'This is where the error message would be.', type: 'error' },
    ]"
    value="Error Text"
  />
</template>

<script>
export default {
  name: 'ExampleInputError',
};
</script>
