// react/examples/Input/error.js
import React from 'react';
import { Input } from '@collab-ui/react';
export default function InputError() {
  return (
    <div className='row'>
      <Input
        name='inputError'
        label='Error (Error) Input'
        htmlId='inputError'
        inputSize='small-5'
        errorArr={ [{error: 'This is where the error message would be.', type: 'error'}] }
      />
    </div>
  );
}

// vue/src/lib/input/examples/error.vue
<template>
  <md-input
    name="inputError"
    label="Error (Error) Input"
    htmlId="inputError"
    inputSize="small-5"
    :errorArr="[
      { error: 'This is where the error message would be.', type: 'error' },
    ]"
  />
</template>

<script>
export default {
  name: 'ExampleInputError',
};
</script>
