// react/src/lib/Input/examples/Success.js
import React from 'react';
import { Input } from '@momentum-ui/react';

export default function InputSuccess() {
  return (
    <Input
      name='inputSuccess'
      label='Success Input'
      htmlId='inputSuccess'
      containerSize='medium-6'
      messageArr={[
        {
          message: 'This is where the success message would be.',
          type: 'success',
        },
      ]}
      value='Success Text'
    />
  );
}

// vue/src/lib/input/examples/success.vue
<template>
  <md-input
    name="inputSuccess"
    label="Success Input"
    htmlId="inputSuccess"
    containerSize="medium-6"
    :messageArr="[
      { message: 'This is where the success message would be.', type: 'success' },
    ]"
    value="Success Text"
  />
</template>

<script>
export default {
  name: 'ExampleInputSuccess',
};
</script>
