// vue/src/lib/link/index.vue
<script>
export default {
  name: 'md-link',

  render(h) {
    return h(
      this.tag,
      {
        class: 'md-link' +
          `${(this.color && ` md-link--${this.color}`) || ''}` +
          `${(this.theme && ` md-link--${this.theme}`) || ''}`,
        attrs: {
          disabled: this.disabled,
          tabindex: !this.disabled ? 0 : null,
        }
      },
      this.$slots.default
    );
  },

  props: {
    /** @prop Optional color css styling | 'blue' */
    color: {
      type: String,
      default: 'blue'
    },
    /** @prop Sets the attribute disabled to the Link | false */
    disabled: Boolean,
    /** @prop Set HTML tag type | 'a' */
    tag: {
      type: String,
      default: 'a',
      validator: val => ['a', 'div', 'span'].indexOf(val) !== -1
    },
    /** @prop Set Link theme | ''  */
    theme: {
      type: String,
      default: ''
    },
  }
};
</script>

// react/package/src/lib/Link/index.js
/** @component link */

import React from 'react';
import PropTypes from 'prop-types';

const Link = ({ className, children, color, disabled, tag, theme, ...props }) => {
  return (
    React.createElement(
      tag,
      {
        className:
          'md-link' +
          `${(color && ` md-link--${color}`) || ''}` +
          `${(theme && ` md-link--${theme}`) || ''}` +
          `${(className && ` ${className}`) || ''}`,
        disabled: disabled,
        ...!disabled && { tabIndex: 0 },
        ...props
      },
      children
    )
  );
};

Link.propTypes = {
  /** @prop Children nodes to render inside Link Component | null */
  children: PropTypes.node.isRequired,
  /** @prop Optional css class string | '' */
  className: PropTypes.string,
  /** @prop Optional color css styling | 'blue' */
  color: PropTypes.string,
  /** @prop Sets the attribute disabled to the Link | false */
  disabled: PropTypes.bool,
  /** @prop Set HTML tag type | 'a' */
  tag: PropTypes.oneOf(['a', 'div', 'span']),
  /** @prop Set Link theme | ''  */
  theme: PropTypes.string,
};

Link.defaultProps = {
  children: null,
  className: '',
  color: 'blue',
  disabled: false,
  tag: 'a',
  theme: ''
};

Link.displayName = 'Link';

export default Link;
