// vue/src/lib/list/examples/header.vue
<template>
  <div class="medium-4 columns">
    <md-list>
      <md-list-item-header header="Testing">
        <router-link to="/containers/list-item">More</router-link>
      </md-list-item-header>
    </md-list>
    <md-list class="md--dark" style="background-color: rgba(40,40,40,0.72)">
      <md-list-item-header header="Testing">
        <router-link to="/containers/list-item">More</router-link>
      </md-list-item-header>
    </md-list>
  </div>
</template>

<script>
export default {
  name: 'ExampleListItemHeader',
};
</script>

// react/examples/ListItem/header.js
import React from 'react';
import { List, ListItemHeader } from '@collab-ui/react';
import { NavLink } from 'react-router-dom';
export default class SpaceListExamples extends React.PureComponent {
  render() {
    const anchorNode = <NavLink to='/containers/list-item'>More</NavLink>;
    return(
      <div className="medium-4 columns">
        <List>
          <ListItemHeader header='Testing' children={anchorNode} />
        </List>
        <List className='cui--dark' style={{backgroundColor: 'rgba(40,40,40,0.72)'}}>
          <ListItemHeader header='Testing' children={anchorNode}/>
        </List>
      </div>
    );
  }
}
