// react/src/lib/SidebarNavItem/index.js
/** @component sidebar */

import React from 'react';
import PropTypes from 'prop-types';
import omit from 'lodash/omit';
import { Icon, ListItem, ListItemSection } from '@momentum-ui/react';
import SidebarContext from '../SidebarContext';
import SidebarNavContext from '../SidebarNavContext';
import mapContextToProps from 'react-context-toolbox/mapContextToProps';
import { UIDConsumer, UIDFork } from 'react-uid';

class SidebarNavItem extends React.Component {
  state = {
    expanded: this.props.expanded
  };

  componentDidMount() {
    this.setParentContext();
  }

  componentDidUpdate(prevProps) {
    this.props.expanded !== prevProps.expanded
    && this.state.expanded !== this.props.expanded
    && this.setExpanded();
  }

  handleNavToggle = () => {
    this.setState({
      expanded: !this.state.expanded
    });
  }

  setExpanded = () => {
    this.setState({ expanded: this.props.expanded });
  }

  getHeaderLevel = () => {
    const { level } = this.props;

    if (!level) {
      return 'primary';
    } else if (level === 'primary') {
      return 'secondary';
    } else if (level === 'secondary') {
      return 'tertiary';
    }
  }

  setParentContext = () => {
    const { children, setContext } = this.props;
    const nextLevel = children && this.getHeaderLevel() || 'primary';

    nextLevel
    && setContext
    && setContext(nextLevel);
  }

  render() {
    const {
      children,
      className,
      level,
      icon,
      keyboardKey,
      title,
      titleNode,
      ...props
    } = this.props;
    const { expanded } = this.state;

    const otherProps = omit({...props}, [
      'expanded',
      'primary',
      'secondary',
      'setContext',
      'tertiary',
    ]);

    const getIcon = () => {
      const { secondary } = this.props;

      if(typeof icon === 'string') {
        return (
          <Icon
            name={icon}
            sizeOverride
            size={secondary ? 20 : 16}
          />
        );
      } else return icon;
    };

    const getSection = id => (
      !titleNode
        ? (
          <ListItem
            className={className}
            id={id}
            keyboardKey={keyboardKey || title}
            onClick={() => {children ? this.handleNavToggle() : false;}}
            {...otherProps}
          >
            {
              icon &&
              <ListItemSection position='left'>
                {getIcon()}
              </ListItemSection>
            }
            <ListItemSection position='center'>
              {title}
            </ListItemSection>
            {
              children &&
              <ListItemSection position='right'>
                {
                  expanded
                  ? <Icon name='arrow-up_12' />
                  : <Icon name='arrow-down_12' />
                }
              </ListItemSection>
            }
          </ListItem>
        )
        : React.cloneElement(titleNode, {
            id,
            onClick : () => {children ? this.handleNavToggle() : false;}
        })
    );

    const getHeaderLevel = () => {
      if (!level) {
        return 'primary';
      } else if (level === 'primary') {
        return 'secondary';
      } else if (level === 'secondary') {
        return 'tertiary';
      }
    };

    const headerLevel = getHeaderLevel();

    return (
      <UIDConsumer name={id => `md-sidebar__nav-item-${id}`}>
        {id => {
          return (
            <React.Fragment>
              {getSection(id)}
              {
                children &&
                <UIDFork>
                  <div className={
                    'md-sidebar-nav__group' +
                    ` md-sidebar-nav__group--${headerLevel}` +
                    ` md-sidebar-nav__group--${(!children || expanded) ? 'expanded' : 'collapsed'}`
                  }>
                    <SidebarNavContext.Provider value={{ level: headerLevel }}>
                      {children}
                    </SidebarNavContext.Provider>
                  </div>
                </UIDFork>
              }
            </React.Fragment>
          );
        }}
      </UIDConsumer>
    );
  }
}

SidebarNavItem.propTypes = {
  /** @prop Children nodes to Render inside side navigation | null */
  children: PropTypes.node,
  /** @prop Optional CSS class string | '' */
  className: PropTypes.string,
  /** @prop Set navigation expanded or collapsed | false */
  expanded: PropTypes.bool,
  /** @prop Icon string or node for the title | null */
  icon: PropTypes.node,
  /** @prop Unique string used for keyboard navigation | '' */
  keyboardKey: PropTypes.string,
  // Internal Context Use Only
  level: PropTypes.string,
  // Internal Context Use Only
  primary: PropTypes.bool,
  // Internal Context Use Only
  secondary: PropTypes.bool,
  // Internal Context Use Only
  setContext: PropTypes.func,
  // Internal Context Use Only
  tertiary: PropTypes.bool,
  /** @prop Node to replace title | null */
  titleNode: PropTypes.node,
  /** @prop Title for the side navigation | '' */
  title: PropTypes.string,
};

SidebarNavItem.defaultProps = {
  children: null,
  expanded: false,
  icon: null,
  keyboardKey: '',
  level: null,
  primary: false,
  secondary: false,
  tertiary: false,
  titleNode: null,
  title: '',
  setContext: null,
};

SidebarNavItem.displayName = 'SidebarNavItem';

export default mapContextToProps(
  [SidebarContext, SidebarNavContext],
  (sidebarContext, sidebarNavContext) => ({
    ...sidebarContext,
    ...sidebarNavContext
  }),
  SidebarNavItem
);

// vue/src/lib/sidebar/sidebar-nav-item/index.vue
<script>
import omit from 'lodash/omit';
import uniqueId from 'lodash/uniqueId';
import cloneElement from '../../utils/cloneElement';
import { Fragment } from 'vue-fragment'

export default {
  name: 'md-sidebar-nav-item',

  components: { Fragment },

  data() {
    return {
      expanded2: this.expanded,
    }
  },

  provide() {
    return {
      level: this.getHeaderLevel()
    }
  },

  inject: {
    level: {
      default: null
    },
    sidebar: {
      default: null
    },
    primary: {
      default: true
    },
    secondary: {
      default: false
    },
    tertiary: {
      default: false
    },
  },

  render(h) {
    const {
      className,
      icon,
      keyboardKey,
      title,
      ...props
    } = this.$props;
    const { expanded2 } = this.$data;

    const otherProps = omit({...props}, [
      'expanded',
    ]);

    const getIcon = () => {
      if (icon) {
        return (
          <md-icon
            name={icon}
            sizeOverride
            size={this.secondary ? 20 : 16}
          />
        );
      } else {
        return this.$slots.icon;
      }
    };

    const getSection = id => {
      const clickFunc = () => { this.$slots.default ? this.handleNavToggle() : false; }

      if (!this.$slots.title) {
        return (
          <md-list-item
            class={className}
            id={id}
            keyboardKey={keyboardKey || title}
            onClick={clickFunc}
            {...{props: otherProps}}
          >
            {
              (icon || this.$slots.icon)&&
              <md-list-item-section position='left'>
                {getIcon()}
              </md-list-item-section>
            }
            <md-list-item-section position='center'>
              {title}
            </md-list-item-section>
            {
              this.$slots.default &&
              <md-list-item-section position='right'>
                {
                  expanded2
                  ? <md-icon name='arrow-up_12' />
                  : <md-icon name='arrow-down_12' />
                }
              </md-list-item-section>
            }
          </md-list-item>
        )
      } else {
        const section = cloneElement(this.$slots.title[0], h, {
            props: {
              id: id
            }
        });
        if (section.componentOptions) {
          section.componentOptions.listeners = {
            click: clickFunc
          };
        }
        if (section.data) {
          section.data.on = {
            click: clickFunc
          };
          section.data.nativeOn = {
            click: clickFunc
          };
        }
        
        return section;
      }
    };

    return (
      <fragment name="sidebar-nav-item">
        {getSection(uniqueId('md-sidebar__nav-item-'))}
        {
          this.$slots.default &&
          <div class={
            'md-sidebar-nav__group' +
            ` md-sidebar-nav__group--${this.getHeaderLevel()}` +
            ` md-sidebar-nav__group--${(!this.$slots.default || expanded2) ? 'expanded' : 'collapsed'}`
          }>
            {this.$slots.default}
          </div>
        }
      </fragment>
    );
  },

  props: {
    /** @prop Optional CSS class string | '' */
    className: {
      type: String,
      default: ''
    },
    /** @prop Set navigation expanded or collapsed | false */
    expanded: Boolean,
    /** @prop Icon for the title | null */
    icon: String,
    /** @prop Unique string used for keyboard navigation | '' */
    keyboardKey: {
      type: String,
      default: ''
    },
    /** @prop Title for the side navigation | '' */
    title: {
      type: String,
      default: ''
    },
  },

  mounted() {
    this.setParentContext();
  },

  methods: {
    handleNavToggle() {
      this.expanded2 = !this.expanded2;
    },

    setExpanded() {
      this.expanded2 = this.expanded;
    },

    getHeaderLevel() {
      if (!this.level || this.level === 'primary') {
        return 'secondary';
      } else if (this.level === 'secondary') {
        return 'tertiary';
      }
    },

    setParentContext() {
      const nextLevel = this.$slots.default && this.getHeaderLevel() || 'primary';

      nextLevel
      && this.sidebar
      && this.sidebar.setSidebarLevel
      && this.sidebar.setSidebarLevel(nextLevel);
    },
  },
};
</script>
