// angular/src/lib/lightbox/lightbox.component.ts
/** @component lightbox */

import {
  Component,
  ElementRef,
  Inject,
  OnDestroy,
  OnInit,
  ViewChild,
} from '@angular/core';
import { DOCUMENT } from '@angular/common';
import { Subject } from 'rxjs';
import { LightboxConfig, LightboxInfo, LightboxPage, LightboxTooltips } from './lightbox-config';

@Component({
  selector: 'md-lightbox',
  template: `
    <div class="md-lightbox">
      <div #headerRef class="md-lightbox__header">
        <div class="md-lightbox__header-item--left">
          <div class="md-lightbox__header-meta">
            <div class="md-lightbox__header-sharer">{{ info.sharedBy }}</div>
            <div class="md-lightbox__header-timestamp">{{ info.sharedOn }}</div>
          </div>
        </div>
        <div class="md-lightbox__header-item--center">
          <div class="md-lightbox__header-name">{{ name }}</div>
        </div>
        <div class="md-lightbox__header-item--right">
          <div class="md-lightbox__control"
            [mdTooltip]="tooltips.exit"
            direction="left"
            delay="0"
            (click)="destroy()"
            (keypress)="handleKeypress($event, 'destroy')"
            role="button"
            tabindex="0">
              <md-icon name="cancel_16"></md-icon>
          </div>
        </div>
      </div>
      <div class="md-lightbox__body">
        <ng-container *ngTemplateOutlet="thumbnailsTemplate"></ng-container>
        <div
          class="md-lightbox__content"
          (click)="destroy()"
          (keypress)="handleKeypress($event, 'destroy')"
          role="button"
          tabindex="0"
        >
          <div
            #viewportRef
            class="md-lightbox__viewport"
            [ngClass]="{ 'md-lightbox__viewport--decrypting': !!currentPage.decrypting }"
          >
            <md-spinner *ngIf="pages[index].decrypting" class="md-lightbox__decrypting-spinner"></md-spinner>
            <ng-container *ngTemplateOutlet="viewportTemplate"></ng-container>
          </div>
          <ng-container *ngTemplateOutlet="leftArrowControlTemplate"></ng-container>
          <ng-container *ngTemplateOutlet="rightArrowControlTemplate"></ng-container>
          <ng-container *ngTemplateOutlet="viewportControlsTemplate"></ng-container>
        </div>
      </div>
    </div>

    <ng-template #thumbnailsTemplate>
      <div *ngIf="pages.length > 1" class="md-lightbox__list">
        <div *ngFor="let page of pages; index as idx"
          class="md-lightbox__thumbnail-wrapper"
          [ngClass]="{ 'md-lightbox__thumbnail-wrapper--selected': idx === index }"
          (click)="handleThumbnailClick(idx)"
          (keypress)="handleKeypress($event, 'thumbnail', idx)"
          role="button"
          tabindex="0"
        >
          <div *ngIf="page.decrypting"
            class="md-lightbox__thumbnail md-lightbox__thumbnail--decrypting"
            [attr.dataindex]="idx"
            [ngStyle]="thumbnailDecryptingStyle"
          >
            <md-icon class="md-lightbox__thumbnail--icon" name="secure_28"></md-icon>
          </div>
          <img *ngIf="!page.decrypting"
            alt=""
            class="md-lightbox__thumbnail"
            [attr.dataindex]="idx"
            [attr.draggable]="false"
            [attr.src]="page.thumb"
          />
          <div>
            {{ idx + 1 }}
          </div>
        </div>
      </div>
    </ng-template>

    <ng-template #viewportTemplate>
      <div
        class="md-lightbox__viewport-wrapper"
        [ngStyle]="viewportStyle"
      >
        <div *ngIf="currentPage.content">
          <div
            class="md-lightbox__viewport-content"
            [attr.draggable]="false"
            (click)="stopPropagation($event)"
            (keypress)="stopPropagation($event)"
            (doubleclick)="setZoom(0.25)"
            role="button"
            tabindex="0"
          >
            {{ currentPage.content }}
          </div>
        </div>
        <div *ngIf="currentPage.image">
          <div *ngIf="zoom <= 1">
            <img
              alt=""
              class="md-lightbox__viewport-image"
              [attr.draggable]="false"
              (click)="stopPropagation($event)"
              (keypress)="stopPropagation($event)"
              (doubleclick)="setZoom(0.25)"
              [attr.src]="currentPage.thumb"
            />
          </div>
          <div *ngIf="zoom > 1">
            <img
              alt=""
              class="md-lightbox__viewport-image"
              [attr.draggable]="false"
              (click)="stopPropagation($event)"
              (keypress)="stopPropagation($event)"
              (doubleclick)="setZoom(0.25)"
              [attr.src]="currentPage.thumb"
              [ngStyle]="{
                'object-fit': 'contain',
                'max-height': height * zoom + 'px',
                'max-width': width * zoom + 'px',
                'min-height': height * zoom + 'px',
                'min-width': width * zoom + 'px'
              }"
            />
          </div>
        </div>
      </div>
    </ng-template>

    <ng-template #leftArrowControlTemplate>
      <div *ngIf="pages.length > 1"
        [mdTooltip]="tooltips.previous"
        direction="right"
        delay="0"
        class="md-lightbox__page-control md-lightbox__page-control-icon md-lightbox__page-controls--left"
        role="button"
        tabindex="0"
        (click)="triggerPageChange(index - 1, $event)"
        (keypress)="handleKeypress($event, 'change', index - 1)"
        style="transform: rotate(-180deg)"
      >
        <md-icon name="icon-arrow-right_16"></md-icon>
      </div>
    </ng-template>

    <ng-template #rightArrowControlTemplate>
      <div *ngIf="pages.length > 1"
        [mdTooltip]="tooltips.next"
        direction="left"
        delay="0"
        class="md-lightbox__page-control md-lightbox__page-control-icon md-lightbox__page-controls--right"
        role="button"
        tabindex="0"
        (click)="triggerPageChange(index + 1, $event)"
        (keypress)="handleKeypress($event, 'change', index + 1)"
      >
        <md-icon name="icon-arrow-right_16"></md-icon>
      </div>
    </ng-template>

    <ng-template #viewportControlsTemplate>
      <div
        class="md-lightbox__viewer-controls"
        (click)="stopPropagation($event)"
        (keypress)="stopPropagation($event)"
        role="button"
        tabindex="0"
      >
        <div class="md-lightbox__controls" [ngStyle]="controlStyle">
          <div class="md-lightbox__control"
            [mdTooltip]="tooltips.zoomOut"
            delay="0"
            (click)="setZoom(-0.25)"
            (keypress)="handleKeypress($event, 'zoom', -0.25)"
            role="button"
            tabindex="0"
          >
              <md-icon name="zoom-out_16"></md-icon>
          </div>
          <span class="md-lightbox__control-value">{{ math.round(zoom * 100) }}%</span>
          <div class="md-lightbox__control"
            [mdTooltip]="tooltips.zoomIn"
            delay="0"
            (click)="setZoom(0.25)"
            (keypress)="handleKeypress($event, 'zoom', 0.25)"
            role="button"
            tabindex="0"
          >
            <md-icon name="zoom-in_16"></md-icon>
          </div>
        </div>
        <ng-container *ngTemplateOutlet="pageControlTemplate"></ng-container>
        <div class="md-lightbox__controls" [ngStyle]="controlStyle">
          <span class="md-lightbox__control-value">{{ info.size }}</span>
          <div *ngIf="downloading"
            [mdTooltip]="tooltips.downloading"
            delay="0"
            class="md-lightbox__control md-lightbox__control-spinner">
            <md-spinner size="28"></md-spinner>
          </div>
          <div *ngIf="!downloading"
            [mdTooltip]="tooltips.download"
            delay="0"
            class="md-lightbox__control md-lightbox__control-download"
            (click)="handleDownload()"
            (keypress)="handleKeypress($event, 'download')"
            role="button"
            tabindex="0"
          >
            <md-icon name="download_16"></md-icon>
          </div>
        </div>
      </div>
    </ng-template>

    <ng-template #pageControlTemplate>
      <div *ngIf="pages.length > 1" class="md-lightbox__controls md-lightbox__controls--center">
        <div class="md-lightbox__control"
          [mdTooltip]="tooltips.previous"
          delay="0"
          (click)="triggerPageChange(index - 1, $event)"
          (keypress)="handleKeypress($event, 'change', index - 1)"
          role="button"
          tabindex="0"
          style="transform: rotate(-180deg)"
        >
          <md-icon name="icon-arrow-right_16"></md-icon>
        </div>
        <span class="md-lightbox__control-value">{{ index + 1 }} / {{ pages.length }}</span>
        <div class="md-lightbox__control"
          [mdTooltip]="tooltips.next"
          delay="0"
          (click)="triggerPageChange(index + 1, $event)"
          (keypress)="handleKeypress($event, 'change', index + 1)"
          role="button"
          tabindex="0"
        >
          <md-icon name="icon-arrow-right_16"></md-icon>
        </div>
      </div>
      <div *ngIf="pages.length === 1" class="md-lightbox__controls">
        <span class="md-lightbox__control-value">{{ index + 1 }}</span>
      </div>
    </ng-template>
  `,
  host: {
    'class': 'md-lightbox__container'
  }
})
export class LightboxComponent implements OnInit, OnDestroy {
  decrypting: boolean;
  downloading: boolean;
  height: number;
  index: number;
  info: LightboxInfo;
  math = Math;
  name: string;
  pages: Array<LightboxPage>;
  tooltips: LightboxTooltips;
  viewportDimensions = {
    width: 600,
    height: 600
  };
  width: number;
  zoom: number = 1;

  readonly _onDestroy: Subject<any> = new Subject();
  private _document: Document;

  @ViewChild('headerRef') headerRef: ElementRef;
  @ViewChild('viewportRef') viewportRef: ElementRef;

  get currentPage(): LightboxPage {
    return this.pages[this.index];
  }

  get controlStyle() {
    return this.currentPage.content ? {
      visibility: 'hidden'
    } : {};
  }

  get thumbnailDecryptingStyle() {
    return { height: Math.round(this.height / (this.width / 150)) };
  }

  get viewportStyle() {
    const srcWidth: number = this.width * this.zoom;
    const srcHeight: number = this.height * this.zoom;
    const maxWidth: number = this.viewportDimensions.width;
    const maxHeight: number = this.viewportDimensions.height;
    const ratio = Math.min(maxWidth / srcWidth, maxHeight / srcHeight, 1);

    const width: number = Math.round(srcWidth * ratio);
    const height: number = Math.round(srcHeight * ratio);

    return this.zoom <= 1 ? {
      width: `${width}px`,
      height: `${height}px`
    } : {};
  }

  get config(): LightboxConfig {
    return this._config;
  }

  constructor(private _config: LightboxConfig, @Inject(DOCUMENT) _document: any) {
    this.decrypting = _config.decrypting;
    this.downloading = _config.downloading;
    this.height = _config.height;
    this.index = _config.index;
    this.info = _config.info;
    this.name = _config.name;
    this.pages = _config.pages;
    this.tooltips = _config.tooltips;
    this.width = _config.width;
    this._document = _document;
  }

  ngOnInit(): void {
    this._document.addEventListener('keydown', this.handleKeydown);
    this._document.addEventListener('resize', this.handleResize);
  }

  ngOnDestroy(): void {
    this._document.removeEventListener('keydown', this.handleKeydown);
    this._document.removeEventListener('resize', this.handleResize);
    if (this._config.onClose) {
      this._config.onClose();
    }
  }

  handleResize = () => {
    this.viewportDimensions = {
      width: this.viewportRef.nativeElement.offsetWidth,
      height: this.viewportRef.nativeElement.offsetHeight
    };
  }

  handleKeydown = (e: KeyboardEvent) => {
    let newIndex: number;
    switch (e.code) {
      case 'Escape':
        this.destroy();
        return;
      case 'ArrowLeft':
      case 'ArrowUp':
        newIndex = Math.max(this.index - 1, 0);
        break;
      case 'ArrowRight':
      case 'ArrowDown':
        newIndex = Math.min(this.index + 1, this.pages.length - 1);
        break;
      case 'PageUp':
      case 'Home':
        newIndex = 0;
        break;
      case 'PageDown':
      case 'End':
        newIndex = this.pages.length - 1;
        break;
      case 'Digit1':
      case 'Digit2':
      case 'Digit3':
      case 'Digit4':
      case 'Digit5':
      case 'Digit6':
      case 'Digit7':
      case 'Digit8':
      case 'Digit9':
        newIndex = Math.min(Number(e.code.substr(-1)) - 1, this.pages.length - 1);
        break;
      default:
        return;
    }
    this.triggerPageChange(newIndex, e);
  }

  handleThumbnailClick(index: number): void {
    this.index = index;
    if (this._config.onChange) {
      this._config.onChange(index);
    }
  }

  triggerPageChange(index: number, e: MouseEvent | KeyboardEvent): void {
    const target: HTMLElement = this.headerRef.nativeElement.querySelector(`[dataindex="${index}"]`);
    if (index >= 0 && index <= this.pages.length - 1) {
      this.index = index;
      if (this._config.onChange) {
        this._config.onChange(index);
      }
    }
    if (target) {
      target.scrollIntoView();
    }
    e.stopPropagation();
  }

  stopPropagation(e: MouseEvent | KeyboardEvent): void {
    e.stopPropagation();
  }

  setZoom(increment: number): void {
    const newZoom = this.zoom + increment;
    this.zoom = newZoom < 0.25 ? 0.25 : newZoom;
  }

  handleDownload(): void {
    if (this._config.onDownload) {
      this._config.onDownload(this.currentPage);
    }
  }

  handleKeypress(e: KeyboardEvent, type: string, param?: any): void {
    if (e.code === 'Enter' || e.code === 'Space') {
      switch (type) {
        case 'destroy':
          this.destroy();
          break;
        case 'thumbnail':
          this.handleThumbnailClick(param);
          break;
        case 'change':
          this.triggerPageChange(param, e);
          break;
        case 'download':
          this.handleDownload();
          break;
        case 'zoom':
          this.setZoom(param);
          break;
      }
    }
  }

  destroy(): void {
    this._onDestroy.next();
    this._onDestroy.complete();
  }
}

// react/src/lib/Lightbox/index.js
/** @component lightbox */

import React from 'react';
import PropTypes from 'prop-types';
import Modal from 'react-aria-modal';
import { Spinner, Tooltip, Icon } from '@momentum-ui/react';

class Lightbox extends React.Component {

  state = {
    viewportDimensions: {
      width: 600,
      height: 600
    },
    zoom: 1
  }

  componentDidMount() {
    window.addEventListener('keydown', this.handleKeyDown, true);
    window.addEventListener('resize', this.handleResize, true);
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.index !== this.props.index && this.state.zoom > 1 && this.imgWrapper) {
      const viewportNode = this.viewport;
      viewportNode.scrollTop = 0;
      viewportNode.scrollLeft = (this.imgWrapper.offsetWidth - viewportNode.offsetWidth) / 2;
    }
  }

  componentWillUnmount() {
    window.removeEventListener('keydown', this.handleKeyDown, true);
    window.removeEventListener('resize', this.handleResize, true);
  }

  handleResize = () => {
    const { viewport } = this;
    this.setState({
      viewportDimensions: {
        width: viewport.offsetWidth,
        height: viewport.offsetHeight
      }
    });
  }

  handleKeyDown = e => {
    const { index, pages } = this.props;
    let newIndex;

    switch (e.keyCode) {
      // Escape
      case 27:
        this.handleClose();
        return;
      // left arrow & up arrow
      case 37:
      case 38:
        newIndex = Math.max(index - 1, 0);
        break;
      // right arrow & down arrow
      case 39:
      case 40:
        newIndex = Math.min(index + 1, pages.length - 1);
        break;
      // page up & home
      case 33:
      case 36:
        newIndex = 0;
        break;
      // page down & end
      case 34:
      case 35:
        newIndex = pages.length - 1;
        break;
      // 1 - 9
      case 49:
      case 50:
      case 51:
      case 52:
      case 53:
      case 54:
      case 55:
      case 56:
      case 57:
        newIndex = Math.min(e.keyCode - 49, pages.length - 1);
        break;
      default:
        return;
    }
    this.triggerPageChange(newIndex, e);
  }

  handleThumbnailClick = index => {
    const { onChange } = this.props;
    onChange && onChange(index);
  }

  triggerPageChange = (index, e) => {
    const { onChange, pages } = this.props;
    const target = this.lightBox && this.lightBox.querySelector(`[data-index="${index}"]`);
    if (index >= 0 && index <= pages.length - 1) {
      onChange && onChange(index);
    }
    e.stopPropagation();
    target && target.scrollIntoViewIfNeeded();
  }

  stopPropagation = e => {
    e.stopPropagation();
  }

  setZoom = increment => {
    const newZoom = this.state.zoom + increment;
    this.setState({
      zoom: newZoom < 0.25 ? 0.25 : newZoom
    });
  }

  handleDownload = () => {
    const { onDownload } = this.props;
    onDownload && onDownload();
  }

  handleClose = () => {
    const { onClose } = this.props;
    onClose && onClose();
  }

  render() {
    const { pages, index, width, height, tooltips, downloading, info, name, applicationId } = this.props;
    const { zoom, viewportDimensions } = this.state;
    const currentPage = pages[index];
    const showColumn = pages.length > 1;

    const calculateAspectRatioFit = (srcWidth, srcHeight, maxWidth, maxHeight) => {
      const ratio = Math.min(maxWidth / srcWidth, maxHeight / srcHeight, 1);
      return {
        width: Math.round(srcWidth * ratio),
        height: Math.round(srcHeight * ratio)
      };
    };

    const getThumbnails = () => {
      const thumbnails = pages.map((page, idx) => {
        let key = `${idx}:${page.thumb}`;
        let body;

        if (page.decrypting) {
          const scale = width / 150;
          const scaleY = height / scale;
          const style = {
            height: Math.round(scaleY)
          };
          key += ':decrypting';

          body = (
            <div
              className={
                `md-lightbox__thumbnail` +
                `${(!!page.decrypting && ` md-lightbox__thumbnail--decrypting`) || ''}`
              }
              data-index={idx}
              style={style}
            >
              <Icon className="md-lightbox__thumbnail--icon" name="secure_28" />
            </div>
          );
        }
        else {
          body = (
            <img
              alt=""
              className={
                `md-lightbox__thumbnail` +
                `${(!!page.decrypting && ` md-lightbox__thumbnail--decrypting`) || ''}`
              }
              data-index={idx}
              draggable="false"
              onDragStart={() => false}
              src={page.thumb}
            />
          );
        }

        return (
          <div
            className={
              'md-lightbox__thumbnail-wrapper' +
              `${(idx === index && ` md-lightbox__thumbnail-wrapper--selected`) || ''}`
            }
            key={key}
            onClick={() => this.handleThumbnailClick(idx)}
            onKeyPress={() => this.handleThumbnailClick(idx)}
            role="button"
            tabIndex="0"
          >
            {body}
            <div>
              {idx + 1}
            </div>
          </div>
        );
      });
      return (
        <div className="md-lightbox__list">
          {thumbnails}
        </div>
      );
    };

    const getViewport = () => {
      let viewport;
      const dimensions = calculateAspectRatioFit(
        width * zoom,
        height * zoom,
        viewportDimensions.width,
        viewportDimensions.height
      );
      let imageContainerStyles = {
        width: `${dimensions.width}px`,
        height: `${dimensions.height}px`
      };

      if (currentPage.content) {
        if (currentPage.fullView) {
          imageContainerStyles = {
              width:  '100%',
              height: '100%',
              overflow: 'hidden'
          };
        }
        viewport = (
          <div
            className="md-lightbox__viewport-content"
            draggable="false"
            onClick={this.stopPropagation}
            onKeyPress={this.stopPropagation}
            onDoubleClick={() => this.setZoom(0.25)}
            onDragStart={() => false}
            role="button"
            tabIndex="0"
          >
            {currentPage.content}
          </div>
        );
      }
      else if (currentPage.image) {
        if (zoom <= 1) {
          /* eslint-disable jsx-a11y/no-noninteractive-element-interactions */
          viewport = (
            <img
              alt=""
              className="md-lightbox__viewport-image"
              draggable="false"
              onClick={this.stopPropagation}
              onKeyPress={this.stopPropagation}
              onDoubleClick={() => this.setZoom(0.25)}
              onDragStart={() => false}
              src={currentPage.image}
            />
          );
        }
        else {
          imageContainerStyles = {};
          viewport = (
            <img
              alt=""
              className="md-lightbox__viewport-image"
              draggable="false"
              onClick={this.stopPropagation}
              onKeyPress={this.stopPropagation}
              onDoubleClick={() => this.setZoom(0.25)}
              onDragStart={() => false}
              src={currentPage.image}
              style={{
                maxHeight: height * zoom,
                maxWidth: width * zoom,
                minHeight: height * zoom,
                minWidth: width * zoom
              }}
            />
          );
        }
      }

      return (
        <div
          className="md-lightbox__viewport-wrapper"
          ref={ref => this.imgWrapper = ref}
          style={imageContainerStyles}
        >
          {viewport}
        </div>
      );
    };



    const leftArrowControl = (
      <Tooltip tooltip={tooltips.previous} direction="right-center">
        <div
          className="md-lightbox__page-control md-lightbox__page-control-icon md-lightbox__page-controls--left"
          role="button"
          tabIndex="0"
          onKeyPress={e => this.triggerPageChange(index - 1, e)}
          onClick={e => this.triggerPageChange(index - 1, e)}
          style={{transform: 'rotate(-180deg)'}}
        >
          <Icon name="arrow-right_16" />
        </div>
      </Tooltip>
    );

    const rightArrowControl = (
      <Tooltip tooltip={tooltips.next} direction="left-center">
        <div
          className="md-lightbox__page-control md-lightbox__page-control-icon md-lightbox__page-controls--right"
          role="button"
          tabIndex="0"
          onKeyPress={e => this.triggerPageChange(index + 1, e)}
          onClick={e => this.triggerPageChange(index + 1, e)}
        >
          <Icon name="arrow-right_16" />
        </div>
      </Tooltip>
    );

    const viewportControls = () => {
      const downloadButton = (
        <div
          className="md-lightbox__control md-lightbox__control-download"
          tabIndex="0"
          role="button"
          onClick={this.handleDownload}
          onKeyPress={this.handleDownload}
        >
          <Icon name="download_16"/>
        </div>
      );

      const controlStyle = currentPage.content ? {
        visibility: 'hidden'
      } : {};

      const pageControl = pages.length > 1 ? (
        <div className="md-lightbox__controls md-lightbox__controls--center">
          <Tooltip tooltip={tooltips.previous}>
            <div className="md-lightbox__control"
              onClick={e => this.triggerPageChange(index - 1, e)}
              role="button"
              tabIndex="0"
              onKeyPress={e => this.triggerPageChange(index - 1, e)}
              style={{transform: 'rotate(-180deg)'}}
            >
              <Icon name="arrow-right_16"/>
            </div>
          </Tooltip>
          <span className="md-lightbox__control-value">{`${index + 1} / ${pages.length}`}</span>
          <Tooltip tooltip={tooltips.next}>
            <div className="md-lightbox__control"
              role="button"
              onClick={e => this.triggerPageChange(index + 1, e)}
              tabIndex="0"
              onKeyPress={e => this.triggerPageChange(index + 1, e)}
            >
              <Icon name="arrow-right_16"/>
            </div>
          </Tooltip>
        </div>
      ) : (
        <div className="md-lightbox__controls">
          <span className="md-lightbox__control-value">{index + 1}</span>
        </div>
      );


      return (
        <div
          className="md-lightbox__viewer-controls"
          onClick={this.stopPropagation}
          onKeyPress={this.stopPropagation}
          role="button"
          tabIndex="0"
        >
          <div className="md-lightbox__controls" style={controlStyle}>
            <Tooltip tooltip={tooltips.zoomOut}>
              <div className="md-lightbox__control"
                onClick={() => this.setZoom(-0.25)}
                role="button"
                tabIndex="0"
                onKeyPress={() => this.setZoom(-0.25)}
              >
                  <Icon name="zoom-out_16"/>
              </div>
            </Tooltip>
            <span className="md-lightbox__control-value">{Math.round(zoom * 100)}%</span>
            <Tooltip tooltip={tooltips.zoomIn}>
              <div className="md-lightbox__control"
                role="button"
                onClick={() => this.setZoom(0.25)}
                tabIndex="0"
                onKeyPress={() => this.setZoom(0.25)}
              >
                <Icon name="zoom-in_16"/>
              </div>
            </Tooltip>
          </div>
          {pageControl}
          <div className="md-lightbox__controls" style={controlStyle}>
            <span className="md-lightbox__control-value">{info.size}</span>
            <Tooltip tooltip={downloading ? tooltips.downloading : tooltips.download}>
                { downloading ?
                    <div className="md-lightbox__control md-lightbox__control-spinner">
                      <Spinner size={28}/>
                    </div> :
                    downloadButton
                }
            </Tooltip>
          </div>
        </div>
      );
    };

    return (
      <Modal
        includeDefaultStyles={false}
        getApplicationNode={() => document.querySelector(`#${applicationId}`)}
        onExit={this.handleClose}
        focusDialog={true}
        titleId="md-lightbox"
        dialogClass="md-lightbox"
        underlayClass="md-lightbox__container"
      >
        <div className="md-lightbox__header" ref={ref => this.lightBox = ref}>
          <div className="md-lightbox__header-item--left">
            <div className="md-lightbox__header-meta">
              <div className="md-lightbox__header-sharer">
                {info.sharedBy}
              </div>
              <div className="md-lightbox__header-timestamp">
                {info.sharedOn}
              </div>
            </div>
          </div>
          <div className="md-lightbox__header-item--center">
            <div className="md-lightbox__header-name">
              {name}
            </div>
          </div>
          <div className="md-lightbox__header-item--right">
            <Tooltip tooltip={tooltips.exit} direction="bottom-right">
              <div className="md-lightbox__control"
                onClick={this.handleClose}
                role="button"
                tabIndex="0"
                onKeyPress={this.handleClose}>
                  <Icon name="cancel_16"/>
              </div>
            </Tooltip>
          </div>
        </div>
        <div className="md-lightbox__body">
          {showColumn && getThumbnails()}
          <div
            className="md-lightbox__content"
            onClick={this.handleClose}
            onKeyPress={this.handleClose}
            role="button"
            tabIndex="0"
          >
            <div
              className={
                `md-lightbox__viewport` +
                `${(!!currentPage.decrypting && ` md-lightbox__viewport--decrypting`) || ''}`
              }
              ref={ref => this.viewport = ref}
            >
              {
                pages[index].decrypting &&
                <Spinner className="md-lightbox__decrypting-spinner" />
              }
              {getViewport()}
            </div>
            {showColumn && leftArrowControl}
            {showColumn && rightArrowControl}
            {viewportControls()}
          </div>
        </div>
      </Modal>
    );
  }
}

Lightbox.propTypes = {
  /** @prop ID for Lightbox query lookup */
  applicationId: PropTypes.string.isRequired,
  /** Determines if info is decrypting | false */
  decrypting: PropTypes.bool,
  /** @prop Optional downloading css styling | false */
  downloading: PropTypes.bool,
  /** @prop Set Height value of Lightbox */
  height: PropTypes.number.isRequired,
  /** @prop Initial index of start page | 0 */
  index: PropTypes.number,
  /** @prop Lightbox information Object | {} */
  info: PropTypes.shape({
    sharedBy: PropTypes.string,
    sharedOn: PropTypes.string,
    size: PropTypes.string
  }),
  /** @prop Required name prop for Lightbox */
  name: PropTypes.string.isRequired,
  /** @prop Callback function invoked by user when interact with Lightbox | null */
  onChange: PropTypes.func,
  /** @prop Callback function invoked by user closing the Lightbox | null */
  onClose: PropTypes.func,
  /** @prop Callback function invoked by the download action of Lightbox | null */
  onDownload: PropTypes.func,
  /** @prop Array of Lightbox pages */
  pages: PropTypes.array.isRequired,
  /** @prop Collection of predefined tootips for various Lightbox actions | { download: 'Download', etc } */
  tooltips: PropTypes.shape({
    download: PropTypes.string,
    downloading: PropTypes.string,
    exit: PropTypes.string,
    previous: PropTypes.string,
    next: PropTypes.string,
    zoomIn: PropTypes.string,
    zoomOut: PropTypes.string
  }),
  /** @prop Set Width value for Lightbox */
  width: PropTypes.number.isRequired,
};

Lightbox.defaultProps = {
  decrypting: false,
  downloading: false,
  index: 0,
  info: {},
  name: '',
  onChange: null,
  onClose: null,
  onDownload: null,
  tooltips: {
    download: 'Download',
    downloading: 'Downloading...',
    exit: 'Exit',
    previous: 'Previous',
    next: 'Next',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out'
  },
};

Lightbox.displayName = 'Lightbox';

export default Lightbox;
