// vue/src/lib/tab-pane/index.vue
<template>
  <div
    class="md-tab__pane"
    :class="{ active: active }"
  >
    <div class="md-tab__content"><slot></slot></div>
  </div>
</template>

<script>
export default {
  name: 'md-tab-pane',

  props: {
    /** @prop Determines if TabPane is active | false */
    active: Boolean,
  }
};
</script>

// react/package/es/TabPane/index.js
/** @component tabs */
import React from 'react';
import PropTypes from 'prop-types';

var TabPane = function TabPane(props) {
  var children = props.children,
      active = props.active;
  return React.createElement("div", {
    className: "md-tab__pane" + ("" + (active ? ' active' : ''))
  }, React.createElement("div", {
    className: "md-tab__content"
  }, children));
};

TabPane.propTypes = {
  /** @prop Determines if TabPane is active | false */
  active: PropTypes.bool,

  /** @prop Children nodes to render inside TabPane | null */
  children: PropTypes.node
};
TabPane.defaultProps = {
  active: false,
  children: null
};
TabPane.displayName = 'TabPane';
export default TabPane;
