// angular/src/lib/form/form-info.component.ts
/** @component form */

import { Component, Input } from '@angular/core';

/**
 * FormInfo is supplemental, organizational component used to help divide form
 **/

@Component({
  selector: 'md-form-info',
  template: `
    <h4 class="section__title">{{ title }}</h4>
    <p *ngIf="description" class="section__description">{{ description }}</p>
  `,
  host: {
    'class': 'section__info',
  }
})

export class FormInfoComponent {
  /** @prop Optional FormInfo description text | '' */
  @Input() description: string = '';
  /** @prop Optional FormInfo title | '' */
  @Input() title: string = '';
}

// react/package/es/FormInfo/index.js
/** @component form */
import React from 'react';
import PropTypes from 'prop-types';
/**
 * FormInfo is supplemental, organizational component used to help divide form
 **/

var FormInfo = function FormInfo(props) {
  var title = props.title,
      description = props.description;
  return React.createElement("div", {
    className: "section__info"
  }, React.createElement("h4", {
    className: "section__title"
  }, title), description && React.createElement("p", {
    className: "section__description"
  }, description));
};

FormInfo.propTypes = {
  /** @prop Optional FormInfo description text | '' */
  description: PropTypes.string,

  /** @prop Optional FormInfo title | '' */
  title: PropTypes.string
};
FormInfo.defaultProps = {
  description: '',
  title: ''
};
FormInfo.displayName = 'FormInfo';
export default FormInfo;
