// react/package/src/lib/Menu/examples/CustomMenuItems.js
import React from 'react';
import {
  Button,
  Icon,
  ListItemSection,
  Menu,
  MenuContent,
  MenuItem,
  MenuOverlay,
} from '@momentum-ui/react';
export default class CustomMenuItems extends React.PureComponent {
  onClick(event, value) {
    alert(`${value} clicked`);
  }
  render() {
    return (
      <MenuOverlay
        menuTrigger={
          <Button id="custom" ariaLabel="Show Custom Menu">
            Show Customized MenuItems
          </Button>
        }
        direction="top-center"
      >
        <MenuContent>Content</MenuContent>
        <Menu>
          <MenuItem>
            <ListItemSection position="left">
              <Icon name="edit_20" />
            </ListItemSection>
            <ListItemSection position="center">Edit space settings</ListItemSection>
          </MenuItem>
          <MenuItem keepMenuOpen>
            <ListItemSection position="left">
              <Icon name="favorite_20" />
            </ListItemSection>
            <ListItemSection position="center">Add to favorites</ListItemSection>
          </MenuItem>
          <MenuItem>
            <ListItemSection position="left">
              <Icon name="alert_20" />
            </ListItemSection>
            <ListItemSection position="center">Notifications</ListItemSection>
          </MenuItem>
          <MenuItem>
            <ListItemSection position="left">
              <Icon name="accessories_20" />
            </ListItemSection>
            <ListItemSection position="center">Add Integrations & Bots</ListItemSection>
          </MenuItem>
          <MenuItem>
            <ListItemSection position="left">
              <Icon name="stored-info_20" />
            </ListItemSection>
            <ListItemSection position="center">View space policy</ListItemSection>
          </MenuItem>
          <MenuItem keepMenuOpen>
            <ListItemSection position="left">
              <Icon name="archive_20" />
            </ListItemSection>
            <ListItemSection position="center">Archive space</ListItemSection>
          </MenuItem>
          <MenuItem keepMenuOpen>
            <ListItemSection position="left">
              <Icon name="cancel_20" />
            </ListItemSection>
            <ListItemSection position="center">Remove space from team</ListItemSection>
          </MenuItem>
          <MenuItem>
            <ListItemSection position="left">
              <Icon name="exit-room_20" />
            </ListItemSection>
            <ListItemSection position="center">Leave space</ListItemSection>
          </MenuItem>
        </Menu>
      </MenuOverlay>
    );
  }
}

// angular/src/lib/menu/examples/custom-menu-items.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-menu-custom-menu-item',
  template: `
    <button md-button aria-label="Show Menu" [mdMenuTriggerFor]="testMenu">Show Customized MenuItems</button>

    <md-menu #testMenu>
      <md-menu-content>Content</md-menu-content>
      <md-menu-item>
        <md-list-item-section position="left">
          <md-icon name="icon-edit_20"></md-icon>
        </md-list-item-section>
        <md-list-item-section position="center">
          Edit space settings
        </md-list-item-section>
      </md-menu-item>
      <md-menu-item>
        <md-list-item-section position="left">
          <md-icon name="icon-favorite_20"></md-icon>
        </md-list-item-section>
        <md-list-item-section position="center">
          Add to favorites
        </md-list-item-section>
      </md-menu-item>
      <md-menu-item>
        <md-list-item-section position="left">
          <md-icon name="icon-alert_20"></md-icon>
        </md-list-item-section>
        <md-list-item-section position="center">
          Notifications
        </md-list-item-section>
      </md-menu-item>
      <md-menu-item>
        <md-list-item-section position="left">
          <md-icon name="icon-accessories_20"></md-icon>
        </md-list-item-section>
        <md-list-item-section position="center">
          Add Integrations & Bots
        </md-list-item-section>
      </md-menu-item>
      <md-menu-item>
        <md-list-item-section position="left">
          <md-icon name="icon-info_20"></md-icon>
        </md-list-item-section>
        <md-list-item-section position="center">
          View space policy
        </md-list-item-section>
      </md-menu-item>
      <md-menu-item>
        <md-list-item-section position="left">
          <md-icon name="icon-archive_20"></md-icon>
        </md-list-item-section>
        <md-list-item-section position="center">
          Archive space
        </md-list-item-section>
      </md-menu-item>
      <md-menu-item>
        <md-list-item-section position="left">
          <md-icon name="icon-cancel_20"></md-icon>
        </md-list-item-section>
        <md-list-item-section position="center">
          Remove space from team
        </md-list-item-section>
      </md-menu-item>
      <md-menu-item>
        <md-list-item-section position="left">
          <md-icon name="icon-exit-room_20"></md-icon>
        </md-list-item-section>
        <md-list-item-section position="center">
          Leave space
        </md-list-item-section>
      </md-menu-item>
    </md-menu>
  `,
})
export class ExampleMenuCustomMenuItemComponent {}
