// angular/src/lib/topbar/examples/blue.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-topbar-blue',
  template: `
    <header md-top-bar color="blue">
      <ng-container
        *ngTemplateOutlet="brand"
        ngProjectAs="brand"
      ></ng-container>
      <md-top-bar-nav>
        <ng-container *ngTemplateOutlet="list"></ng-container>
      </md-top-bar-nav>
      <md-top-bar-right>
        <div class="md-top-bar__user"></div>
        <div class="md-top-bar__logged-out">
          <a href="javascript:void(0)">Log In</a>
          <button md-button color="blue" aria-label="myAriaLabel">
            Button
          </button>
        </div>
      </md-top-bar-right>
      <md-top-bar-mobile [shouldCloseOnClick]="false">
        <ng-container
          *ngTemplateOutlet="brand"
          ngProjectAs="brand"
        ></ng-container>
        <ng-container *ngTemplateOutlet="list"></ng-container>
      </md-top-bar-mobile>
    </header>

    <ng-template #brand>
      <a
        href="javascript:void(0)"
        md-top-bar-brand
        title="Momentum UI"
        icon="icon-cisco-logo"
      ></a>
    </ng-template>

    <ng-template #list>
      <a md-list-item link="javascript:void(0)" [active]="true">Develop</a>
      <a md-list-item link="javascript:void(0)">Styles</a>
      <a md-list-item link="javascript:void(0)">Layout</a>
      <a md-list-item link="javascript:void(0)">Navigation</a>
    </ng-template>
  `,
})
export class ExampleTopbarBlueComponent {}

// vue/src/lib/topbar/examples/blue.vue
<template>
  <md-topbar
    color="blue"
  >
    <md-topbar-nav>
      <md-list-item>Develop</md-list-item>
      <md-list-item>Styles</md-list-item>
      <md-list-item>Layout</md-list-item>
      <md-list-item>Navigation</md-list-item>
    </md-topbar-nav>
    <md-topbar-right>
      <div class="md-top-bar__user" />
      <div class="md-top-bar__logged-out">
        <a href="javascript:void(0)">Log In</a>
        <md-button color="blue" ariaLabel="myAriaLabel">
          Button
        </md-button>
      </div>
    </md-topbar-right>
    <md-topbar-mobile :shouldCloseOnClick="false">
      <template v-slot:brand>
        <a
          href="javascript:void(0)"
          title="Momentum UI"
        >
          <md-icon name="cisco-logo" :size="32" />
        </a>
      </template>
      <md-list-item>Develop</md-list-item>
      <md-list-item>Styles</md-list-item>
      <md-list-item>Layout</md-list-item>
      <md-list-item>Navigation</md-list-item>

    </md-topbar-mobile>
    
    <template v-slot:brand>
      <a
        href="javascript:void(0)"
        title="Momentum UI"
      >
        <md-icon name="cisco-logo" :size="32" />
      </a>
    </template>
  </md-topbar>
</template>

<script>
export default {
  name: 'ExampleTopbarBlue',
};
</script>
