// react/src/lib/Alert/examples/Error.js
import React from 'react';
import {
  AlertContainer,
  Button
} from '@collab-ui/react';
export default class AlertError extends React.PureComponent {
  state = {
    alertMessage: 'Who\'s awesome?  You are!'
  }
  render() {
    let alertContainer;
    return (
      <section>
        <div>
          <div className='row'>
            <br />
            <Button
              ariaLabel='Click to Open'
              onClick={() => alertContainer.error(
                'Alert',
                this.state.alertMessage,
                () => alert('onHide info'),
                { ariaLabel: 'Close Alert' }
              )}
              children='Error'
              color='primary'
            />
          </div>
        </div>
        <br />
        <AlertContainer
          ref={ref => alertContainer = ref}
          orderNewest={false}
        />
      </section>
    );
  }
}

// angular/src/lib/alert/examples/error.component.ts
import { Component } from '@angular/core';
import { AlertService } from '@collab-ui/angular';

@Component({
  selector: 'example-alert-error',
  template: `
    <button md-button (click)="onClick()" aria-label="Click to Open">
      Error
    </button>
  `,
})
export class ExampleAlertErrorComponent {
  constructor(private alertService: AlertService) {}

  onClick() {
    this.alertService.error('Error', 'Who\'s awesome?  You are!', {
      ariaLabel: 'Close Alert',
      orderNewest: false,
      onHide: () => console.info('onHide info'),
    });
  }
}
