// react/src/docs/containers/Playground/index.js
import React from 'react';
import Header from '../Header';
import SampleComponent from './insertExampleHere';

const Playground = () => {
  return (
    <div data-docs-overview="docs-overview">
      <Header
        title="Playground"
        description="Use this page to develop and test components for the toolkit."
        hero
        color="#00B387"
        textColor="light"
      />
      <article className="row copy-spacing">
        <div className="docs-container">
          <SampleComponent />
        </div>
      </article>
    </div>
  );
};

export default Playground;

// core/docs/app/playground/playground.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { colors } from '../../../data/colors';

@Component({
  selector: 'docs-playground',
  templateUrl: './playground.component.html',
  styleUrls: ['./playground.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class PlaygroundComponent implements OnInit {
  public title = 'Playground';
  public description = 'Use this page to develop and test components for the toolkit.';

  constructor() { }

  ngOnInit() {
  }
}

<docs-header [title]="title" [description]="description" hero="true"></docs-header>
<article class="row copy-spacing">
    <div class="docs-container">

      <!-- Test HTML goes Here -->

    </div>
  </article>
