// vue/src/lib/popover/examples/offset.vue
<template>
  <div class="docs-example docs-example--spacing">
    <md-popover
      direction="top-center"
      :isContained="true"
      :targetOffset="{ vertical: 20 }"
    >
      <md-button ariaLabel="offset" >offset</md-button>
      <span slot="content" style="padding: 10px">Offset</span>
    </md-popover>
  </div>
</template>

<script>
export default {
  name: 'ExamplePopoverOffset',
};
</script>

// react/src/lib/Popover/examples/Offset.js
import React from 'react';
 import {
  Button,
  Popover
} from '@collab-ui/react';
 export default function PopoverOffset() {
  const contentOffset = (
    <span key="1" style={{ padding: '10px'}}>Offset</span>
  );
  return (
    <div className="docs-example docs-example--spacing">
      <Popover
        content={contentOffset}
        direction={'top-center'}
        targetOffset={{ vertical: 20 }}
      >
        <Button children='offset' ariaLabel='offset' />
      </Popover>
    </div>
  );
}
