// vue/src/lib/input-error/index.vue
<template>
  <div class="md-input__messages" role="alert">
    <div class="message">{{ error }}</div>
  </div>
</template>

<script>
export default {
  name: 'md-input-error',

  props: {
    /** @prop Error message for InputError component */
    error: {
      type: String,
      required: true
    }
  }
};
</script>

// react/src/lib/InputError/index.js
/** @component input */

import React from 'react';
import PropTypes from 'prop-types';

/** Input Error with required error */
const InputError = ({ error }) => {
  return (
    <div className="md-input__messages" role="alert">
      <div className="message">{error}</div>
    </div>
  );
};

InputError.propTypes = {
  /** @prop Error message for InputError component */
  error: PropTypes.string.isRequired,
};

InputError.displayName = 'InputError';

export default InputError;
