// react/package/src/lib/Popover/examples/Contained.js
import React from 'react';
 import {
  Button,
  Popover
} from '@momentum-ui/react';
 export default function PopoverContained() {
  const tall = (
    <span key="1" style={{ height: '3000px' }}>Popover(height: 3000px)</span>
  );
  return (
    <Popover
      isContained
      content={tall}
      direction={'bottom-center'}
      popoverTrigger={'Click'}
    >
      <Button id='contained' children='Tall' ariaLabel='Tall' />
    </Popover>
  );
}

// vue/src/lib/popover/examples/contained.vue
<template>
  <div class="docs-example docs-example--spacing">
    <md-popover
      isContained
      direction="bottom-center"
      popoverTrigger="Click"
    >
      <md-button ariaLabel="Tall" >Tall</md-button>
      <span slot="content" style="height: 3000px">Popover(height: 3000px)</span>
    </md-popover>
  </div>
</template>

<script>
export default {
  name: 'ExamplePopoverContained',
};
</script>
