// react/src/lib/Popover/examples/Delay.js
import React from 'react';
 import {
  Button,
  Popover,
} from '@momentum-ui/react';
 export default function PopOverDelay() {
    const contentDelay = (
      <span key="1" style={{ padding: '10px'}}>Delayed</span>
    );
    return (
      <div className="docs-example docs-example--spacing">
        <Popover
          content={contentDelay}
          delay={500}
        >
          <Button children='Hover with Delay' ariaLabel='Hover with Delay' />
        </Popover>
      </div>
    );
}

// vue/src/lib/popover/examples/delay.vue
<template>
  <div class="docs-example docs-example--spacing">
    <md-popover
      delay="500"
    >
      <md-button ariaLabel="Hover with Delay" >Hover with Delay</md-button>
      <span slot="content" style="padding: 10px">Delayed</span>
    </md-popover>
  </div>
</template>

<script>
export default {
  name: 'ExamplePopoverDelay',
};
</script>
