// react/src/lib/Popover/examples/Direction.js
import React from 'react';
 import {
  Button,
  Popover
} from '@momentum-ui/react';
 export default function PopOverDirection() {
    const content = (
    <span key="1" style={{ padding: '10px'}}>right-center</span>
  );
  return (
    <div className="docs-example docs-example--spacing">
      <Popover
        content={content}
        direction={'right-center'}
      >
        <Button id='direction' children='Direction' ariaLabel='Direction' />
      </Popover>
    </div>
  );
}

// vue/src/lib/popover/examples/direction.vue
<template>
  <div class="docs-example docs-example--spacing">
    <md-popover
      direction="right-center"
    >
      <md-button ariaLabel="Direction" >Direction</md-button>
      <span slot="content" style="padding: 10px">right-center</span>
    </md-popover>
  </div>
</template>

<script>
export default {
  name: 'ExamplePopoverDirection',
};
</script>
