// angular/src/lib/alert-call/device-list-call.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { ListItemComponent } from '@collab-ui/angular/list-item';
import uniqueId from 'lodash-es/uniqueId';

export type AlertCallDeviceType = '' | 'device';

export class AlertCallDevice {
  id?: string = uniqueId('cui-device-list-item-');
  name: string;
  value?: string;
  type?: AlertCallDeviceType;
  title?: string;
}

@Component({
  selector: 'cui-device-list-call',
  template: `
    <cui-list (select)="onSelect($event)">
      <cui-list-item-header cuiRemoveHost [header]="header"></cui-list-item-header>
      <div cui-list-item *ngFor="let device of devices; index as i"
        [value]="device.value"
        [title]="device.title || device.name"
      >
        <cui-list-item-section position="left">
          <ng-container [ngSwitch]="device.type">
            <cui-icon *ngSwitchCase="'device'" name="spark-board_20"></cui-icon>
            <cui-icon *ngSwitchDefault name="laptop_20"></cui-icon>
          </ng-container>
        </cui-list-item-section>
        <cui-list-item-section position="center">
          <div class="cui-list-item__header">
            {{ device.name }}
          </div>
        </cui-list-item-section>
        <cui-list-item-section position="right">
          <cui-icon *ngIf="i === selectedIndex || device.id === selectedIndex" name="check_20" color="blue"></cui-icon>
        </cui-list-item-section>
      </div>
    </cui-list>
  `,
})

export class DeviceListCallComponent {
  /** Default Index Value selected | null */
  @Input() defaultSelected: number | string;
  /** Required list of devices to show in list */
  @Input() devices: AlertCallDevice[];
  /** ListItem header */
  @Input() header: string;

  @Output() readonly select: EventEmitter<ListItemComponent> = new EventEmitter<ListItemComponent>();

  selectedIndex: number | string = this.defaultSelected;

  onSelect(listItem: ListItemComponent) {
    console.log(listItem);
    this.selectedIndex = listItem.id;
    this.select.emit(listItem);
  }
}

// react/src/lib/DeviceListCall/index.js
import React from 'react';
import PropTypes from 'prop-types';
import omit from 'lodash/omit';
import { UIDConsumer } from 'react-uid';
import {
  Icon,
  List,
  ListItem,
  ListItemHeader,
  ListItemSection,
} from '@collab-ui/react';

class DeviceListCall extends React.PureComponent {
  state = {
    selectedIndex: this.props.defaultSelected,
  };

  handleSelect = (e, opts) => {
    const { onSelect } = this.props;
    const { value, eventKey } = opts;

    e.preventDefault();
    return this.setState({
      selectedIndex: eventKey
    },
    () => (
      onSelect && onSelect(e, { eventKey, value })
    ));
  }

  render() {
    const {
      className,
      devices,
      header,
      ...props
    } = this.props;
    const { selectedIndex } = this.state;

    const otherProps = omit({...props}, [
      'defaultSelected',
      'onSelect'
    ]);

    const getLeftSection = deviceType => {
      switch(deviceType) {
        case 'device': return <Icon name='spark-board_20' />;
        default: return <Icon name='laptop_20'/>;
      }
    };

    const getRightSection = (uid, idx) => {
      if(!isNaN(selectedIndex)) {
        if (idx === selectedIndex) {
          return <Icon name='check_20' color='blue-50'/>;
        }
      } else if (uid === selectedIndex) {
        return <Icon name='check_20' color='blue-50'/>;
      }
    };

    return (
      <List
        className={className}
        onSelect={this.handleSelect}
        active={selectedIndex}
        {...otherProps}
      >
        <ListItemHeader header={header} />
        {
          devices.map(({
            eventKey,
            id,
            name,
            title,
            type,
            value,
            ...deviceProps
          }, idx) => (
              <UIDConsumer name={uid => `cui-device-list-call-${uid}`} key={`device-${idx}`}>
                {uid => {
                  const uniqueKey = eventKey || id || uid;

                  return (
                    <ListItem
                      value={value}
                      label={name}
                      title={title || name}
                      id={uniqueKey}
                      {...deviceProps}
                    >
                      <ListItemSection position='left'>
                        {getLeftSection(type)}
                      </ListItemSection>
                      <ListItemSection position='center'>
                        <div className='cui-list-item__header'>
                          {name}
                        </div>
                      </ListItemSection>
                      <ListItemSection position='right'>
                        {getRightSection(uniqueKey, idx)}
                      </ListItemSection>
                    </ListItem>
                  );
                }}
              </UIDConsumer>
          ))
        }
      </List>
    );
  }
}

DeviceListCall.defaultProps = {
  className: '',
  defaultSelected: null,
  onSelect: null
};

DeviceListCall.propTypes = {
  /** HTML Class for associated input | '' */
  className: PropTypes.string,
  /** Default Index Value selected | null */
  defaultSelected: PropTypes.oneOfType([ PropTypes.number, PropTypes.string]),
  /** Required list of devices to show in list */
  devices: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string.isRequired,
      value: PropTypes.string,
      type: PropTypes.oneOf(['', 'device']),
      title: PropTypes.string
    })
  ).isRequired,
  /** ListItem header */
  header: PropTypes.string.isRequired,
  /** Optional function called when list item is selected | null */
  onSelect: PropTypes.func
};

DeviceListCall.displayName = 'DeviceListCall';

export default DeviceListCall;
