// react/examples/Modal/small.js
import React from 'react';
import {
  Button,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  Form
} from '@collab-ui/react';
export default class Default extends React.PureComponent {
  state = {
    showModal3: false,
    showModal4: false,
  }
  render() {
    return (
      <div className='row'>
        <div className="docs-example docs-example--spacing">
          <Button
            children='Small Modal'
            onClick={() => this.setState({showModal3: true})}
            ariaLabel='Open Modal'
            color='primary'
          />
          <Button
            children='Small Modal with Message'
            onClick={() => this.setState({showModal4: true})}
            ariaLabel='Open Modal'
            color='primary'
          />
          <Modal
            applicationId='app'
            onHide={() => this.setState({showModal3: false})}
            show={this.state.showModal3}
            ref={modal3 => this.modal3 = modal3}
            size='small'
            htmlId='modal3'
          >
            <ModalHeader
              headerLabel='Small Modal'
              showCloseButton
            />
            <ModalBody>
              <form ref={moform2 => this.moform2 = moform2} />
            </ModalBody>
            <ModalFooter>
              <Button
                children='Cancel'
                onClick={() => this.modal3.closeModal()}
                ariaLabel='Close Modal'
                color='default'
              />
              <Button
                children='OK'
                type='submit'
                onClick={(e) => {
                  e.preventDefault;
                  this.modal3.closeModal();
                }}
                ariaLabel='Submit Form'
                color='blue'
              />
            </ModalFooter>
          </Modal>
          <Modal
            applicationId='app'
            onHide={() => this.setState({showModal4: false})}
            show={this.state.showModal4}
            ref={modal4 => this.modal4 = modal4}
            size='small'
            htmlId='modal4'
          >
            <ModalHeader
              headerLabel='Small Modal'
              showCloseButton
              message='To create a meeting invite manually, copy and paste the meeting information and people into your email calendar invite.'
            />
            <ModalBody>
              <form ref={moform2 => this.moform2 = moform2} />
            </ModalBody>
            <ModalFooter>
              <Button
                children='Cancel'
                onClick={() => this.modal4.closeModal()}
                ariaLabel='Close Modal'
                color='default'
              />
              <Button
                children='OK'
                type='submit'
                onClick={(e) => {
                  e.preventDefault;
                  this.modal4.closeModal();
                }}
                ariaLabel='Submit Form'
                color='blue'
              />
            </ModalFooter>
          </Modal>
        </div>
      </div>
    );
  }
}

// vue/src/lib/modal/examples/small.vue
<template>
  <div class="row">
    <div class="docs-example docs-example--spacing">
      <md-button
        @click="() => showModal = true"
        ariaLabel="Open Modal"
        color="primary"
      >Small Modal</md-button>
      <md-button
        @click="() => showModal2 = true"
        ariaLabel="Open Modal 2"
        color="primary"
      >Small Modal with Message</md-button>
      <md-modal
        applicationId="app"
        @hide="showModal = false"
        :show="showModal"
        ref="modal1"
        htmlId="modal1"
        size="small"
      >
        <md-modal-header
          headerLabel="Small Modal"
          showCloseButton
        />
        <md-modal-body>
          <form ref="form1" />
        </md-modal-body>
        <md-modal-footer>
          <md-button
            @click="() => $refs.modal1.closeModal()"
            ariaLabel="Close Modal"
            color="default"
          >Cancel</md-button>
          <md-button
            type="submit"
            @click="() => $refs.modal1.closeModal()"
            ariaLabel="Submit Form"
            color="blue"
          >OK</md-button>
        </md-modal-footer>
      </md-modal>
      <md-modal
        applicationId="app"
        @hide="showModal2 = false"
        :show="showModal2"
        ref="modal2"
        htmlId="modal2"
        size="small"
      >
        <md-modal-header
          headerLabel="Small Modal"
          message="To create a meeting invite manually, copy and paste the meeting information and people into your email calendar invite."
          showCloseButton
        />
        <md-modal-body>
          <form ref="form1" />
        </md-modal-body>
        <md-modal-footer>
          <md-button
            @click="() => $refs.modal2.closeModal()"
            ariaLabel="Close Modal"
            color="default"
          >Cancel</md-button>
          <md-button
            type="submit"
            @click="() => $refs.modal2.closeModal()"
            ariaLabel="Submit Form"
            color="blue"
          >OK</md-button>
        </md-modal-footer>
      </md-modal>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ExampleModalSmall',

  data() {
    return {
      showModal: false,
      showModal2: false,
    }
  },
};
</script>
