// vue/src/lib/topbar/index.vue
<script>
export default {
  name: 'md-topbar',

  provide() {
    return {
      getBrandNode: () => this.$slots.brand,
    }
  },

  render(h) {
    const {
      anchor,
      color,
      fixed,
      icon,
      title,
      ...otherProps
    } = this.$props;

    const topBarClass = `md-top-bar`;
    const brandClass = `md-brand`;

    const brandNodeChildren = ([
      <div class={`${brandClass}__logo`} key={`${brandClass}__logo`}>
        {this.$slots.image || <i class={`icon ${icon}`} />}
      </div>,
      <div class={`${brandClass}__title`} key={`${brandClass}__title`}>
        {title}
      </div>
    ]);

    const getBrandAnchor = () => (
      this.$slots.brand || <a class={brandClass} href={anchor}>{brandNodeChildren}</a>
    );

    const brandNode = (
      <div class={`${topBarClass}__brand`}>
        {getBrandAnchor()}
      </div>
    );

    return (
      <div
        class={
          `${topBarClass}` +
          `${fixed && ` ${topBarClass}--fixed` || ''}` +
          `${color && ` ${topBarClass}--${color}` || ''}`
        }
        role='navigation'
        {...{props: otherProps}}
      >
        <div class={`${topBarClass}__container`}>
          {brandNode}
          {this.$slots.default}
        </div>
      </div>
    );
  },

  props: {
    /** @prop App Url/Link | null */
    anchor: String,
    /** @prop Topbar header color | '' */
    color: {
      type: String,
      default: ''
    },
    /** @prop Determines if Topbar is fixed to top | false */
    fixed: Boolean,
    /** @prop Icon class name | 'icon-cisco-logo' */
    icon: {
      type: String,
      default: 'icon-cisco-logo'
    },
    /** @prop Topbar title text | '' */
    title: {
      type: String,
      default: ''
    },
  }
};
</script>

// react/src/lib/Topbar/index.js
/** @component topbar */

import PropTypes from 'prop-types';
import React from 'react';
import { prefix } from '../utils/index';

class Topbar extends React.Component {
  render() {
    const {
      anchor,
      brandAnchorElement,
      children,
      className,
      color,
      fixed,
      icon,
      image,
      title,
      ...otherProps
    } = this.props;

    const topBarClass = `${prefix}-top-bar`;
    const brandClass = `${prefix}-brand`;

    const brandNodeChildren = ([
      <div className={`${brandClass}__logo`} key={`${brandClass}__logo`}>
        {
          image
            ? image
            : <i className={`icon ${icon}`} />
        }
      </div>,
      <div className={`${brandClass}__title`} key={`${brandClass}__title`}>
        {title}
      </div>
    ]);

    const getBrandAnchor = () => (
      brandAnchorElement
        ? React.cloneElement(
            brandAnchorElement,
            {
              className:
                `${brandClass}` +
                `${(brandAnchorElement.props.className && ` ${brandAnchorElement.props.className}`) || ''}`,
            },
            brandNodeChildren
          )
        : <a className={brandClass} href={anchor}>
            {brandNodeChildren}
          </a>
    );

    const brandNode = (
      <div className={`${topBarClass}__brand`}>
        {getBrandAnchor()}
      </div>
    );

    const injectChildren = React.Children.map(children, child => {
      if (child && (child.type.displayName === 'TopbarMobile') && (!child.props.brandNode)) {
        return React.cloneElement(child, {
          brandNode
        });
      } else {
        return child;
      }
    });

    return (
      <div
        className={
          `${topBarClass}` +
          `${fixed && ` ${topBarClass}--fixed` || ''}` +
          `${color && ` ${topBarClass}--${color}` || ''}` +
          `${className && ` ${className}` || ''}`
        }
        role='navigation'
        {...otherProps}
      >
        <div className={`${topBarClass}__container`}>
          {brandNode}
          {injectChildren}
        </div>
      </div>
    );
  }
}

Topbar.propTypes = {
  /** @prop App Url/Link | null */
  anchor: PropTypes.string,
  /** @prop Custom Node to wrap | null */
  brandAnchorElement: PropTypes.element,
  /** @prop Children nodes to render inside of Topbar | null */
  children: PropTypes.node,
  /** @prop Optional CSS class string | '' */
  className: PropTypes.string,
  /** @prop Topbar header color | '' */
  color: PropTypes.string,
  /** @prop Determines if Topbar is fixed to top | false */
  fixed: PropTypes.bool,
  /** @prop Icon class name | 'icon-cisco-logo' */
  icon: PropTypes.string,
  /** @prop Image node | null */
  image: PropTypes.node,
  /** @prop Topbar title text | '' */
  title: PropTypes.string,
};

Topbar.defaultProps = {
  anchor: null,
  brandAnchorElement: null,
  children: null,
  className: '',
  color: 'dark',
  fixed: false,
  icon: 'icon-cisco-logo',
  image: null,
  title: '',
};

Topbar.displayName = 'Topbar';

export default Topbar;
