// vue/src/lib/input-section/index.vue
<template>
  <span :class="`md-input__${position}`">
    <slot></slot>
  </span>
</template>

<script>
export default {
  name: 'md-input-section',

  props: {
    /** @prop Determine the InputSection's position | 'before' */
    position: {
      type: String,
      default: 'before',
      validator: value => ['before', 'after'].indexOf(value) !== -1
    },
  }
};
</script>

// angular/src/lib/input-section/input-section.component.ts
import {
  Component,
  HostBinding,
  Input,
} from '@angular/core';

export type InputSectionType = 'before' | 'after';

@Component({
  selector: 'md-input-section',
  template: `
    <ng-content></ng-content>
  `,
  styles: []
})

export class InputSectionComponent {
  /** @prop Determine the InputSection's position | 'before' */
  @Input() public position: InputSectionType = 'before';
  /** @prop Optional css class name | '' */
  @Input() public className: string;

  @HostBinding('class') get _class(): string {
    return (
      `md-input__${this.position || 'before'}` +
      `${this.className ? ` ${this.className}` : ''}`
    );
  }
}
