// angular/src/lib/slider/slider-pointer.component.ts
/** @component slider-pointer */

import {
  Component,
  ElementRef,
  EventEmitter,
  HostBinding,
  Inject,
  Input,
  Output,
} from '@angular/core';
import { DOCUMENT } from '@angular/common';

export interface SliderPointerChange {
  from?: number;
  to?: number;
  direction: number;
  isKeyBoard: boolean;
}

@Component({
  selector: 'md-slider-pointer',
  template: ``,
  host: {
    class: 'md-slider__pointer',
    role: 'button',
    tabindex: '0',
    '(keydown)': 'onKeydown($event)',
    '(mousedown)': 'onMousedown($event)',
    '(touchstart)': 'onTouchstart($event)',
    '(touchmove)': 'onTouchmove($event)',
  },
})
export class SliderPointerComponent {
  private _previousPosition: number;
  private _document: Document;

  /** @option Set Slider Pointer's position | 0 */
  @Input() position: number = 0;

  /** Event emitted when user moves the Slider Pointer */
  @Output() readonly move: EventEmitter<SliderPointerChange> = new EventEmitter<
    SliderPointerChange
  >();

  @HostBinding('style.left.%') get left(): number {
    return this.position;
  }

  constructor(
    private elementRef: ElementRef,
    @Inject(DOCUMENT) _document: any
  ) {
    this._document = _document;
  }

  getDirections(currentPos: number) {
    if (currentPos > this._previousPosition) {
      return 1;
    }
    return -1;
  }

  onKeydown(event: KeyboardEvent) {
    switch (event.code) {
      case 'ArrowUp':
      case 'ArrowRight':
        this.move.emit({
          direction: 1,
          isKeyBoard: true,
        });
        event.preventDefault();
        break;

      case 'ArrowDown':
      case 'ArrowLeft':
        this.move.emit({
          direction: -1,
          isKeyBoard: true,
        });
        event.preventDefault();
        break;
    }
  }

  onMousedown(event: MouseEvent) {
    this._document.addEventListener('mousemove', this.onMousemove);
    this._document.addEventListener('mouseup', this.onMouseup);

    this._previousPosition = event.clientX;
  }

  onMousemove = (event: MouseEvent) => {
    const xPos = event.clientX;
    const direction = this.getDirections(xPos);

    this.move.emit({
      from: this.elementRef.nativeElement.getBoundingClientRect().left,
      to: xPos,
      direction: direction,
      isKeyBoard: false,
    });
  }

  onMouseup = (_: MouseEvent) => {
    this._document.removeEventListener('mousemove', this.onMousemove);
    this._document.removeEventListener('mouseup', this.onMouseup);
  }

  onTouchstart(event: TouchEvent) {
    this._previousPosition = event.touches[0].clientX;
  }

  onTouchmove(event: TouchEvent) {
    const xPos = event.touches[0].clientX;
    const direction = this.getDirections(xPos);

    this.move.emit({
      from: this.elementRef.nativeElement.getBoundingClientRect().left,
      to: xPos,
      direction: direction,
      isKeyBoard: false,
    });
  }
}

// vue/src/lib/slider-pointer/index.vue
<template>
  <div
    class='md-slider__pointer'
    @mousedown="this.onMouseDown"
    @touchstart="this.onMouseDown($event, true)"
    @touchmove="this.onMouseDown($event, true)"
    @keydown="this.onKeyDown"
    role="button"
    tabindex="0"
    :style="{left: `calc(${position}%`}"
    ref="sliderRef"
  />
</template>

<script>
export default {
  name: 'md-slider-pointer',

  data() {
    return {
      previousPosition: null
    }
  },

  props: {
    /** Set Slider Pointer's position | 0 */
    position: {
      type: Number,
      default: 0
    },
  },

  methods: {
    getDirections(currentPos) {
      const { previousPosition } = this.$data;
      if (currentPos > previousPosition) {
        return 1;
      }
      return -1;
    },

    getPosition(event, isTouch) {
      return isTouch ? event.touches[0].clientX : event.clientX;
    },

    onMouseDown(event, isTouch = false) {
      if (!isTouch) {
        document.addEventListener('mousemove', this.onMouseMove);
        document.addEventListener('mouseup', this.onMouseUp);
      }

      this.previousPosition = this.getPosition(event, isTouch);
    },

    onMouseUp() {
      document.removeEventListener('mousemove', this.onMouseMove);
      document.removeEventListener('mouseup', this.onMouseUp);
    },

    onMouseMove(event, isTouch = false) {
      const xPos = this.getPosition(event, isTouch);
      const direction = this.getDirections(xPos);

      this.$emit('move', {
        from: this.$refs.sliderRef.getBoundingClientRect().x,
        to: xPos,
        direction,
        isKeyBoard: false
      });
    },

    onKeyDown(event) {
      const KEYS = {
        LEFT: 37,
        UP: 38,
        RIGHT: 39,
        DOWN: 40
      };

      switch (event.which || event.keyCode || event.charCode) {
        case KEYS.UP:
        case KEYS.RIGHT:
          this.$emit('move', {
            isKeyBoard: true,
            direction: 1
          });
          event.preventDefault();
          break;

        case KEYS.DOWN:
        case KEYS.LEFT:
          this.$emit('move', {
            isKeyBoard: true,
            direction: -1
          });
          event.preventDefault();
          break;
      }
    }
  },
};
</script>
