// react/src/lib/Input/examples/Disabled.js
import React from 'react';
import { Input } from '@momentum-ui/react';
export default function InputDisabled() {
  return (
    <Input
      name='inputDisabled'
      label='Disabled Input'
      htmlId='inputDisabled'
      inputSize='small-5'
      value='Disabled Text'
      disabled
    />
  );
}

// angular/src/lib/input/examples/disabled.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-input-disabled',
  template: `
    <md-input-group
      label="Disabled Input"
      inputSize="small-5"
    >
      <input
        mdInput
        disabled
        value='Disabled'
      />
    </md-input-group>
  `,
})

export class ExampleInputDisabledComponent {}
