// react/src/lib/Input/examples/HelpText.js
import React from 'react';
import { Input } from '@momentum-ui/react';
export default function InputHelpText() {
  return (
    <div className='row'>
      <Input
        name='inputHelpText'
        label='Help Text Input'
        htmlId='inputHelpText'
        inputSize='small-5'
        inputHelpText='Help Text'
      />
    </div>
  );
}

// angular/src/lib/input/examples/help-text.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-input-helptext',
  template: `
    <md-input
      [(ngModel)]="dataModel"
      inputSize="small-5"
      inputHelpText="Helper Text Here"
      label="Help Text Input"
    ></md-input>
  `,
})
export class ExampleInputHelpTextComponent {
  dataModel = 'Help Text';
}
