// react/examples/Input/secondarylabel.js
import React from 'react';
import { Input } from '@collab-ui/react';
export default function InputSecondary() {
  return (
    <div className='row'>
      <Input
        name='inputSecondaryLabel'
        label='Input with Secondary Label'
        htmlId='inputSecondaryLabel'
        inputSize='small-5'
        secondaryLabel='Secondary Label'
      />
    </div>
  );
}

// angular/src/lib/input/examples/secondary-label.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-input-secondary-label',
  template: `
    <md-input
      [(ngModel)]="dataModel"
      inputSize="small-5"
      secondaryLabel="Secondary Label"
    ></md-input>
  `,
})
export class ExampleInputSecondaryLabelComponent {
  dataModel = 'Text';
}
