// angular/src/lib/input-helper/input-helper.component.ts
import {
  Component,
  HostBinding,
  Input,
} from '@angular/core';

@Component({
  selector: 'md-input-helper',
  template: `<ng-content></ng-content>`,
  styles: [],
})

export class InputHelperComponent {
  /** @prop Optional css class name | '' */
  @Input() public className: string;

  @HostBinding('class') get _class(): string {
    return (
      `md-input__help-text` +
      `${this.className ? ` ${this.className}` : ''}`
    );
  }
}

// vue/src/lib/input-helper/index.vue
<template>
  <p :class="['md-input__help-text', className]">{{ message }}</p>
</template>

<script>
export default {
  name: 'md-input-helper',

  props: {
    /** @prop Optional css class name | '' */
    className: {
      type: String,
      default: ''
    },
    /** @prop Input help message for parent Input | null */
    message: {
      type: String,
      required: true
    }
  }
};
</script>
