// vue/src/lib/date-picker-week/index.vue
<script>
import { addDays, getStartOfWeek } from '../utils/dateUtils.js';
import moment from 'moment';

export default {
  name: 'md-date-picker-week',

  render(h) {
    const { day, month, ...otherProps } = this.$props;

    const renderDays = () => {
      const startOfWeek = getStartOfWeek(day.clone());

      const days = [0, 1, 2, 3, 4, 5, 6].map(offset => {
        const day = addDays(startOfWeek.clone(), offset);
        return (
          <md-date-picker-day
            key={offset}
            day={day}
            month={month}
            {...{props: otherProps}}
            {...{attrs: this.$attrs}}
          />
        );
      });

      return days;
    };

    return (
      <div class="md-datepicker__week">
        {renderDays()}
      </div>
    );
  },

  props: {
    /** Required day for the DatePickerWeek */
    day: {
      type: Object,
      required: true
    },
    /** Required month that the DatePickerDay displays */
    month: {
      type: Number,
      required: true
    },
  },
};
</script>

// web-components/src/components/datepicker/datepicker-week/DatePickerWeek.ts
import "@/components/datepicker/datepicker-day/DatePickerDay";
import { addDays, getStartOfWeek } from "@/utils/dateUtils";
import { customElement, html, LitElement, property } from "lit-element";
import DateTime from "luxon/src/datetime.js";

export namespace DatePickerWeek {}

@customElement("md-datepicker-week")
export class DatePickerWeek extends LitElement {
  @property() day: DateTime | undefined = undefined; // provided from upper component scope
  @property() month: DateTime | undefined = undefined; // provided from upper component scope
  @property({ type: Boolean }) selected = false; // not sure, seems moment related?
  // "otherprops" need to send to datepicker-day: { selected, focus, day, month }

  renderDays = () => {
    const startOfWeek = getStartOfWeek(this.day.clone());

    const days = [0, 1, 2, 3, 4, 5, 6].map(offset => {
      const offsetDay = addDays(startOfWeek.clone(), offset);
      return html`
        <md-datepicker-day day=${offsetDay}> </md-datepicker-day>
      `;
    });

    return days;
  };

  render() {
    return html`
      <div class="md-datepicker__week">
        ${this.renderDays()}
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "md-datepicker-week": DatePickerWeek;
  }
}
