// react/package/src/lib/ListItemSection/index.js
/** @component list-item */

import React from 'react';
import PropTypes from 'prop-types';

const ListItemSection = props => {
    const {
      children,
      className,
      position,
      ...otherProps
    } = props;

  return (
    <div
      className={
        `md-list-item__${position}` +
        `${(className && ` ${className}`) || ''}`
      }
      {...otherProps}
    >
      {children}
    </div>
  );
};

ListItemSection.propTypes = {
  /** @prop Children nodes to render inside ListItemSection | null */
  children: PropTypes.node,
  /** @prop Optional css class name | '' */
  className: PropTypes.string,
  /** @prop Determine the ListItemSection's position | 'center' */
  position: PropTypes.oneOf(['left', 'center', 'right', 'center-align']),
};

ListItemSection.defaultProps = {
  children: null,
  className: '',
  position: 'center',
};

ListItemSection.displayName = 'ListItemSection';

export default ListItemSection;

// vue/src/lib/list-item-section/index.vue
<template>
  <div
    :class="[
      `md-list-item__${position}`
    ]"
  >
    <slot></slot>
  </div>
</template>

<script>
export default {
  name: 'md-list-item-section',

  props: {
    /** @prop Determine the ListItemSection's position | 'center' */
    position: {
      type: String,
      default: 'center',
      validator: function (value) {
        return ['left', 'center', 'right', 'center-align'].indexOf(value) !== -1
      }
    },
  },

};
</script>
