// vue/src/lib/card/examples/clickable.vue
<template>
  <md-card @click="handleClick" style="width: 400px;">
    <md-card-section style="display: flex, justifyContent: space-between">
      <md-avatar src="http://react.collab-ui.com/barbara.png" style="display: flex" />
      <h4>Clickable</h4>
      <h6>Subtitle</h6>
    </md-card-section>
    <md-card-section full>
      <img alt="placeholder" src="https://place-hold.it/400x400" />
    </md-card-section>
    <md-card-section>
      Et netus et malesuada fames ac turpis egestas macecenas. Adipisccing at in tellus integer.
    </md-card-section>
    <md-card-section style="width: 100%, display: flex, justifyContent: flex-end, alignItems: baseline">
      <md-link href="" style="margin-right: 16px"> Link Text </md-link>
      <md-button
        ariaLabel="myAriaLabel"
      >Button</md-button>
    </md-card-section>
  </md-card>
</template>

<script>
export default {
  name: 'ExampleCardClickable',

  methods: {
    handleClick(e) {}
  },
};
</script>

// react/package/src/lib/Card/examples/Clickable.js
import React from 'react';
import { Avatar, Button, Card, CardSection, Link } from '@momentum-ui/react';
export default function CardClickable() {
	return (
		<Card onClick={()=>{}} style={{width: '300px'}}>
			<CardSection style={{display: 'flex', justifyContent: 'space-between'}}>
				<Avatar src="http://react.collab-ui.com/barbara.png" style={{display: 'flex'}} />
				<div style={{paddingLeft: '16px'}}>
					<h4>Clickable</h4>
					<h6>Subtitle</h6>
				</div>
			</CardSection>
			<CardSection full>
				<img alt="placeholder" src="https://place-hold.it/400x400" />
			</CardSection>
			<CardSection>
				Et netus et malesuada fames ac turpis egestas macecenas. Adipisccing at in tellus integer.
			</CardSection>
			<CardSection style={{width: "100%", display: "flex", justifyContent: "flex-end", alignItems: "baseline"}}>
				<Link href="" style={{marginRight: '16px',}}> Link Text </Link>
				<Button 
					children="Button" 
					ariaLabel="myAriaLabel" 
				/>
			</CardSection>
		</Card>
	);
}
