// react/src/docs/containers/Header/index.js
import React from 'react';
import PropTypes from 'prop-types';

export default class Header extends React.Component {
  static propTypes = {
    title: PropTypes.string.isRequired,
    description: PropTypes.string,
    hero: PropTypes.bool,
    textAlign: PropTypes.string,
    textColor: PropTypes.string,
    color: PropTypes.string,
  };

  static defaultProps = {
    description: '',
    hero: false,
    textAlign: '',
    textColor: '',
    color: '',
  };

  render() {
    const {
      title,
      description,
      hero,
      textAlign,
      textColor,
      color,
    } = this.props;

    const leadElement = () => {
      return description ? (
        <h3 className={hero ? 'hero__lead' : 'page-header__lead'}>
          {description}
        </h3>
      ) : (
        ''
      );
    };

    const titleElement = () => {
      return (
        <h1 className={hero ? 'hero__title' : 'page-header__title'}>{title}</h1>
      );
    };

    return (
      <div
        className={
          (hero
            ? hero === 'center' ? 'text-center' : 'hero hero--fluid'
            : 'page-header') +
          ' ' +
          (textAlign === 'left' ? 'page-header--left' : '') +
          ' ' +
          (textColor === 'light' ? 'hero--dark' : '')
        }
        style={{ backgroundColor: color }}
      >
        <div
          className={
            'page-header__container ' +
            (textAlign === 'left' ? 'page-header--left' : '')
          }
        >
          {titleElement()}
          {leadElement()}
        </div>
      </div>
    );
  }
}

// core/docs/app/shared/header/header.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'docs-header',
  template: `
  <div
    [ngClass]="{'page-header': !hero,
    'hero hero--fluid': hero,
    'text-center': hero === 'center',
    'page-header--left': textAlign === 'left',
    'hero--dark': textColor === 'light'}" [style.background-image]="'url(' + image + ')'" [style.background-color]="color">
    <div class="page-header__container" [ngClass]="{'page-header--left': textAlign === 'left'}">
      <h1 [ngClass]="{'page-header__title': !hero,'hero__title': hero}">{{title}}</h1>
      <h3 [ngClass]="{'page-header__lead': !hero,'hero__lead': hero}" [innerHTML]="description | keepHtml" *ngIf="description"></h3>
    </div>
  </div>
    `,
  styles: []
})
export class HeaderComponent {
  @Input() public title: string;
  @Input() public description: string;
  @Input() public hero?: any;
  @Input() public textAlign?: string;
  @Input() public image?: string;
  @Input() public color?: string;
  @Input() public textColor?: string;
}
