// vue/src/lib/time-picker/time-picker-dropdown/index.vue
<template>
  <div
    class="md-timepicker__dropdown-container"
    @click="handleClick"
  >
    <div class="md-timepicker__dropdown">
      <div class="inline-flex"><slot></slot></div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'md-time-picker-dropdown',

  methods: {
    handleClick(e) {
      e.stopPropagation();
    }
  },
};
</script>

// angular/src/lib/time-picker/time-picker-dropdown.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'md-time-picker-dropdown',
  template: `
    <div class='md-timepicker__dropdown'>
      <div class="inline-flex">
        <ng-content></ng-content>
      </div>
    </div>
  `,
  host: {
    class: 'md-timepicker__dropdown-container'
  }
})
export class TimePickerDropdownComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
