// angular/src/lib/button-group/examples/justified-false.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-button-group-justified-false',
  template: `
    <md-button-group [justified]="false">
      <button md-button aria-label="1">one</button>
      <button md-button aria-label="2" [disabled]="true">two</button>
      <button md-button aria-label="3">three</button>
    </md-button-group>
  `,
})
export class ExampleButtonGroupJustifiedFalseComponent {
  constructor() {}
}

// vue/src/lib/button-group/examples/justified-false.vue
<template>
  <md-button-group :justified="false" :highlightSelected="false">
    <md-button :ariaLabel="1" >one</md-button>
    <md-button :ariaLabel="2" :disabled="true">two</md-button>
    <md-button :ariaLabel="3">three</md-button>
  </md-button-group>
</template>

<script>
export default {
  name: 'ExampleButtonGroupJustifiedFalse',
};
</script>
