// react/package/src/lib/ButtonGroup/examples/Pill.js
import React from 'react';
 import { Button, ButtonGroup, Icon } from '@momentum-ui/react';
 export default class ButtonGroupPill extends React.PureComponent {
  render() {
    return(
      <div>
        <div className='columns small-4'>
          <ButtonGroup>
            <Button ariaLabel='left'><Icon name='icon-arrow-left_12' /></Button>
            <Button ariaLabel='right'><Icon name='icon-arrow-right_12' /></Button>
          </ButtonGroup>
        </div>
        <div className='columns small-4'>
          <ButtonGroup type='pill'>
            <Button ariaLabel='left'><Icon name='icon-flag_16' /></Button>
            <Button ariaLabel='right'><Icon name='icon-cancel_16' /></Button>
          </ButtonGroup>
        </div>
        <div className='columns small-4'>
          <ButtonGroup type='pill' pillWidth='60px'>
            <Button ariaLabel='left'><Icon name='icon-flag_16' /></Button>
          </ButtonGroup>
        </div>
      </div>
    );
  }
}

// vue/src/lib/button-group/examples/pill.vue
<template>
  <div>
    <div class='columns small-4'>
      <md-button-group>
        <md-button ariaLabel="left"><md-icon name="icon-arrow-left_12" /></md-button>
        <md-button ariaLabel="right"><md-icon name="icon-arrow-right_12" /></md-button>
      </md-button-group>
    </div>
    <div class='columns small-4'>
      <md-button-group type="pill">
        <md-button ariaLabel="left"><md-icon name="icon-flag_16" /></md-button>
        <md-button ariaLabel="right"><md-icon name="icon-cancel_16" /></md-button>
      </md-button-group>
    </div>
    <div class='columns small-4'>
      <md-button-group type="pill" pillWidth="60px">
        <md-button ariaLabel="left"><md-icon name="icon-flag_16" /></md-button>
      </md-button-group>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ExampleButtonGroupPill',
};
</script>
