// react/src/lib/Accordion/examples/PreSelectedOpen.js
import React from 'react';
import {
  Accordion,
  AccordionContent,
  AccordionGroup,
  AccordionHeader,
  ListItem,
} from '@momentum-ui/react';
export default class AccordionPreSelectedOpen extends React.Component {
  render() {
    return (
      <Accordion multipleVisible initialActive={[0]}>
        <AccordionGroup>
          <AccordionHeader>
            <div>Accordion 1</div>
          </AccordionHeader>
          <AccordionContent>
            <ListItem label="Content 1" />
          </AccordionContent>
        </AccordionGroup>
        <AccordionGroup>
          <AccordionHeader>
            <div>Accordion 2</div>
          </AccordionHeader>
          <AccordionContent>
            <ListItem label="Content 2" />
          </AccordionContent>
        </AccordionGroup>
      </Accordion>
    );
  }
}

// vue/src/lib/accordion/examples/pre-selected-open.vue
<template>
  <md-accordion multipleVisible :initialActive="[0]">
    <md-accordion-group>
      <md-accordion-header>
        <div>Accordion 1</div>
      </md-accordion-header>
      <md-accordion-content>
        <md-list-item label="Content 1" />
      </md-accordion-content>
    </md-accordion-group>
    <md-accordion-group>
      <md-accordion-header>
        <div>Accordion 2</div>
      </md-accordion-header>
      <md-accordion-content>
        <md-list-item label="Content 2" />
      </md-accordion-content>
    </md-accordion-group>
  </md-accordion>
</template>

<script>
export default {
  name: 'ExampleAccordionPreSelectedOpen',
};
</script>
