// angular/src/lib/alert-call/alert-call.component.ts
import {
  Component,
  EventEmitter,
  Input,
  Output,
  TemplateRef,
} from '@angular/core';

import { AlertCaller } from './alert-call-config';
import { AlertCallDevice } from './device-list-call.component';

// Used internally by the alert call service.
@Component({
  selector: 'cui-alert-call',
  template: `
    <div class="cui-alert__title">{{ title }}</div>
    <div class="cui-alert__caller">
      <ng-container *ngIf="avatar; else callerTemplate" [ngTemplateOutlet]="avatar"></ng-container>
      <div class="cui-alert__caller-title">{{ caller.title }}</div>
      <div class="cui-alert__caller-subtitle">{{ caller.alt }}</div>
    </div>
    <cui-device-list-call
      *ngIf="devices.length > 0"
      cuiRemoveHost
      [devices]="devices"
      [defaultSelected]="defaultSelectedDevice"
      [header]="deviceListHeader"
      (select)="onDeviceSelect($event)"
      ></cui-device-list-call>
    <div class="cui-alert--call--buttons">
      <button
        cui-button
        [attr.aria-label]="videoAriaLabel"
        [circle]="true"
        color="green"
        size="44"
        tabindex="0"
        (click)="onAnswerVideo()"
      >
        <cui-icon name="camera_24"></cui-icon>
      </button>
      <button
        *ngIf="answerVoiceButtonVisible"
        cui-button
        [attr.aria-label]="voiceAriaLabel"
        [circle]="true"
        color="green"
        size="44"
        tabindex="0"
        (click)="onAnswerVoice()"
      >
        <cui-icon name="handset_24"></cui-icon>
      </button>
      <button
        cui-button
        [attr.aria-label]="rejectAriaLabel"
        [circle]="true"
        color="red"
        size="44"
        tabindex="0"
        (click)="onReject()"
      >
        <cui-icon name="cancel_24"></cui-icon>
      </button>
    </div>

    <ng-template #callerTemplate>
      <ng-container [ngSwitch]="caller.type">
        <cui-avatar *ngSwitchCase="'number'" title="#" [alt]="caller.title" size="xlarge"></cui-avatar>
        <cui-avatar *ngSwitchCase="'device'" icon="spark-board_32" [alt]="caller.title" size="xlarge"></cui-avatar>
        <cui-avatar *ngSwitchDefault [title]="caller.title" [alt]="caller.title" size="xlarge"></cui-avatar>
      </ng-container>
    </ng-template>
  `,
  host: {
    'class': 'cui-alert cui-alert--call',
  }
})
export class AlertCallComponent {
  @Input() private key: string;
  @Input() answerVoiceButtonVisible: boolean;
  @Input() avatar: TemplateRef<any>;
  @Input() caller: AlertCaller;
  @Input() defaultSelectedDevice: number | string = 0;
  @Input() deviceListHeader: string = 'Device selection';
  @Input() devices: AlertCallDevice[] = [];
  @Input() rejectAriaLabel: string = 'reject call';
  @Input() title: string = '';
  @Input() videoAriaLabel: string = 'answer call with voice and video';
  @Input() voiceAriaLabel: string = 'answer call with voice only';

  @Output() readonly answerVideo: EventEmitter<string> = new EventEmitter<string>();
  @Output() readonly answerVoice: EventEmitter<string> = new EventEmitter<string>();
  @Output() readonly deviceSelect: EventEmitter<string> = new EventEmitter<string>();
  @Output() readonly reject: EventEmitter<string> = new EventEmitter<string>();

  onDeviceSelect(device: any): void {
    this.deviceSelect.emit(this.key);
  }

  onAnswerVideo(): void {
    this.answerVideo.emit(this.key);
  }

  onAnswerVoice(): void {
    this.answerVoice.emit(this.key);
  }

  onReject(): void {
    this.reject.emit(this.key);
  }
}

// react/src/lib/AlertCall/index.js
/** @component alert-call */
import React from 'react';
import PropTypes from 'prop-types';
import DeviceListCall from '../DeviceListCall';
import { UIDReset } from 'react-uid';
import {
  Avatar,
  Button,
  Icon
} from '@collab-ui/react';

const AlertCall = props => {
  const {
    avatar,
    caller,
    defaultSelectedDevice,
    deviceListHeader,
    devices,
    onAnswerShare,
    onAnswerVideo,
    onAnswerVoice,
    onDeviceSelect,
    onReject,
    rejectAriaLabel,
    shareAriaLabel,
    show,
    title,
    videoAriaLabel,
    voiceAriaLabel,
  } = props;

  const getAvatar = () => {
    if (avatar) {
      return avatar;
    } else {
      switch(caller.type) {
        case 'number': return <Avatar title='#' alt={caller.title} size='xlarge'/>;
        case 'device': return <Avatar icon={<Icon name='spark-board_32' />} alt={caller.title} size='xlarge'/>;
        default: return <Avatar title={caller.title} alt={caller.title} size='xlarge'/> ;
      }
    }
  };

  const getDeviceList = () => {
    return devices.length > 0 && (
      <DeviceListCall
        devices={devices}
        header={deviceListHeader}
        onSelect={onDeviceSelect}
        defaultSelected={defaultSelectedDevice}
      />
    );
  };

  return (
    show && (
      <div className='cui-alert cui-alert--call'>
        <div className='cui-alert__title'>
          {title}
        </div>
        <div className='cui-alert__caller'>
          {getAvatar()}
          <div className='cui-alert__caller-title'>
            {caller.title}
          </div>
          <div className='cui-alert__caller-subtitle'>
            {caller.alt}
          </div>
        </div>
        <UIDReset>
          {getDeviceList()}
        </UIDReset>
        <div className='cui-alert--call--buttons'>
          {onAnswerShare &&
            <Button
              children={<Icon name='share-screen_24'/>}
              onClick={onAnswerShare}
              ariaLabel={shareAriaLabel}
              color='blue'
              circle
              size={44}
            />
          }
          {onAnswerVideo &&
            <Button
              children={<Icon name='camera_24'/>}
              onClick={onAnswerVideo}
              ariaLabel={videoAriaLabel}
              color='green'
              circle
              size={44}
            />
          }
          {onAnswerVoice &&
            <Button
              children={<Icon name='handset_24'/>}
              onClick={onAnswerVoice}
              ariaLabel={voiceAriaLabel}
              color='green'
              circle
              size={44}
            />
          }
          <Button
            children={<Icon name='cancel_24'/>}
            onClick={onReject}
            ariaLabel={rejectAriaLabel}
            color='red'
            circle
            size={44}
          />
        </div>
      </div>
    )
  );
};

AlertCall.defaultProps = {
  avatar: null,
  caller: null,
  defaultSelectedDevice: 0,
  deviceListHeader: 'Device selection',
  devices: [],
  onAnswerShare: null,
  onAnswerVideo: null,
  onAnswerVoice: null,
  onDeviceSelect: null,
  onReject: null,
  rejectAriaLabel: 'reject call',
  shareAriaLabel: 'answer call with share',
  title: '',
  videoAriaLabel: 'answer call with video',
  voiceAriaLabel: 'answer call with voice',
};

AlertCall.propTypes = {
  /** @prop Optional avatar prop | null */
  avatar: PropTypes.node,
  /** @prop Required caller object */
  caller: PropTypes.shape({
    title: PropTypes.string.isRequired,
    alt: PropTypes.string,
    src: PropTypes.string,
    type: PropTypes.oneOf(['', 'number', 'device']),
  }).isRequired,
  /** @prop Optional default selected device by index value or eventKey | 0 */
  defaultSelectedDevice: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  /** @prop Optional header string for device selection list | "Device selection" */
  deviceListHeader: PropTypes.string,
  /** @prop Optional list of devices to answer call with | [] */
  devices: PropTypes.array,
  /** @prop Callback function invoked when the share button is clicked | null */
  onAnswerShare: PropTypes.func,
  /** @prop Callback function invoked when the video button is clicked | null */
  onAnswerVideo: PropTypes.func,
  /** @prop Callback function invoked when the handset button is clicked | null */
  onAnswerVoice: PropTypes.func,
  /** @prop Optional callback function when device is selected | null */
  onDeviceSelect: PropTypes.func,
  /** @prop Callback function invoked when the reject button is clicked | null */
  onReject: PropTypes.func,
  /** @prop Optional aria-label reject message | 'reject call' */
  rejectAriaLabel: PropTypes.string,
  /** @prop Optional aria-label share | 'answer call with share' */
  shareAriaLabel: PropTypes.string,
  /** @prop Required AlertCall visitibility setting */
  show: PropTypes.bool.isRequired,
  /** @prop Optional title of AlertCall | '' */
  title: PropTypes.string,
  /** @prop Optional aria-label video | 'answer call with video' */
  videoAriaLabel: PropTypes.string,
  /** @prop Optional aria-label voice | 'answer call with voice only' */
  voiceAriaLabel: PropTypes.string,
};

AlertCall.displayName = 'AlertCall';

export default AlertCall;
