// angular/src/lib/list-item-header/list-item-header.component.ts
import { Component, ElementRef, Input } from '@angular/core';

export type ListItemHeaderType = '' | 'space';

@Component({
  selector: 'md-list-item-header',
  template: `
    <div
      md-list-item
      class="md-list-item-header"
      [isReadOnly]="isReadOnly"
      [title]="getTitle()"
    >
      <md-list-item-section position="center">
        <div class="md-list-item__header">{{ header }}</div>
      </md-list-item-section>
      <md-list-item-section position="right">
        <ng-content></ng-content>
      </md-list-item-section>
    </div>
  `,
})

export class ListItemHeaderComponent {
  /** ListItem header text */
  @Input() header: string;
  /** HTML ID for associated input | '' */
  @Input() id: string = '';
  /** Determines if ListItemHeader is Clickable | true */
  @Input() isReadOnly: boolean = true;
  /** ListItem title | '' */
  @Input() title: string = '';
  /** ListItemHeader type variation | '' */
  @Input()
  get type(): ListItemHeaderType {
    return this._type;
  }
  set type(value: ListItemHeaderType) {
    this.elementRef.nativeElement.classList.remove(`md-list-item-header--${this._type}`);
    this.elementRef.nativeElement.classList.add(`md-list-item-header--${value}`);
    this._type = value;
  }

  private _type: ListItemHeaderType = '';

  constructor(private elementRef: ElementRef) {}

  getTitle(): string {
    return !this.title ? this.header : this.title;
  }
}

// vue/src/lib/list-item-header/index.vue
<template>
  <md-list-item
    :class="
      'md-list-item-header' +
      `${(type && ` md-list-item-header--${type}`) || ''}`
    "
    isReadOnly
    :id="getId"
    :title="getTitle"
    v-bind="$attrs"
  >
    <md-list-item-section key="child-0" position="center">
      <div class="md-list-item__header">
        {{ header }}
      </div>
    </md-list-item-section>
    <md-list-item-section key="child-1" position="right">
      <slot></slot><slot name="customAnchor"></slot>
    </md-list-item-section>
  </md-list-item>
</template>

<script>
import uniqueId from 'lodash/uniqueId';

export default {
  name: 'md-list-item-header',

  props: {
    /** @prop ListItem header text */
    header: {
      type: String,
      required: true
    },
    /** @prop HTML ID for associated input | '' */
    id: {
      type: String,
      default: ''
    },
    /** @prop Determines if ListItemHeader is Clickable | true */
    isReadOnly: {
      type: Boolean,
      default: true
    },
    /** @prop ListItem title | '' */
    title: {
      type: String,
      default: ''
    },
    /** @prop ListItemHeader type variation | '' */
    type: {
      type: String,
      default: '',
      validator: function (value) {
        return ['', 'space'].indexOf(value) !== -1
      }
    },
  },

  computed: {
    getId() {
      return this.id || uniqueId('md-space-list-item__header-');
    },

    getTitle() {
      return !this.title ? this.header : this.title;
    },
  },

};
</script>
