// vue/src/lib/button-group/examples/highlight-false.vue
<template>
  <md-button-group :justified="false" :highlightSelected="false">
    <md-button ariaLabel="Left" ><md-icon name="icon-arrow-left_12" /></md-button>
    <md-button ariaLabel="Today" :disabled="true">Today</md-button>
    <md-button ariaLabel="Right"><md-icon name="icon-arrow-right_12" /></md-button>
  </md-button-group>
</template>

<script>
export default {
  name: 'ExampleButtonGroupHighlightFalse',
};
</script>

// react/src/lib/ButtonGroup/examples/HighlightFalse.js
import React from 'react';
 import { Button, ButtonGroup, Icon } from '@momentum-ui/react';
 export default class ButtonGroupHiglightFalse extends React.PureComponent {
  render() {
    return(
      <ButtonGroup justified={false} highlightSelected={false}>
        <Button ariaLabel='Left'><Icon name='icon-arrow-left_12' /></Button>
        <Button ariaLabel='Today'>Today</Button>
        <Button ariaLabel='Right'><Icon name='icon-arrow-right_12' /></Button>
      </ButtonGroup>
    );
  }
}
