// vue/src/lib/button-group/examples/justified-false.vue
<template>
  <md-button-group :justified="false" :highlightSelected="false">
    <md-button :ariaLabel="1" >one</md-button>
    <md-button :ariaLabel="2" :disabled="true">two</md-button>
    <md-button :ariaLabel="3">three</md-button>
  </md-button-group>
</template>

<script>
export default {
  name: 'ExampleButtonGroupJustifiedFalse',
};
</script>

// react/src/lib/ButtonGroup/examples/JustifiedFalse.js
import React from 'react';
 import { Button, ButtonGroup } from '@momentum-ui/react';
 export default class ButtonGroupJustifiedFalse extends React.PureComponent {
  render() {
    return(
      <ButtonGroup justified={false}>
        <Button ariaLabel='1'>one</Button>
        <Button ariaLabel='2' disabled>two</Button>
        <Button ariaLabel='3'>three</Button>
      </ButtonGroup>
    );
  }
}
