// vue/src/lib/input-helper/index.vue
<template>
  <p :class="['md-input__help-text', className]">{{ message }}</p>
</template>

<script>
export default {
  name: 'md-input-helper',

  props: {
    /** @prop Optional css class name | '' */
    className: {
      type: String,
      default: ''
    },
    /** @prop Input help message for parent Input | null */
    message: {
      type: String,
      required: true
    }
  }
};
</script>

// react/src/lib/InputHelper/index.js
/** @component input */

import React from 'react';
import PropTypes from 'prop-types';

const InputHelper = ({ message, className }) => {
  return <p className={`md-input__help-text ${className}`}>{message}</p>;
};

InputHelper.propTypes = {
  /** @prop Optional css class name | '' */
  className: PropTypes.string,
  /** @prop Input help message for parent Input | null */
  message: PropTypes.string.isRequired
};

InputHelper.defaultProps = {
  className: '',
  message: null,
};

InputHelper.displayName = 'InputHelper';

export default InputHelper;
