// vue/src/lib/button-group/examples/highlight-false.vue
<template>
  <md-button-group :justified="false" :highlightSelected="false">
    <md-button ariaLabel="Left" ><md-icon name="icon-arrow-left_12" /></md-button>
    <md-button ariaLabel="Today" :disabled="true">Today</md-button>
    <md-button ariaLabel="Right"><md-icon name="icon-arrow-right_12" /></md-button>
  </md-button-group>
</template>

<script>
export default {
  name: 'ExampleButtonGroupHighlightFalse',
};
</script>

// angular/src/lib/button-group/examples/highlight-false.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'example-button-group-highlight-false',
  template: `
    <md-button-group [highlightSelected]="false">
      <button md-button aria-label="Left">
      <md-icon name="icon-arrow-left_12"></md-icon>
      </button>
      <button md-button aria-label="Today">Today</button>
      <button md-button aria-label="Right">
        <md-icon name="icon-arrow-right_12"></md-icon>
      </button>
    </md-button-group>
  `,
})
export class ExampleButtonGroupHighlightFalseComponent {
  constructor() {}
}
