// angular/src/lib/form/form-section.component.ts
/** @component form */

import { Component, Input } from '@angular/core';

@Component({
  selector: 'md-form-section',
  template: `
    <md-form-info [title]="title" [description]="description"></md-form-info>
    <md-form-content><ng-content></ng-content></md-form-content>
  `,
  host: {
    'class': 'md-form__section',
  }
})

export class FormSectionComponent {
  /** @prop Optional FormSection description | '' */
  @Input() description: string = '';
  /** @prop Optional FormSection title | null */
  @Input() title: string;
}

// react/src/lib/FormSection/index.js
/** @component form */

import React from 'react';
import PropTypes from 'prop-types';
import {
  FormInfo,
  FormContent,
} from '@momentum-ui/react';

const FormSection = props => {
  const { title, description, children } = props;

  return (
    <div className="md-form__section">
      <FormInfo title={title} description={description} />
      <FormContent>{children}</FormContent>
    </div>
  );
};

FormSection.propTypes = {
  /** @prop Children node to render inside FormSection | null */
  children: PropTypes.node,
  /** @prop Optional FormSection description | '' */
  description: PropTypes.string,
  /** @prop Optional FormSection title | null */
  title: PropTypes.string.isRequired
};

FormSection.defaultProps = {
  children: null,
  description: '',
  title: null,
};

FormSection.displayName = 'FormSection';

export default FormSection;
