// angular/src/lib/tabs/tab-header.component.ts
/** @component tab */

import { Component, Input } from '@angular/core';

@Component({
  selector: 'md-tab-header',
  template: `
    {{ heading }}
    <div *ngIf="subHeading">{{ subHeading }}</div>
  `,
  styles: [],
})
export class TabHeaderComponent {
  /** @prop TabHeader text */
  @Input() public heading: string;
  /** @prop Subheader text | '' */
  @Input() public subHeading: string = '';
}

// react/src/lib/TabHeader/index.js
import React from 'react';
import PropTypes from 'prop-types';

const TabHeader = props => {
  const { heading, subHeading } = props;

  return (
    //Element type requires by UI-Collab Style
    <cui-tab-heading>
      {heading}
      {subHeading && <div>{subHeading}</div>}
    </cui-tab-heading>
  );
};

TabHeader.propTypes = {
  /** @prop TabHeader text */
  heading: PropTypes.string.isRequired,
  /** @prop Subheader text | '' */
  subHeading: PropTypes.string,
};

TabHeader.defaultProps = {
  subHeading: '',
};

TabHeader.displayName = 'TabHeader';

export default TabHeader;
