// angular/src/docs/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'docs-root',
  template: `
    <div style="display: flex; flex-direction: column; min-height: 100vh;">
      <header md-top-bar color="light">
        <a
          routerLink="/"
          md-top-bar-brand
          [image]="logo"
          ngProjectAs="brand"
        ></a>
        <md-top-bar-nav>
          <a md-list-item routerLink="/kitchen-sink" [active]="true">Kitchen Sink</a>
          <a md-list-item routerLink="/playground">Playground</a>
        </md-top-bar-nav>
      </header>
      <main>
        <router-outlet></router-outlet>
      </main>
    </div>
  `,
})
export class AppComponent {
  logo = require('@momentum-ui/core/images/momentum/momentum-horiz-color.svg');
}

// react/src/app/App.js
import React from 'react';
import { Switch, Route, NavLink } from 'react-router-dom';
import Playground from './containers/Playground';
import KitchenSink from './containers/KitchenSink';
import {
  ListItem,
  Topbar,
  TopbarNav,
} from '@momentum-ui/react';

import logo from '@momentum-ui/core/images/momentum/momentum-horiz-color.svg';

const App = () => {
  const wordMark = <img src={logo} alt="Momentum Design" />;
  const navItems = (
    <>
      <ListItem
        customRefProp="innerRef"
        customAnchorNode={
          <NavLink to="/" activeClassName={'active'}>
            Kitchen Sink
          </NavLink>
        }
      />
      <ListItem
        customRefProp="innerRef"
        customAnchorNode={
          <NavLink to="/playground" activeClassName={'active'}>
            Playground
          </NavLink>
        }
      />
    </>
  );

  return (
    <div
      style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
      <Topbar color="light" image={wordMark} brandAnchorElement={<NavLink to="/" />}>
        <TopbarNav>{navItems}</TopbarNav>
      </Topbar>
      <main>
        <Switch>
          <Route key={'Playground'} path="/playground" component={Playground} />
          <Route component={KitchenSink} />
        </Switch>
      </main>
    </div>
  );
};

export default App;
