// react/package/src/lib/ListItem/index.js
/** @component list-item */

import React from 'react';
import ReactDOM from 'react-dom';
import PropTypes from 'prop-types';
import omit from 'lodash/omit';
import { UIDConsumer } from 'react-uid';
import SelectableContext, { makeKeyboardKey } from '../SelectableContext';
import ListContext from '../ListContext';
import mapContextToProps from '@restart/context/mapContextToProps';

class ListItem extends React.Component {
  componentDidMount() {
    const { focus, refName, focusOnLoad } = this.props;
    this.verifyStructure();

    focusOnLoad && focus
    && this[refName]
    && this[refName].focus();
  }

  checkElements = tag => {
    const children = Object.values(ReactDOM.findDOMNode(this).childNodes);

    return this.countDOMChildren(children, tag);
  };

  countDOMChildren = (children, tag) =>
    children.reduce(
      (agg, child) => (
        child.tagName === tag
          ? { ...agg, count: (agg.count += 1) }
          : agg
      ), { count: 0, children: children.length }
    );

  getChildrenElements = nameArr => {
    const { children } = this.props;
    let elementCount = 0;

    React.Children.forEach(children, child => {
      if (child && (child.type && nameArr.includes(child.type.displayName))) {
        return elementCount++;
      }
    });

    return (
      elementCount && {
        length: elementCount
      }
    );
  };

  handleClick = (e, eventKey) => {
    const {
      disabled,
      label,
      onClick,
      parentOnSelect,
      value,
    } = this.props;

    if(disabled) {
      e.preventDefault();
      e.stopPropagation();
    }

    e.persist();
    onClick && onClick(e);
    parentOnSelect && parentOnSelect(e, { value, label, eventKey });
  }

  handleKeyDown = (e, eventKey, focusLockTabbableChildren, tabbableChildrenQuery) => {
    const { disabled, onKeyDown, parentKeyDown, value, label } = this.props;

    if(disabled) {
      e.preventDefault();
      e.stopPropagation();
    }
    
    if (focusLockTabbableChildren && e.target) {
      const currListItem = e.target.closest('md-list-item');

      if  (currListItem) {
        const tabbableChildren = currListItem.querySelectorAll(tabbableChildrenQuery);
        if (tabbableChildren.length) {
          if (e.keyCode === 9 && !e.shiftKey) { // TAB only
            // only allow focus of tabbable children if TAB on the current listitem
            if (e.target.classList.contains('md-list-item')) {
              for (let i = 0; i < tabbableChildren.length; i++) {
                if (tabbableChildren[i].tabIndex === -1) {
                  tabbableChildren[i].tabIndex = 0;
                }
              }
            } else if (e.target === tabbableChildren[tabbableChildren.length - 1]) {
              e.preventDefault();
              e.stopPropagation();
              // cycle focus between tabbable children (last tabbable child wil' cycle back to first tabbable child)
              tabbableChildren[0].focus();
            }
          } else if (e.keyCode === 9 && e.shiftKey) { // SHIFT + TAB
            e.preventDefault();
            e.stopPropagation();
            // focus on the tabbable children's associated lisitem
            e.target.closest('.md-list-item').focus();
          }
        }
      }
    }

    e.persist();
    onKeyDown && onKeyDown(e);
    parentKeyDown && parentKeyDown(e, { value, label, eventKey });
  }

  isFocusSwitchedToDifferentListItem = (relatedTarget, tabbableChildren, currListItem) => {
    if (relatedTarget !== currListItem) {
      for (let i = 0; i < tabbableChildren.length; i++) {
        if (tabbableChildren[i] === relatedTarget) {
          return false;
        }
      }
    }

    return true;
  }

  handleBlur = (e, focusLockTabbableChildren, tabbableChildrenQuery) => {
    const { disabled } = this.props;

    if(disabled) {
      e.preventDefault();
      e.stopPropagation();
    }

    if (focusLockTabbableChildren && e.target && e.relatedTarget) {
      const currListItem = e.target.closest('.md-list-item');
      if (currListItem) {
        const tabbableChildren = currListItem.querySelectorAll(tabbableChildrenQuery);
        // only disable focus on tabbable children of the current listitem if focus is changing to another listitem
        if (tabbableChildren.length &&
            this.isFocusSwitchedToDifferentListItem(e.relatedTarget, tabbableChildren, currListItem)
        ) {
          for (let i = 0; i < tabbableChildren.length; i++) {
            if (tabbableChildren[i].tabIndex === 0) {
              tabbableChildren[i].tabIndex = -1;
            }
          }
        }
      }
    }
  }

  verifyStructure() {
    if (!this.props.children) return;

    const anchorCount = this.checkElements('A');
    const checkAllChildren = this.getChildrenElements(['ListItemSection', 'EventOverlay']);
    const checkSectionChildren = this.getChildrenElements(['ListItemSection']);

    if (anchorCount.count > 1) {
      throw new Error(
        'Only 1 primary child anchor tag may be used with ListItem component'
      );
    } else if (anchorCount.count === 1 && anchorCount.children > 1) {
      throw new Error('Anchor tag can not have sibling');
    }

    if (!checkAllChildren) {
      return;
    } else if (checkSectionChildren.length > 3) {
      throw new Error(
        `Only 3 ListItemSection components can be used as children. You've used ${
          checkSectionChildren.length
        }`
      );
    }
  }

  render() {
    const {
      active,
      children,
      className,
      customAnchorNode,
      customRefProp,
      disabled,
      eventKey,
      focus,
      focusLockTabbableChildren,
      isReadOnly,
      keyboardKey,
      label,
      link,
      refName,
      role,
      separator,
      tabbableChildrenQuery,
      title,
      type,
      ...props
    } = this.props;

    const keyboardNavKey = makeKeyboardKey(keyboardKey || title || label);

    const otherProps = omit({...props}, [
      'focusOnLoad',
      'id',
      'itemIndex',
      'onClick',
      'onKeyDown',
      'parentKeyDown',
      'parentOnSelect',
      'value',
    ]);

    const setProps = cxtProps => ({
      className:
        'md-list-item' +
        `${(cxtProps.type && ` md-list-item--${cxtProps.type}`) || ''}` +
        `${(cxtProps.active && ` active`) || ''}` +
        `${(disabled && ` disabled`) || ''}` +
        `${(isReadOnly && ` md-list-item--read-only`) || ''}` +
        `${(separator && ` md-list-item--separator`) || ''}` +
        `${(className && ` ${className}`) || ''}` +
        `${(customAnchorNode && customAnchorNode.props.className && ` ${customAnchorNode.props.className}`) || ''}`,
      id: cxtProps.id,
      role: cxtProps.role,
      ...!customAnchorNode && {
        ref: ref => (this[refName] = ref),
        ...link && { href: link }
      },
      ...customAnchorNode && customRefProp && {
        [customRefProp]: ref => this[refName] = ref
      },
      ...!isReadOnly && {
        onClick: e => this.handleClick(e, cxtProps.uniqueKey),
        onKeyDown: e => this.handleKeyDown(e, cxtProps.uniqueKey, focusLockTabbableChildren, tabbableChildrenQuery),
        onBlur: e => this.handleBlur(e, focusLockTabbableChildren, tabbableChildrenQuery),
        tabIndex: (!disabled && cxtProps.focus) ? 0 : -1,
      },
      'data-md-event-key': cxtProps.uniqueKey,
      ...!cxtProps?.ariaConfig?.disableAriaCurrent && {...cxtProps.focus && { 'aria-current': `${cxtProps.focus}` }},
      ...keyboardNavKey && { 'data-md-keyboard-key': keyboardNavKey },
      ...(title || label) && {title: title || label},
      ...otherProps
    });

    const addRefToAnchor = cxtProps => {
      return React.cloneElement(
        customAnchorNode,
        setProps(cxtProps),
        children || customAnchorNode.props.children || label
      );
    };

    const createElement = cxtProps => {
      return React.createElement(
        link ? 'a' : 'div',
        setProps(cxtProps),
        children || label
      );
    };

    return (
      <UIDConsumer name={id => `md-list-item-${id}`}>
        {id => (
          <ListContext.Consumer>
            {listContext => {
              let contextProps = {};

              contextProps.id = this.props.id || id;
              contextProps.uniqueKey = eventKey || contextProps.id;
              contextProps.type = type || (listContext && listContext.type);
              contextProps.focus = focus || (listContext && listContext.focus === contextProps.uniqueKey);
              contextProps.active = active || (listContext && listContext.active === contextProps.uniqueKey);
              contextProps.role = (listContext && listContext.role) || role;
              contextProps.ariaConfig = listContext && listContext.ariaConfig;

              return (
                customAnchorNode
                  ? addRefToAnchor(contextProps)
                  : createElement(contextProps)
              );
            }}
          </ListContext.Consumer>
        )}
      </UIDConsumer>
    );
  }
}

ListItem.propTypes = {
  /** @prop Active prop to help determine styles | false */
  active: PropTypes.bool,
  /** @prop Children nodes to render inside ListItem | null  */
  children: PropTypes.node,
  /** @prop Optional css class string | '' */
  className: PropTypes.string,
  /** @prop Node in which the selection begins | null */
  customAnchorNode: PropTypes.element,
  /** @prop ListItem Custom Prop Name for child with custom Ref | null */
  customRefProp: PropTypes.string,
  /** @prop Disabled attribute for ListItem to determine styles | false */
  disabled: PropTypes.bool,
  /** @prop Unique string used for tracking events among ancestors | '' */
  eventKey: PropTypes.string,
  /** @prop Specifies if ListItem should automatically get focus | false */
  focus: PropTypes.bool,
  /** @prop Locks focus to cycle between all tabbable children  | false */
  focusLockTabbableChildren: PropTypes.bool,
  /** @prop Specifies if ListItem should automatically get focus when page loads | false */
  focusOnLoad: PropTypes.bool,
  /** @prop Sets ListItem id | null */
  id: PropTypes.string,
  /** @prop Determines if ListItem is clickable | false */
  isReadOnly: PropTypes.bool,
  /** @prop ListItem index number | null */
  itemIndex: PropTypes.number,
  /** @prop Unique string used for keyboard navigation | '' */
  keyboardKey: PropTypes.string,
  /** @prop ListItem label text | '' */
  label: PropTypes.string,
  /** @prop external link associated input | '' */
  link: PropTypes.string,
  /** @prop Callback function invoked by user tapping on ListItem | null */
  onClick: PropTypes.func,
  /** @prop Callback function invoked by user pressing on a key | null */
  onKeyDown: PropTypes.func,
  // Internal Context Use Only
  parentKeyDown: PropTypes.func,
  // Internal Context Use Only
  parentOnSelect: PropTypes.func,
  /** @prop ListItem ref name | 'navLink' */
  refName: PropTypes.string,
  /** @prop Aria role | 'listitem' */
  role: PropTypes.string,
  /** @prop Prop that controls whether to show separator or not | false */
  separator: PropTypes.bool,
  /** @prop Query for focusLockTabbableChildren | '' */
  tabbableChildrenQuery: PropTypes.string,
  /** @prop ListItem Title | '' */
  title: PropTypes.string,
  /** @prop ListItem size | '' */
  type: PropTypes.oneOf(['', 'small', 'large', 'xlarge', 'space', 'header', 36, 52, 60]),
  /** @prop ListItem value for OnSelect value | '' */
  value: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.number,
    PropTypes.object,
    PropTypes.array
  ]),
};

ListItem.defaultProps = {
  active: false,
  children: null,
  className: '',
  customAnchorNode: null,
  customRefProp: '',
  disabled: false,
  eventKey: '',
  focus: false,
  focusLockTabbableChildren: false,
  focusOnLoad: false,
  id: null,
  itemIndex: null,
  isReadOnly: false,
  keyboardKey: '',
  label: '',
  link: '',
  onClick: null,
  onKeyDown: null,
  parentKeyDown: null,
  parentOnSelect: null,
  refName: 'navLink',
  role: 'listitem',
  separator: false,
  tabbableChildrenQuery: '',
  title: '',
  type: '',
  value: '',
};

ListItem.displayName = 'ListItem';

export default mapContextToProps(
  SelectableContext,
  context => context,
  ListItem
);

// vue/src/lib/list-item/index.vue
<script>
import assign from 'lodash/assign';
import kebabCase from 'lodash/kebabCase';
import omit from 'lodash/omit';
import uniqueId from 'lodash/uniqueId';
import cloneElement from '../utils/cloneElement';

export default {
  name: 'md-list-item',

  data() {
    return {
      uid: uniqueId('md-list-item-')
    }
  },

  render: function (h) {
    const {
      active,
      disabled,
      isReadOnly,
      keyboardKey,
      label,
      link,
      refName,
      separator,
      title,
      ...props
    } = this.$props;

    const keyboardNavKey = kebabCase(keyboardKey || title || label);

    const otherProps = omit({...props}, [
      'focus',
      'focusOnLoad',
      'itemIndex',
      'role',
      'type',
      'value',
    ]);

    const getComponentData = () => ({
      class:
        'md-list-item' +
        `${(this.getType && ` md-list-item--${this.getType}`) || ''}` +
        `${(active && ` active`) || ''}` +
        `${(disabled && ` disabled`) || ''}` +
        `${(isReadOnly && ` md-list-item--read-only`) || ''}` +
        `${(separator && ` md-list-item--separator`) || ''}`,
      attrs: {
        'aria-current': this.getFocus,
        'data-md-event-key': this.getEventKey,
        role: this.getRole,
        ref: refName,
        ...!isReadOnly && { tabindex: !disabled && this.getFocus ? 0 : -1 },
        ...link && { href: link },
        ...keyboardNavKey && { 'data-md-keyboard-key': keyboardNavKey },
        ...(title || label) && { title: title || label },
        ...otherProps,
      },
      on: {
        ...!isReadOnly && {
          click: this.handleClick,
          keydown: this.handleKeyDown
        },
      },
    });

    const customElement = () => {
      const node = this.$slots.customAnchor[0];
      const data = getComponentData();
      node.data.class = data.class;
      assign(node.data.attrs, data.attrs);
      assign(node.data.on, data.on);

      return cloneElement(
        node,
        h,
        {},
        this.$slots.default
          || node.children
          || node.componentOptions && node.componentOptions.children
          || [label]
      );
    };

    const defaultElement = () => h(
      link ? 'a' : 'div',
      getComponentData(),
      this.$slots.default || [label]
    );

    return (
      this.$slots.customAnchor
        ? customElement()
        : defaultElement()
    );

  },

  inject: {
    itemFocus: {
      default: null
    },
    itemRole: {
      default: null
    },
    itemType: {
      default: null
    },
    parentKeyDown: {
      default: null
    },
    parentOnSelect: {
      default: null
    }
  },

  props: {
    /** @prop Active prop to help determine styles | false */
    active: Boolean,
    /** @prop Disabled attribute for ListItem to determine styles | false */
    disabled: Boolean,
    /** @prop Unique string used for tracking events among ancestors | '' */
    eventKey: {
      type: String,
      default: ''
    },
    /** @prop Specifies if ListItem should automatically get focus | false */
    focus: Boolean,
    /** @prop Specifies if ListItem should automatically get focus when page loads | false */
    focusOnLoad: Boolean,
    /** @prop Determines if ListItem is clickable | false */
    isReadOnly: Boolean,
    /** @prop ListItem index number | null */
    itemIndex: Number,
    /** @prop Unique string used for keyboard navigation | '' */
    keyboardKey: {
      type: String,
      default: ''
    },
    /** @prop ListItem label text | '' */
    label: {
      type: String,
      default: ''
    },
    /** @prop external link associated input | '' */
    link: {
      type: String,
      default: ''
    },
    /** @prop ListItem ref name | 'navLink' */
    refName: {
      type: String,
      default: 'navLink'
    },
    /** @prop Aria role | 'listitem' */
    role: {
      type: String,
      default: 'listitem'
    },
    /** @prop Prop that controls whether to show separator or not | false */
    separator: Boolean,
    /** @prop ListItem Title | '' */
    title: {
      type: String,
      default: ''
    },
    /** @prop ListItem size | '' */
    type: {
      type: [Number, String],
      default: '',
      validator: function (value) {
        return ['', 'small', 'large', 'xlarge', 'space', 'header', 36, 52, 60].indexOf(value) !== -1
      }
    },
    /** @prop ListItem value for OnSelect value | '' */
    value: {
      type: [Number, String, Object, Array],
      default: ''
    },
  },

  computed: {
    getEventKey() {
      return this.$attrs.id || this.eventKey || this.uid;
    },

    getFocus() {
      return this.focus || this.itemFocus === this.getEventKey;
    },

    getRole() {
      return this.itemRole || this.role;
    },

    getType() {
      return this.itemType || this.type;
    },

  },

  beforeMount() {
    if (!this.$slots.default) return;
    const checkAllChildren = this.getChildrenElements(['ListItemSection', 'EventOverlay']);
    const checkSectionChildren = this.getChildrenElements(['ListItemSection']);

    if (!checkAllChildren) {
      return;
    } else if (checkSectionChildren.length > 3) {
      throw new Error(
        `Only 3 ListItemSection components can be used as children. You've used ${
          checkSectionChildren.length
        }`
      );
    }
  },

  mounted() {
    const anchorCount = this.checkElements('A');
    const { refName, focusOnLoad } = this.$props;

    if (anchorCount.count > 1) {
      throw new Error(
        'Only 1 primary child anchor tag may be used with ListItem component'
      );
    } else if (anchorCount.count === 1 && anchorCount.children > 1) {
      throw new Error('Anchor tag can not have sibling');
    }

    focusOnLoad && this.getFocus
      && this.$refs[refName]
      && this.$refs[refName].focus();
  },

  methods: {
    checkElements(tag) {
      const children = Object.values(this.$el.childNodes);

      return this.countDOMChildren(children, tag);
    },

    countDOMChildren(children, tag) {
      return children.reduce(
        (agg, child) => (
          child.tagName === tag
            ? { ...agg, count: (agg.count += 1) }
            : agg
        ), { count: 0, children: children.length }
      );
    },

    getChildrenElements(nameArr) {
      let elementCount = 0;

      this.$slots.default.forEach(child => {
        if (child && (child.type && nameArr.includes(child.type.displayName))) {
          return elementCount++;
        }
      });

      return (
        elementCount && {
          length: elementCount
        }
      );
    },

    handleClick(e) {
      const {
        disabled,
        label,
        value,
      } = this.$props;

      if(disabled) {
        e.preventDefault();
        e.stopPropagation();
      }

      this.$emit('click', e);
      this.parentOnSelect && this.parentOnSelect(e, { value, label, eventKey: this.getEventKey });
    },

    handleKeyDown(e) {
      const {
        disabled,
        value,
        label,
      } = this.$props;

      if(disabled) {
        e.preventDefault();
        e.stopPropagation();
      }

      this.$emit('keydown', e);
      this.parentKeyDown && this.parentKeyDown(e, { value, label, eventKey: this.getEventKey });
    },
  },
};
</script>
