// angular/src/lib/modal/modal-header.component.ts
/** @component modal-header */

import {
  Component,
  Input,
  HostBinding,
  HostListener,
} from '@angular/core';
import { ModalRef } from './modal-ref';


@Component({
  selector: 'md-modal-header',
  template: `
  <span class="md-modal__title">{{headerLabel}}</span>
  <span *ngIf="message" class="md-modal__message">{{
    message
  }}</span>
  <button
    *ngIf="showCloseButton"
    class="md-close md-modal__close"
    (click)="close()"
    (keydown)="handleKeydown($event)"
    aria-label="close"
    type="button"
  >
  </button>
  `,
})
export class ModalHeaderComponent {
  /** @prop Optional css class string | '' */
  @Input() public class: string = '';
  /** @prop ModalHeader label text | '' */
  @Input() public headerLabel: string = '';
  /** @prop  Modal message | '' */
  @Input() public message: string = '';
  /** @prop show/hide close button | true */
  @Input() public showCloseButton: boolean = true;

  @HostBinding('class') get className(): string {
    return (
      'md-modal__header' + `${(this.class && ` ${this.class}`) || ''}` + ``
    );
  }


  @HostListener('document:keydown.escape', ['$event']) handleKeydown(
    _: KeyboardEvent
  ) {
    this.close();
  }

  constructor(private modalRef: ModalRef) {}

  close() {
    this.modalRef.close();
  }
}

// vue/src/lib/modal-header/index.vue
<template>
  <div class="md-modal__header">
    <slot></slot>
    <span v-if="!$slots.default" class="md-modal__title">{{ headerLabel }}</span>
    <span v-if="!$slots.default && message" class="md-modal__message">{{ message }}</span>
    <md-close-icon
      v-if="showCloseButton"
      class="md-modal__close"
      @click="handleClose"
      v-bind="closeBtnProps"
    />
  </div>
</template>

<script>
export default {
  name: 'md-modal-header',

  inject: {
    close: {
      default: null
    }
  },

  props: {
    /** @prop Props to be passed to close button | null */
    closeBtnProps: Object,
    /** @prop ModalHeader label text | '' */
    headerLabel: {
      type: String,
      default: ''
    },
    /** @prop Modal message | '' */
    message: {
      type: String,
      default: ''
    },
    /** @prop show/hide close button | true */
    showCloseButton: {
      type: Boolean,
      default: true
    },
  },

  methods: {
    handleClose(e) {
      this.close && this.close(e);
    }
  },

};
</script>
