// react/package/es/DatePicker/index.js
function _extends() { _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }

function _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; }

function _inheritsLoose(subClass, superClass) { subClass.prototype = Object.create(superClass.prototype); subClass.prototype.constructor = subClass; subClass.__proto__ = superClass; }

/** @component date-picker */
import React from 'react';
import PropTypes from 'prop-types';
import { EventOverlay } from "./..";
import DatePickerCalendar from "./DatePickerCalendar";
import DatePickerContext from "../DatePickerContext";
import { addDays, addWeeks, isDayDisabled, isSameDay, subtractDays, subtractWeeks } from "../utils/dateUtils";
import moment from 'moment';
import omit from 'lodash/omit';

var DatePicker = /*#__PURE__*/function (_React$Component) {
  _inheritsLoose(DatePicker, _React$Component);

  function DatePicker(props) {
    var _this;

    _this = _React$Component.call(this, props) || this;

    _this.setOpen = function (open) {
      _this.setState({
        isOpen: open
      });
    };

    _this.handleSelect = function (event, date) {
      var shouldCloseOnSelect = _this.props.shouldCloseOnSelect;

      _this.setPreSelection(date, event);

      _this.setSelected(date, event);

      shouldCloseOnSelect && _this.setOpen(false);
    };

    _this.setSelected = function (date, event) {
      var onSelect = _this.props.onSelect;
      !isDayDisabled(date, _this.props) && _this.setState({
        selected: date
      }, function () {
        return onSelect && onSelect(event, date.toDate());
      });
    };

    _this.setPreSelection = function (date, event) {
      var onChange = _this.props.onChange;
      !isDayDisabled(date, _this.props) && _this.setState({
        focus: date
      }, function () {
        return onChange && onChange(event, date.toDate());
      });
    };

    _this.setMonthNavFocus = function () {
      var monthNavFocus = _this.state.monthNavFocus;

      if (monthNavFocus === 'prev') {
        _this.setState({
          monthNavFocus: 'next'
        });
      } else {
        _this.setState({
          monthNavFocus: 'prev'
        });
      }
    };

    _this.handleInputClick = function () {
      _this.setOpen(true);
    };

    _this.handleInputKeyDown = function (event) {
      var _this$state = _this.state,
          focus = _this$state.focus,
          isOpen = _this$state.isOpen;
      var flag = false;
      var copy = moment(focus);
      var datePickerDayHasFocus = document.activeElement.className.includes('md-datepicker__day--focus');

      var tabOverride = function tabOverride(event) {
        _this.setMonthNavFocus();

        event.preventDefault();
      };

      switch (!event.shiftKey && event.which) {
        case 9:
          // Tab
          isOpen && tabOverride(event);
          break;

        case 32:
        case 13:
          if (!isOpen) {
            _this.handleInputClick();
          } else if ((moment.isMoment(focus) || moment.isDate(focus)) && datePickerDayHasFocus) {
            _this.handleSelect(event, copy);
          }

          flag = true;
          break;

        case 27:
          // escape
          _this.setOpen(false);

          break;

        case 38:
          // up
          _this.setPreSelection(subtractWeeks(copy, 1));

          flag = true;
          break;

        case 37:
          // left
          _this.setPreSelection(subtractDays(copy, 1));

          flag = true;
          break;

        case 39:
          // right
          _this.setPreSelection(addDays(copy, 1));

          flag = true;
          break;

        case 40:
          // bottom
          _this.setPreSelection(addWeeks(copy, 1));

          flag = true;
          break;

        default:
          break;
      }

      switch (event.shiftKey && event.which) {
        case 9:
          // Tab
          isOpen && tabOverride(event);
          break;

        default:
          break;
      }

      if (flag) {
        event.stopPropagation();
        event.preventDefault();
      }
    };

    _this.state = {
      anchorNode: null,
      focus: null,
      isOpen: false,
      selected: null,
      monthNavFocus: ''
    };
    return _this;
  }

  var _proto = DatePicker.prototype;

  _proto.componentDidMount = function componentDidMount() {
    var selectedDate = moment(this.props.selectedDate);
    var isValid = selectedDate.isValid() && !isDayDisabled(selectedDate, this.props);
    isValid && this.setPreSelection(selectedDate);
    isValid && this.setSelected(selectedDate);
  };

  _proto.componentDidUpdate = function componentDidUpdate(prevProps) {
    var selectedDate = moment(this.props.selectedDate);
    var prevSelectedDate = moment(prevProps.selectedDate);
    var isValid = selectedDate.isValid() && !isDayDisabled(selectedDate, this.props);

    if (isValid && !isSameDay(prevSelectedDate, selectedDate)) {
      this.setSelected(selectedDate);
      this.setPreSelection(selectedDate);
    }
  };

  _proto.render = function render() {
    var _this2 = this;

    var _this$props = this.props,
        children = _this$props.children,
        className = _this$props.className,
        direction = _this$props.direction,
        isDynamic = _this$props.isDynamic,
        onMonthChange = _this$props.onMonthChange,
        showArrow = _this$props.showArrow,
        props = _objectWithoutPropertiesLoose(_this$props, ["children", "className", "direction", "isDynamic", "onMonthChange", "showArrow"]);

    var _this$state2 = this.state,
        selected = _this$state2.selected,
        focus = _this$state2.focus,
        anchorNode = _this$state2.anchorNode,
        isOpen = _this$state2.isOpen,
        monthNavFocus = _this$state2.monthNavFocus;
    var dpContext = {
      handleDayClick: function handleDayClick(event, date) {
        return _this2.handleSelect(event, date);
      },
      handleMonthChange: function handleMonthChange(event, date) {
        return onMonthChange && onMonthChange(event, date.toDate());
      },
      focus: focus,
      selected: selected
    };
    var trigger = React.cloneElement(children, {
      ref: function ref(_ref) {
        return !_this2.state.anchorNode && _this2.setState({
          anchorNode: _ref
        });
      },
      onClick: this.handleInputClick,
      onKeyDown: this.handleInputKeyDown
    });
    var otherProps = omit(_extends({}, props), ['onSelect', 'onChange', 'onMonthChange', 'shouldCloseOnSelect']);
    var calendar = React.createElement(DatePickerContext.Provider, {
      value: dpContext
    }, React.createElement(DatePickerCalendar, _extends({
      monthNavFocus: monthNavFocus
    }, otherProps)));
    var content = React.createElement(EventOverlay, {
      allowClickAway: true,
      isOpen: isOpen,
      anchorNode: anchorNode,
      close: function close() {
        return _this2.setOpen(false);
      },
      direction: direction,
      showArrow: showArrow,
      isDynamic: isDynamic,
      onKeyDown: this.handleInputKeyDown
    }, calendar);
    return React.createElement("div", {
      className: 'md-datepicker-container' + ("" + (className && " " + className || ''))
    }, trigger, isOpen && content);
  };

  return DatePicker;
}(React.Component);

DatePicker.propTypes = {
  /** @prop Children nodes to render inside DatePicker | null */
  children: PropTypes.element,

  /** @prop Optional css class string | '' */
  className: PropTypes.string,

  /** @prop Set the direction in which the DatePicker opens | 'bottom-center' */
  direction: PropTypes.string,

  /** @prop Function to filter Dates | null */
  filterDate: PropTypes.func,

  /** @prop Sets the DatePicker EventOverlay to be dynamic | true */
  isDynamic: PropTypes.bool,

  /** @prop Sets the language of the DatePicker | 'en' */
  locale: PropTypes.string,

  /** @prop Sets the last date in which the DatePicker does not disable | null */
  maxDate: PropTypes.instanceOf(Date),

  /** @prop Sets the first date in which the DatePicker does not disable | null */
  minDate: PropTypes.instanceOf(Date),

  /** @prop Sets the format of the month | 'MMMM YYYY' */
  monthFormat: PropTypes.string,

  /** @prop Text to display for blindness accessibility features | 'next' */
  nextArialLabel: PropTypes.string,

  /** @prop Handler invoked when user makes a chnage within the DatePicker | null */
  onChange: PropTypes.func,

  /** @prop Handler invoked when user makes a change to the selected month within DatePicker | null */
  onMonthChange: PropTypes.func,

  /** @prop Handler invoked when user selects a date within DatePicker | null */
  onSelect: PropTypes.func,

  /** @prop Text to display for blindness accessibility features | 'previous' */
  previousArialLabel: PropTypes.string,

  /** @prop Initial Selected Date for DatePicker | moment().toDate()  */
  selectedDate: PropTypes.instanceOf(Date),

  /** @prop Determines if the DatePicker should close when a date is selected | true */
  shouldCloseOnSelect: PropTypes.bool,

  /** @prop Determines if the DatePicker should show the open/close arrow | false */
  showArrow: PropTypes.bool
};
DatePicker.defaultProps = {
  children: null,
  className: '',
  direction: 'bottom-center',
  filterDate: null,
  isDynamic: true,
  locale: 'en',
  maxDate: null,
  minDate: null,
  monthFormat: 'MMMM YYYY',
  nextArialLabel: '',
  onChange: null,
  onMonthChange: null,
  onSelect: null,
  previousArialLabel: '',
  selectedDate: moment().toDate(),
  shouldCloseOnSelect: true,
  showArrow: false
};
DatePicker.displayName = 'DatePicker';
export default DatePicker;

// vue/src/lib/date-picker/index.vue
<script>
import {
  addDays,
  addWeeks,
  isDayDisabled,
  isSameDay,
  subtractDays,
  subtractWeeks,
} from '../utils/dateUtils.js';
import moment from 'moment';
import assign from 'lodash/assign';
import omit from 'lodash/omit';

export default {
  name: 'md-date-picker',

  data() {
    return {
      focus: null,
      isOpen: false,
      selected: null,
    }
  },

  provide () {
    return {
      getFocus: () => this.focus,
      getSelected: () => this.selected,
      handleDayClick: (event, date) => this.handleSelect(event, date),
      handleMonthChange: (event, date) => { this.$emit('monthChange', event, date.toDate()); },
    }
  },

  render(h) {
    const {
      direction,
      isDynamic,
      showArrow,
      ...props
    } = this.$props;

    const { selected, focus, isOpen } = this.$data;

    const trigger = this.$slots.default && this.$slots.default[0];
    const nativeOn = {
      click: this.handleInputClick,
      keydown: this.handleInputKeyDown
    };
    const attrs = {
      ref: 'trigger'
    };
    if (trigger && trigger.data) {
      trigger.data.on = {};
      trigger.data.nativeOn = {};
      assign(trigger.data.attrs, attrs);
      assign(trigger.data.on, nativeOn);
      assign(trigger.data.nativeOn, nativeOn);
    }

    const otherProps = omit({...props}, ['shouldCloseOnSelect']);

    const calendar = (
      <md-date-picker-calendar
        focus={focus}
        selected={selected}
        {...{props: otherProps}}
      />
    );

    const content = (
      <md-event-overlay
        allowClickAway={true}
        isOpen={isOpen}
        anchorNode={trigger.elm}
        onClose={() => this.setOpen(false)}
        direction={direction}
        showArrow={showArrow}
        isDynamic={isDynamic}
      >
        {calendar}
      </md-event-overlay>
    );

    return (
      <div class='md-datepicker-container'>
        {trigger}
        {isOpen && content}
      </div>
    );
  },

  props: {
    /** @prop Set the direction in which the DatePicker opens | 'bottom-center' */
    direction: String,
    /** @prop Function to filter Dates | null */
    filterDate: Function,
    /** @prop Sets the DatePicker md-event-overlay to be dynamic | true */
    isDynamic: {
      type: Boolean,
      default: true
    },
    /** @prop Sets the language of the DatePicker | 'en' */
    locale: {
      type: String,
      default: 'en'
    },
    /** @prop Sets the last date in which the DatePicker does not disable | null */
    maxDate: Date,
    /** @prop Sets the first date in which the DatePicker does not disable | null */
    minDate: Date,
    /** @prop Sets the format of the month | 'MMMM YYYY' */
    monthFormat: {
      type: String,
      default: 'MMMM YYYY'
    },
    /** @prop Text to display for blindness accessibility features | 'next' */
    nextArialLabel: {
      type: String,
      default: 'next'
    },
    /** @prop Text to display for blindness accessibility features | 'previous' */
    previousArialLabel: {
      type: String,
      default: 'previous'
    },
    /** @prop Initial Selected Date for DatePicker | moment().toDate()  */
    selectedDate: {
      type: Date,
      default: () => moment().toDate()
    },
    /** @prop Determines if the DatePicker should close when a date is selected | true */
    shouldCloseOnSelect: {
      type: Boolean,
      default: true
    },
    /** @prop Determines if the DatePicker should show the open/close arrow | false */
    showArrow: Boolean,
  },

  mounted() {
    const selectedDate = moment(this.selectedDate);
    const isValid =
      selectedDate.isValid()
      && !isDayDisabled(selectedDate, this.$props);

    isValid && this.setPreSelection(selectedDate);
    isValid && this.setSelected(selectedDate);
  },

  watch: {
    selectedDate(val, oldVal) {
      const selectedDate = moment(val);
      const prevSelectedDate = moment(oldVal);
      const isValid =
        selectedDate.isValid()
        && !isDayDisabled(selectedDate, this.$props);
      if(
        isValid
        && !isSameDay(prevSelectedDate, selectedDate)
      ) {
        this.setSelected(selectedDate);
        this.setPreSelection(selectedDate);
      }
    }
  },

  methods: {
    setOpen(open) {
      this.isOpen = open;
    },

    handleSelect(event, date){
      const { shouldCloseOnSelect } = this.$props;
      this.setPreSelection(date, event);
      this.setSelected(date, event);
      shouldCloseOnSelect && this.setOpen(false);
    },

    setSelected(date, event) {
      if (!isDayDisabled(date, this.$props)) {
        this.selected = date;
        this.$emit('select', event, date.toDate());
      }
    },

    setPreSelection(date, event) {
      if (!isDayDisabled(date, this.$props)) {
        this.focus = date;
        this.$emit('change', event, date.toDate());
      }
    },

    handleInputClick() {
      this.setOpen(true);
    },

    handleInputKeyDown(event) {
      const { focus, isOpen } = this.$data;

      let flag = false;
      const copy = moment(focus);

      switch (!event.shiftKey && event.which) {
        case 32:
        case 13:
          if(!isOpen) {
            this.handleInputClick();
          } else if (
            moment.isMoment(focus) ||
            moment.isDate(focus)
          ) {
            this.handleSelect(event, copy);
          }
          flag = true;
          break;

        case 38: //up
          this.setPreSelection(subtractWeeks(copy, 1));
          flag = true;
          break;
        case 37:// left
          this.setPreSelection(subtractDays(copy, 1));
          flag = true;
          break;

        case 39: //right
          this.setPreSelection(addDays(copy, 1));
          flag = true;
          break;

        case 40: //bottom
          this.setPreSelection(addWeeks(copy, 1));
          flag = true;
          break;

        default:
          break;
      }

      if (flag) {
        event.stopPropagation();
        event.preventDefault();
      }
    },
  },
};
</script>
